### ISSUE TITLE
 Anzeige der Dateigröße fehlerhaft 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Theme#109]
Meldung:
"Hallo, wenn ich Dateien auf fau.de im Text hinzufüge, wird die Dateigröße nicht mit angegeben, Wenn der Links zur Datei mit megli.zuv.... geschrieben wird, funktioniert es."

Unklare Meldung. Bitte um Details.

**Comment by xwolfde** [comment]
Hat das je funktioniert? Wo und wie? @rvdforst

**Comment by wrcg** [comment]
mit fau.de im Dateilink hat es meines Wissens noch nie funktioniert, nur mit megli.zuv... hat es ohne Schwierigkeiten geklappt.

**Comment by wrkb** [comment]
@wrcg Cathrin, wir müssen prüfen. mal gehts, mal nicht...

**Comment by rvdforst** [comment]
Screenshots bitte.

**Comment by wrkb** [comment]
Kommen. Issue liegt erstmal bei uns.

**Comment by wrkb** [comment]
Symptom:

Links auf megli.zuv.fau.... werden korrekt angezeigt: https://www.fau.de/international/wege-ins-ausland/studieren-im-ausland/austauschprogramme-des-ria/

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6326176/338e98be-bb4f-11e4-96e3-915cfc8c36a3.JPG)

Links auf fau.de werden nicht korrekt angezeigt: https://www.fau.de/intranet/service-fuer-studium-und-lehre/studienprogrammentwicklung/

![unbenannt2](https://cloud.githubusercontent.com/assets/9445370/6326188/5ea9ceec-bb4f-11e4-8449-2488596dee67.JPG)

**Comment by xwolfde** [comment]
@rvdforst Wo kommt das her? Im Theme finde ich das nicht. Das muss irgendein Plugin produzieren.

**Comment by rvdforst** [comment]
Die Icons und die Dateigröße werden vom MimeType Icons-Plugin erzeugt. Siehe Einstellungen > MimeType Icons. Dieses Plugin wurde vom Entwickler am Juni 2014 aktualisiert.

**Comment by xwolfde** [comment]
Und das bedeutet...?

**Comment by rvdforst** [comment]
Das bedeutet, dass ich das Plugin überarbeitet muss.

**Comment by xwolfde** [comment]
Seufz.. wir können doch nicht jedes Plugin überarbeiten...

**Comment by xwolfde** [comment]
Wie verfahren wir hier weiter? Bei einigen neuen Sites hab ich gesehen, daß die Size da nun richtig stand. Wurde das Plugin aktualisiert?

**Comment by xwolfde** [comment]
auf der aktuellen site gelöst wie ich sah. Plugin wurde wohl erneuert.
