### ISSUE TITLE
Workflow  - Autorenrechte werden bei Versionierung übertragen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#111]
Ein Autor, der auf der deutschen Seite Schreibrechte hat, wird bei der Versionierung automatisch Autor der englischen Seite, obwohl er auf der englischen Seite gar nicht als Autor angelegt ist. Das passt nicht: Im englischen Webauftritt gibt es deutlich weniger Autoren.

**Comment by xwolfde** [comment]
Wer soll denn dann stattdessen Autor werden? 
Irgendein "Autor" muss zugeordnet werden.

**Comment by wrcg** [comment]
nur die Webredaktion. Andere Autoren sollen nach unserem Workflow im englischen Auftritt nicht arbeiten können.

**Comment by xwolfde** [comment]
Die Antwort hilft nicht. Das Theme kennt die "Webredaktion" nicht.  
Erst recht nicht bei einem Einsatz in einer Fakultät.
Wir brauchen also ein definierten Account, der bei Multisite-Domains die Ersatzfunktion einnimmt, wenn (ggf. global über Parameter des Plugins) gesetzt ist, dass vorhandene User nicht übernommen werden.
Ok, das alles ist neue Funktionionalität.

**Comment by wrkb** [comment]
Anmerkung dazu: den Siteadmin nehmen? Wordpress hat ja eine Prozedur für Importe oder beim Löschen eines Users und bietet da den Admin teils sogar als Standard an.

**Comment by rvdforst** [comment]
Um dieses Problem endlich zu beheben. Ich schlage vor:
1. Nur Administratoren und Redakteuren können eine netzwerkweite Versionierung durchführen
2. Wenn der Administrator bzw. Redakteur auf der Zielseite nicht existiert, dann ist das Zieldokument durch ein beliebigen Administrator der Zielseite referenziert.

**Comment by wrkb** [comment]
zu 1: Das wäre für uns okay, ich weiß nicht, ob das als Workflow für alle Einrichtungen passt.
zu 2: Klingt sinnvoll für mich.

**Comment by rvdforst** [comment]
Ist erledigt gemäß den obigen Punkten (1. u. 2.)
