### ISSUE TITLE
Wird das Plugin RRZE-Events auch veröffentlicht werden?

### ISSUE THREAD

**Issue by holzhannes** [RRZE-Webteam/FAU-Theme#115]
Da dieses Theme eine Abhängingkeit zum Plugin RRZE-Events aufweist wäre es sehr gut wenn dieses Plugin auch veröffentlicht würde. Wann ist damit zu rechnen?

**Comment by xwolfde** [comment]
@rvdforst Wie sieht es aus?

**Comment by xwolfde** [comment]
Da ist es: https://github.com/RRZE-Webteam/fau-events
