### ISSUE TITLE
Weitere neue CSS-Probleme 

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#119]
Gerade gemeldet:

"Auf der Startseite fehlt der Blog (https://www.fau.de/studium/im-studium/career-service/)" - Mittlerweile ist er wohl da, aber die Formatierung ist anders/defekt.

"Bei der Beratungsseite funktioniert die Ziehharmonika für die Beschreibung der Beratungsangebote nicht mehr (https://www.fau.de/studium/im-studium/career-service/beratungsangebot/)"

**Comment by xwolfde** [comment]
Fürs CSS ist die Agentur zuständig. Bitte mit der in Verbindung setzen.
Bei mir funktioniert die "Ziehharmonika".

Dringend ist das nicht, weil der Zugriff auf Inhalte nicht gestört ist.

**Comment by wrkb** [comment]
Jo, Rolf empfahl mir, mich an dich zu wenden. Also Agentur, kein Problem.
Bei mir in Chrome sieht das Akkordeon so aus: 
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/5814251/adf88ee2-a089-11e4-914e-2dce9f43c9a2.JPG)

**Comment by xwolfde** [comment]
So sieht es bei mir  mit Firefox auch aus. Dachte das war gewollt? :) Funktionell ist das jedenfalls genauso wie vorher.

**Comment by wrkb** [comment]
Nein (beides). Wir haben weder solche Akkordeons noch sollen die aufgeklappt sein per default :)

**Comment by xwolfde** [comment]
Bug ist ja da; Nur weil er woanders gelöst wird, bitte noch nicht schliessen, solange er nicht auch im GitHub nicht gelöst ist.

**Comment by wrkb** [comment]
Sorry, Verständnisfrage: Basecamp darf also Github doppeln? Oder so sollen die mr-Leute reingucken?

**Comment by xwolfde** [comment]
GitHub ist öffentlich (was gut ist, da auch andere Leute aus der Uni sich hier schon orientieren und das Theme nutzen).  
Mit MR haben wir als Kommunikation nur Basecamp fest vereinbart gehabt. Daher würde ich dort die Bugs, die nur MR betreffen dort auch ggf. doppeln oder dort ein Eintrag machen, der dann hierhin verweist.

**Comment by xwolfde** [comment]
Bei mir ist das noch nicht gelöst? Inhalt ist zwar erreichbar und zuklappbar, aber es ist nicht per Default alles zu und nur das erste offen.

**Comment by xwolfde** [comment]
fixed
