### ISSUE TITLE
Externe Links im Kontext nicht dargestellt (im Backend da)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#123]
https://www.fau.de/intranet/ --> Häufig benötigt.
Duplikat unter https://basecamp.com/1789646/projects/2227875/todos/150378129

**Comment by wrkb** [comment]
Dringend, da Inhalte fehlen und die Kollegen hier aufschlagen. Laut mr kein Bezug zum CSS-Update.

**Comment by xwolfde** [comment]
Bestätigt.
Und nebeninfo: Dort wurde auf fau.de das kommerzielle ACF-Repeater Plugin eingesetzt, damit es überhaupt funktioniert. Meee, ich kann das nichtmal auf meiner Testinstanz nachbauen. So ein Murks.
Dafür hätte man ganz normal ein Widget nutzen sollen, welches von WP schon existiert...

Quicklösung:
In den "Text darunter" die Links einbauen.

Dafür die Überschrift bei text darunter leer machen und in den Text mit einbauen nach den Links.
Habs mal bei Intranet provisorisch gemacht,
Aber dies müssen wir komplett anders bauen, das macht so gar keinen Sinn, wie es gemacht ist.
Muss ich drüber nachdenken.

**Comment by xwolfde** [comment]
geht wieder, aber bessere Lösung muss her für die LInks. das Mit ACF-Repeater muss weg, damit das Theme auch für andere nutzbar ist.
