### ISSUE TITLE
Interne Links in Kontextspalte: Linktitel änderbar machen

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#124]
Wenn wir interne Links in der Kontextspalte platzieren (siehe Screen) dann wird dort der Seitentitel genommen, wir können den nicht überschreiben mit einem eigenen Linktitel. Was aber nötig wird, wenn man es nutzerfreundlich machen will.
ACF-Frage: Ich weiß nicht, inwieweit ihr diese Funktion noch umbaut nach den neuen Vorgaben/Wünschen des RRZE - denn falls ihr das tut, dann wäre es vielleicht doch möglich. 

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/5856250/a607c766-a241-11e4-9a17-e50f90cfbdf2.JPG)

Weiteres, evtl. verwandtes Anliegen, die Kontextspalte betreffend: https://github.com/RRZE-Webteam/FAU-Theme/issues/97

**Comment by xwolfde** [comment]
Das liegt tatsächlich daran, daß dies alles via ACF gemacht wurde.
Das müssen wir zurückbauen und durch eigene Metaboxen ändern. Dann können wir auch eigene änderbare Titel o.ä. andenken. Im Moment geht das aber nicht.

**Comment by xwolfde** [comment]
In Zusammenhang mit #123

**Comment by xwolfde** [comment]
Für Links wäre ein eigener Custom Post Type sinnvoller?

**Comment by wrkb** [comment]
Was wären die Folgen?
Dutzende posts (Typ Linkbox), die getrennt von der Seite gepflegt werden müssen? Das wäre in der Tag kontraproduktiv.

Das ist wohl Wordpress-spezifisch, aber hier würden wir doch die typischen Vorteile moderner CMS wegwerfen - outsourcen quasi - und Bearbeitung der Elemente am betroffenen Objekt immer mehr ausdünnen. Bilder lädt man idealerweise auch an der Seite hoch und nicht über einen eigenen Pfad usw.

Die fehlende Linkverwaltung wäre auch blöd bei internen Links.

ACF für solche Fälle erhalten, geht nicht? Dafür ist es doch da... sinniert der Laie?

**Comment by xwolfde** [comment]
Es geht ja gerade darum, daß ihr aktuell die Links via ACF garnicht strukturiert pflegt. Eben das gegenteil dessen was du schreibst :)   In ACF werden die Links als reine Objekte gepflegt die nur zu dieser einen Seitenresource linken aber sonst nichts. D.h. es gibt da keinerlei Mechanismus um diese Daten zu kontrollieren und z.B. zu prüfen ob Links noch gültig sind oder nicht.

**Comment by xwolfde** [comment]
ich fände es nebenbei als Webredakteur auch sehr wertvoll, irgendwo eine Verwaltung zu haben, die mir *alle* in meiner SIte verwendeten externen Links auflistet, ohne das ich mich durch alle Seiten klickern muss. Insbesondere wenn es in machen OTRS-Meldungen so schön heisst. "Der Link zu ... geht nicht". (Aber nirgends steht, wo der lInk war).

**Comment by xwolfde** [comment]
Statusupdate.
Wir brauchen diese Lösung.
Ziel: Es muss so gut nutzbar sein wie die Widgets. Es muss aber portierbar sein für Mehrfachinstallationen (was ACF nicht ist).  Es muss aber für Pages (und ggf. Artikel) nutzbar sein.

**Comment by wrkb** [comment]
sowas ist mir tatsächlich neu. Wenn es zusätzlich hilft, gern. Aber wenn Autoren dann an ihren Seiten die Links nicht selbst pflegen können und für jeden Klacks hier aufschlagen, dann können wir nicht arbeiten. Das ist ja unser aktuelles Problem ;)
Vielleicht telefonisch besprechen? Das ist einfacher und vielleicht gibt es gar kein Problem?

**Comment by xwolfde** [comment]
Komplex.

In Frage kommende Plugiuns:
https://wordpress.org/plugins/microkids-related-posts/screenshots/
  (Leider Titel nicht änderbar, aber gute SUche, liefert Fehler)
https://wordpress.org/plugins/baw-manual-related-posts/screenshots/
   (Nur für Posts, Artikeltitel nicht änderbar, auch fehlerhaft)
https://wordpress.org/plugins/related-links/screenshots/
   (veraltet, seit 2 jahren ungepflegt. Titel nicht änderbar)
https://wordpress.org/plugins/related-pages/
   (Liefert fehler)

Ich krieg ne Krise. Es geht doch nur um die popelige Linkverwaltung die im wpeditor() sowieso schon enthalten ist...

**Comment by wrkb** [comment]
Das wäre mit dem ACF-Rückbau in der Sidebar erledigt, oder?

**Comment by xwolfde** [comment]
Genau dafür suche ich

**Comment by xwolfde** [comment]
Wenn man nicht alles selbst macht, wird alles nur Murks. Ok, Lösung funktioniert. jetzt muss ich sie noch in Schön machen.

**Comment by xwolfde** [comment]
done in 1.3
