### ISSUE TITLE
Bilder für Designterminologie im Wiki

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#126]
...man braucht ja die Links. Eine elegantere und schnellere Methode habe ich gerade nicht.
![meta-leiste](https://cloud.githubusercontent.com/assets/9445370/5859290/a0810452-a259-11e4-8477-5f4b44d09cc4.JPG)

**Comment by wrkb** [comment]
![header-bereich](https://cloud.githubusercontent.com/assets/9445370/5859378/1a2ce320-a25a-11e4-9bd6-fac1a2bdba7f.JPG)

**Comment by xwolfde** [comment]
?

**Comment by wrkb** [comment]
hierfür: https://github.com/RRZE-Webteam/FAU-Theme/wiki/Design-Terminologie
Nicht okay?

**Comment by xwolfde** [comment]
Öh... kann man im Wiki nicht Bilder direkt zu den Seiten hochladen?

**Comment by wrkb** [comment]
Nee. Nur Links...

**Comment by xwolfde** [comment]
Das ist ja blöd.
Alternativen wären dann ggf.: Unser Blogsystem, FAUBox oder halt eine statische Website bei uns.

**Comment by wrkb** [comment]
Okay, ich ändere das noch und arbeite erstmal ohne Bilder weiter. Also ich lade sie später dazu.

**Comment by wrkb** [comment]
FAUBox? Haben wir Powerfolder? Mail? :)

**Comment by wrkb** [comment]
Okay, dieses Issue kann gelöscht werden.
