### ISSUE TITLE
Unterschiedliche Darstellung Personen fau.de/fau.eu

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#128]
Straße und Raumnummer werden im deutschen mit mehr Abstand nach oben angezeigt, zudem nicht in einer Zeile. Das müsste doch gleich sein?

(Ist eine Aufgabe für medienreaktor, habe sie informiert)

**Comment by xwolfde** [comment]
für @danielkestler  :)

**Comment by xwolfde** [comment]
Nope. Das ist alles richtig so. Da ist allenfalls ein optischer Irrtum, weil bei fau.eu noch eine Zeile mehr da ist.
![abstaende-adresse-de-eu](https://cloud.githubusercontent.com/assets/1070669/5977964/7797c46a-a89c-11e4-852a-d07154a61d41.jpg)
