### ISSUE TITLE
Custom Post Type „Stipendium, Austauschprogramm, Stiftung"

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#13]
Soll für Einheitlichkeit und einfache Pflege von Stipendien sorgen.
Bislang: Chaos aus Tabellen, aufwändigen Assistenten, Listen

Wenn der Inhalt einfach bleibt (Titel, Text, Text, Link, PDF, Ablaufdatum) könnte man mit weiteren optionalen Freitextfeldern den CPT vielleicht auch für so lästige Dinge wie Stiftungslisten nutzen, die auch nicht mehr Details benötigen.

**Comment by xwolfde** [comment]
inzwischen durch Accordions gelöst

**Comment by wrkb** [comment]
Wie was? Welche Akkordeons?
Nein, das wäre ein ganz neuer Post Type, den wir noch zusammen definieren müssten. Kann das gerne nochmal erläutern, damit du einschätzen kannst, wieviel Aufwand das ist und ob wir es schieben müssen.

**Comment by xwolfde** [comment]
Sind Content-Seiten. Nutz die Macht (des Editors), Luke :)

Für ein neues Plugin oder CPT gibt es unsererseits keinen zeitlichen Spielraum. Ihr seit schneller dabei, den Content in Seiten reinzuklopfen als das wir ein Plugin dafür machen, es testen etc pp und ihr dann den Content in  den Plugin-Felder eingebt.

**Comment by wrkb** [comment]
Hätteste auch früher sagen können ;)
Aber ja, ich habe mich eh gewundert, wie ihr das schaffen wollte. Es wäre sehr aufwändig.
