### ISSUE TITLE
Backend: Letzte Optimierungen für Autoren für Schulung

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#133]
...ist das auch FAU-Theme? Wo sonst sollte ich es ggf. verschieben?

Folgendes muss vor der Schulung bitte noch umgesetzt werden (Ergänzungen folgen als Kommentar):

# Glossar
Dropdown für die Filterun nach Autoren: Bitte Namen verwenden, nicht IdM-Kürzel. (Vorschlag: Nachname, dann Vorname aus dem Profil, nicht der öffentliche Name. Sortierung nach Nachname!). Aktuell sind noch die Kürzel zu sehen.
![autorenangabe](https://cloud.githubusercontent.com/assets/9445370/5917344/f762797a-a61b-11e4-8cff-7e359346db00.jpg)

# Seitenliste
Filterung (Dropdown) nach Autor (Name, nicht IdM-Kürzel)
Filterung nach Schlagwort

# Mediendatenbank
Filterung der Medien nach Autor (Name, nicht IdM-Kürzel)

Ich habe wieder vergessen, ob man die Metaboxen via "Optionen" technisch ausblenden kann für Autoren, so dass sie nicht einschaltbar sind. Falls ja, hier unsere Vorstellung für den Inhaltstyp "Seiten" als Screenshot, falls nicht, ist es hier eben dokumentiert, wie es aussehen soll :)
![optionen](https://cloud.githubusercontent.com/assets/9445370/5917192/6c1a4678-a61a-11e4-933d-74cb16685c90.JPG)

Für den Inhaltstyp "Glossar":
![golssaroptionen](https://cloud.githubusercontent.com/assets/9445370/5917251/0220cb1a-a61b-11e4-82ff-810bf4cbdf1e.JPG)

# Weiteres

Die Box "Werbebanner einblenden dürfte für Autoren nicht zugänglich sein. 

Frage: Dürfen Autoren Ihr Passwort selbst neu setzen? Es gibt ja bislang keine Mindeststandards für die Sicherheit eines Passworts. (Ich bin nicht grundsätzlich dagegen, weise nur auf die möglichen unsicheren Passwörter als Folge hin.)

**Comment by xwolfde** [comment]
Welches Plugin erstellt denn diese Auswahlliste der Autoren? Es ist weder im Theme, noch FAU-Plugin, noch Workflow, noch UnivIS. @rvdforst ?

**Comment by wrkb** [comment]
Bei der Seitenliste: Die Autoren sehen keine Schlagworte in der Metabox (im Gegensatz zu Kategorien). Vergeben sollen sie tatsächlich auch keine. Wenn also die Filterung der Liste nach Schlagworten daher nicht geht, ist das auch okay für uns.

Es wäre nur ein schöner Mehrwert, wenn die Autoren sehen, mit welchen Suchoptimierungen via Schlagwort die Seiten von uns ausgestattet wurden/welche Seiten wie optimiert wurden.

**Comment by xwolfde** [comment]
Filterung nach Schlagwort macht nicht viel sinn: Das würde erstmal ne lange Liste werden. Aber dann ist man schnell, mit tippt einfach das WOrt nach dem man sucht un welches in Seiten vorhanden sein sollte, oben rechts in den Suchschlitz.

**Comment by xwolfde** [comment]
bzgl: Werbebanner einblenden: Habs sichtbar gemacht, weil Autoren Seiten eh nicht publishen können. D.h. die können dann in ihrer Autorenschaft schon eine Werbung auswählen, aber Redakteure müssen es eh noch kontrollieren.

**Comment by xwolfde** [comment]
Die Passworte haben keine Relevanz, da das Login nur noch über SSO gehen soll.

**Comment by wrkb** [comment]
Schlagworte: Okay, dann gern auch ohne (nur bei Seiten! Anderswo haben sie eine andere Funktion!)
Werbebanner: Guter Einwand, dann soll es bleiben.
Passworte: OK.

**Comment by wrkb** [comment]
# Punkt/Workflow-Station "Neue Version"

Ich weiß, wir hatten das schon ein- oder zweimal angesprochen. Aber aus eigener Erfahrung und beim Prüfen der Abläufe für Autoren müssen wir sagen: Der Button "Neue Version" in der Seitenliste _muss_ in die Bearbeitungsansicht einer Seite, um akzeptiert zu werden. Die Leute haben die Möglichkeit, auf eine Seite zu navigieren, dort auf "Seite bearbeiten" zu klicken. Um sie zu überzeugen, auch eine neue Version zu erzeugen, wenn die Seite Umstrukturierungen/größere Änderungen erfährt, können wir sie nicht zurück ins Dashboard zur Seitenliste schicken.

Wo genau der Link im Editor steht, ist nicht so wichtig wie die Tatsache, _dass_ er da steht. Wir selber vergessen das immer wieder, auch wenn es auch eine Routine- und Disziplinfrage ist.

Was genau hindert uns am Einbau? Dass der Link zur Seiten-ID dynamisch erzeugt wird? Oder die Möglichkeit, HTML-Links zu hinterlegen in der Ansicht? Letzteres sollte ja über die Hilfstexte gehen notfalls?

@danielkestler Hast du evtl. Ideen?

Lasst uns bitte nochmal schauen, ob es wirklich gar keinen Weg gibt. Für uns hängt schlicht der saubere Workflow davon ab.

**Comment by wrkb** [comment]
Seiten-Editor: Feld "Untertitel" umbenennen in Abhängigkeit von https://github.com/RRZE-Webteam/FAU-Theme/issues/146

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/5960362/194b1050-a7d5-11e4-9be1-49d1799fead6.JPG)

**Comment by wrkb** [comment]
Die Sidebar wird sich ja mittelfristig noch ändern, aber bis dahin können wir noch einige Begriffe anpassen, um es den Autoren leichter zu machen:
Alt: Titel darüber
Neu: Titel für Textfeld
Alt: Text darüber
Neu: Text
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/5960509/3ed03f5c-a7d6-11e4-8b56-c8ad30cc7fc7.JPG)


Alt: Titel darunter
Neu: Titel für Text
Alt: Text darunter
Neu: Text
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/5960488/0f9e6894-a7d6-11e4-8e8b-41c7bb135001.JPG)

**Comment by xwolfde** [comment]
Liefer mal Beschreibungen wofür die Felder notwendig sein sollen.

Ansonsten: Dieser Issue ist Murks. Wenn du Notizen für deine Schulung machen willst, mach das bitte woanders. Issues betreffen konkrete Umsetzungen für einzelne Punkte. Dieser Issue ist nun ein Sammelsurium an allen möglichen und von Brainstorming. Damit kann ich nichts anfangen.

**Comment by wrkb** [comment]
Issues verschoben in Gitlab.
