### ISSUE TITLE
Hauptmenü - Unterpunkte ausklappbar geplant?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#134]
Auf dem Testserver ist da so ein Pfeil... --> beim letzten Punkt "Testportal". Ist das Absicht/Feature für die Fakultäten?
Wir wollen ja bewusst keine Unternavigation.
@danielkestler

![testport](https://cloud.githubusercontent.com/assets/9445370/5917654/8f299aec-a61f-11e4-937e-047d8f2c18ee.jpg)

**Comment by xwolfde** [comment]
Das liegt daran, daß ich da zum Testen einen Unterpunkt eingetragen hab ;) 
ich wollte sehen, was in einen solchen Fall passiert.
