### ISSUE TITLE
Bild und Bildunterschriften in Beiträgen und auf Startseite laufen nicht richtig

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#138]
@danielkestler

Ich habe gerade einen Beitrag in FAU aktuell eingestellt. Als Artikelbild ein Portrait, als jpg aus einem tiff erzeugt, Originalbreite 950px ca.. Die Anzeige auf der Startseite passt nicht:

![unbenannt0](https://cloud.githubusercontent.com/assets/9445370/5921993/53aa7332-a648-11e4-84dd-61c98fe60e61.JPG)

# Gleichzeitig
passt die Darstellung des Artikelbildes auf der Leseansicht nicht:
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/5922019/9341603c-a648-11e4-9b65-17718e79c4a3.JPG)

# Dazu
kommen Bildunterschriften, die teils komisch umbrechen - linkszentrierter Text und die letzten Zeichen aber rechtszentriert (scheinbar) - beim zweiten Bild von Prof. Neurath im Screen oben und im nächsten Screen. Wichtig Tritt nicht bei allen Bildern/Beiträgen auf!

Ein zweiter Fall (durch Zufall entdeckt) ist zu sehen in https://www.fau.de/2013/10/18/news/wissenschaft/was-den-darm-am-leben-haelt-fau-forscher-entschluesseln-selbstmordprogramm-in-der-darmschleimhaut/

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/5921438/3cea9fea-a644-11e4-907b-82b2cdb37a66.JPG)

**Comment by wrkb** [comment]
P.S. Ich muss das Artikelbild noch mal neu hochladen in einer unkritischen Größe und hoffe, das hilft. Das alte lasse ich mal in der Datenbank - Suchwort becker müsste beide Varianten finden.

**Comment by xwolfde** [comment]
auf der testinstanz existiert nun eine lösung für beide probleme.
Bei Artikeln kann eine eigene optionale Bildunterschrift gesetzt werden für das beitragsbild. Für den Slider kann ein alternatives Bild ausgewählt werden, welches nicht das Beitragsbild ist. Und auf der Startseit ist das problem mit der Größe Behoben.

**Comment by wrkb** [comment]
Testen wir am Montag. Danke schomma!
