### ISSUE TITLE
Suchergebnisseite - Länge der Auszüge geringer

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#139]
...ist auch für die neue Suchseite relevant, wenn man sich dort für eine Ergebniskategorie entscheidet. Dann müsste wahrscheinlich so etwas wie die bisherige Suchergebnisseite kommen - und dort sind mir die Textauszüge etwas zu ausführlich. Ich fände etwas um die 5 Zeilen gut. Wieviele Zeichen das sind, müsste man testen - vielleicht kann das gleich derjenige machen, der es auch umsetzt, ich habe keinen Vergleich.

![suche_nachrichten_ _fau de_-_2015-01-27_17 23 38](https://cloud.githubusercontent.com/assets/9445370/5922155/b37e9cc4-a649-11e4-8391-8421b09efe7c.png)

@danielkestler

**Comment by xwolfde** [comment]
Ein Limit ist bereits enthalten, der auf den Auszug basiert. Bei diesen alten Blogartikel gibt es aber wohl kein Auszug, weswegen es da wohl zu einem Problem kommt. ich nehms in meine Todo.

**Comment by xwolfde** [comment]
Spezifische Suchergebnisseiten waren noch nicht mit
fau_custom_excerpt(get_the_ID(),$options['default_search_excerpt_length']);
versehen

**Comment by xwolfde** [comment]
Drin, aber ich kann noch nicht testen.
Plugin CMS-Search fehlt im GitHub @rvdforst !
Und es gibt keine Ausweichbehandlung wenn das Plugin fehlt. :(

**Comment by wrkb** [comment]
solved?
