### ISSUE TITLE
Responsive: Bricht für die Smartphone-Größe alles korrekt um?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#141]
Fiel gerade auf: Die Darstellung nach dem letzten breaking point stimmt nicht, der Text bricht nicht korrekt um. Test mit Smartphone (Android, Firefox) bestätigt das.
@danielkestler

**Comment by danielkestler** [comment]
Ist das in der neusten Version (in 1.2) immernoch so?

**Comment by wrkb** [comment]
Ja. Exemplarische Screens (Chrome), aber auch via Smartphone nachvollziehbar:

![studium-umbruch](https://cloud.githubusercontent.com/assets/9445370/5955096/79897ffa-a79f-11e4-9300-a369d1542289.png)
![start-umbruch1](https://cloud.githubusercontent.com/assets/9445370/5955098/7c76f850-a79f-11e4-874f-8f9a5eb84918.png)

**Comment by xwolfde** [comment]
Ich bin mit dem Menü noch nicht glücklich.
Auf der Startseite ist bei einem Handy nichts vom Inhalt zu sehen wegen den zweiten Menü (Quicklink-Bereich unter Slider). Wenn man dann ein menü über Hamburger aufklappt ist die Bedienung ebenfalls gewöhnungsbedüftig.
![startseite-20150209-mobile1](https://cloud.githubusercontent.com/assets/1070669/6126226/a77b59e6-b11e-11e4-8aee-e14ff784cd91.png)
![startseite-20150209-mobile2](https://cloud.githubusercontent.com/assets/1070669/6126230/aa53a948-b11e-11e4-8ff1-4e8933463e1b.png)

**Comment by wrkb** [comment]
Über den blauen Bereich müssen wir mal sprechen. Das Problem ist da (2 Menüs) aber gleichzeitig ist der blaue Bereich zumindest auf fau.de ja auch gewollt als sichtbarer Inhalt und hat Mehrwert (die Startseite ist nicht nur für Studis). Optisch ist es halt blöd und man sieht nicht, noch kommt - wie du schon sagst. Da wir nicht wissen, was technisch machbar ist, müssen wir uns zusammensetzen für Vorschläge. Mal rüberkommen?

**Comment by wrkb** [comment]
Grade noch gesehen und das darf als Blocker gelten: Auf den Inhaltsseiten ist die Navi nicht mehr zu sehen (die linke). (Screen vom PC, auf dem Smartphone ist das Kontextmenü ganz unten netterweise.). Getestet mit Firefox und Chrome.
(Müssen wir Stockbrowser noch berücksichtigen, der ja seit einigen Wochen unsicher ist und von Google nicht mehr zur Nutzung empfohlen wird?).

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6326046/e7c10468-bb4d-11e4-8cd0-839deea4300d.JPG)

@danielkestler

**Comment by wrkb** [comment]
Inhaltsmenüproblem ist nun auch im Basecamp und eilt - Daniel weiß Bescheid.

**Comment by xwolfde** [comment]
Ok, Menü ist sichtbar unter Firefox4 auf Android.
Trotzdem bin ich nicht glücklich:
1. ein aufgeklapptes Menü (Klick auf Hamburger-Icon, dnach Klick auf Pfeil nach unten) lässt sich nicht mehr zuklappen indem man auf den Pfeil nach unten klickt. Dieser Pfeil sollte dabei übrigens im aufgeklappten Zustand auch eher nach oben oder links zeigen. Klickt man auf den Pfeil, wird dei Seite geladen, die hinter dem Menuicon steckt. Um es zuzuklappen ist nur ein Umweg über Click auf Hamburgermenu möglich.
2. Die Seitennavi ist zwar jetzt sichtbar, ist aber immer oben on top und nicht zuklappbar (und damit nicht aufklappbar). Es bleibt dabei, daß nur das Hamburgermenu das hauptmenu steuert. Andere Menüs in der Seite werden nicht zugeklappt, der Inhalt daher nach unten verscho
![screenshot_ff-android-z3compact-2015-03-03-14-38-37](https://cloud.githubusercontent.com/assets/1070669/6463741/482c222a-c1b5-11e4-9244-deeff8b8d484.png)
![screenshot_ff-android-z3compact-2015-03-03-14-38-51](https://cloud.githubusercontent.com/assets/1070669/6463740/482b43d2-c1b5-11e4-8e70-69e351eaba50.png)

ben.

**Comment by wrkb** [comment]
Stimmt alles. Müssen wir auch mit Chrome nochmal testen, der ist vorinstalliert bei neueren Telefonen. Hat den wer drauf?

**Comment by xwolfde** [comment]
Es gibt ein Bug bei Samsung Galaxy S3 auf der Startseite: Hamburger Symbol kommt erst nach nochmaligen Laden.

**Comment by wrkb** [comment]
...welcher Browser? Stockbrowser oder Chrome?
(Daneben sind die Samsung-Oberflächen ein einziger Bug - zählt das also? :see_no_evil: )

**Comment by xwolfde** [comment]
Standardbrowser auf dem Samsung. Astrid versucht gerade vom Gerät aus hochzuladen ;P

**Comment by xwolfde** [comment]
Passiert hier noch was?

**Comment by wrkb** [comment]
Das habe ich vor 7 Tagen ja schon gefragt - s.o. :) Ich habe nichts weiter auf dem Schirm in der Richtung und bräuchte noch mal eine Einschätzung von euch. Bzw. einen Auftrag (du hast keinen formuliert nach deiner Kritik oben), den ich dann der Agentur gebe. Ruf am besten kurz durch, dann geht es auch ganz fix weiter :racehorse:

**Comment by xwolfde** [comment]
Ich nehme diese Rückmeldung als Beleg dafür, daß wir uns besser selbst drum kümmern.

**Comment by wrkb** [comment]
Beleg wofür? Dass wir nicht irgendwas ändern, ohne Euren Input mit zur Agentur zu nehmen? Bevor wir dann was bekommen, was uns nicht gefällt? Korrekt. Dieser Input fehlt bislang einfach (z.B. an dieser Stelle). Siehe auch Frage 15 Tage zuvor...

**Comment by xwolfde** [comment]
ich warte noch bis Ende der Woche, ob es bzgl. der hier und im Basecamp angefragten Probleme einen Lösungsvorschlag oder einen sachlichen Feedback gibt. Falls nicht, wird es bei den Fakultäten eine RRZE-Lösung geben.

**Comment by wrkb** [comment]
Wenn ich nur wüsste, was genau du meinst? Sollst alles haben, aber ich werde aus deinen Antworten nicht schlau! Willst du...
a) einen Vorschlag von der Agentur?
b) sollen wir einen Vorschlag machen?

Im Basecamp sehe ich keine offenen Anfragen von dir zum Thema Mobilseite. Dafür aber Fragen von Daniel an _dich_, die unbeantwortet sind...
Bitte schick mir eine Mail oder ruf mich an - wo genau fehlt dir etwas?

@wrcg @danielkestler

**Comment by xwolfde** [comment]
Ab https://github.com/RRZE-Webteam/FAU-Theme/issues/141#issuecomment-76948808 sehe ich nur Problemmeldungen von mir.

**Comment by wrkb** [comment]
...du hast sie niemandem zugewiesen, die Frage. Meine obige Frage, wie wir mit dem blauen Bereich verfahren, ist auch unbeantwortet, denn ich habe auch keine Patentlösung parat und wollte deinen Rat.
Erneut der Hinweis, dass Telefonate effektiver sind, als Github.

**Comment by xwolfde** [comment]
Werden wir im Zuge der Entwicklung eines Fakultätstemplates nochmal durchdenken. Bis dahin wird das nach hinten geschoben.

**Comment by xwolfde** [comment]
Erste Beta im Test.  Scheint zu klappen, ein eiegner Case wird aufgemacht für Schönheitskorrekturen.
