### ISSUE TITLE
Suchergebnisse: Veranstaltungen ohne Datum, Datumsangabe bitte ohne "Meldung vom"...

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#142]
Veranstaltungen werden in den Suchergebnissen mit dem (eigentlich immer abweichenden) Erstellungsdatum angezeigt, was natürlich sehr irreführend ist. Das Datum soll bitte ersatzlos weg aus den Ergebnissen. Nur Meldungen brauchen ein Datum.

Der Text "Meldung vom" vor dem Erstellungsdatum bei Beiträgen ist generell überflüssig, der Text muss nur dekodiert werden und blockiert den Weg zur eigentlichen Info - dem Datum.

Danke, Gruß, Karsten

**Comment by wrkb** [comment]
![unbenannt3](https://cloud.githubusercontent.com/assets/9445370/6168183/4ba2c874-b2c3-11e4-8cdb-cb9d3baf9c70.JPG)

Leider sehr irritierend, daher Prio1-Label...

**Comment by xwolfde** [comment]
Ich frag mich ja bzgl. der Zeit ob du gerade mit dem Laptop unterwegs bist, oder einen Termin verpasst :P

**Comment by wrkb** [comment]
trust me!

**Comment by xwolfde** [comment]
Hm, das ist ein Problem, weil diese Eventhinweise kein eigener PostType sind, sondern eben Meldungen mit Eigenschaften... Ein zukünftiges Datum dort einzustellen wäre für den User auch verwirrend,w eil der text ja an dem Datum geschrieben wurde.

**Comment by xwolfde** [comment]
Sollen solche Meldungem, die keine Meldungen sind, sondern veranstaltungshinweise, wie Veranstaltungen gezeigt werden?

Und ist das ein Fehler, dass ihr das doppelt eingetragen habt?:
![veranstaltungshinweis-doppelt](https://cloud.githubusercontent.com/assets/1070669/6189468/28ea15b6-b39b-11e4-9e38-7da6e1156202.png)

**Comment by xwolfde** [comment]
HA! Toller Scherz. Hab umsonst gesucht. Ihr bedient es nur falsch. Danach hab ich zuletzt geschaut... 
Ihr habt da bei dem Termin kein tTrmineintrag (z.B. Top Event mit den extra Attributen dafür) und auch kein Event-Eintrag gemacht, sondern habt einfach in der ersten Zeile einer normalen Meldung einen fett geschriebenen Text mit ein Datum geschrieben. Wie bitteschön soll denn das erkannt werden!?

Verwendet für Veranstaltungen auch bitte Events oder eben Top-Event, aber nicht Beiträge!

**Comment by wrkb** [comment]
Ähm. Mea culpa. Da haben wir dicke was durcheinander gebracht. Wir können das Problem also tatsächlich selbst lösen.
