### ISSUE TITLE
Wasserzeichen FAU aktuell falsch geschrieben

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#143]
..."aktuell" bitte klein schreiben. Danke!

![fau-aktuell](https://cloud.githubusercontent.com/assets/9445370/5955751/78033a2a-a7a6-11e4-965f-21d0af505e82.jpg)

**Comment by wrkb** [comment]
@danielkestler

**Comment by xwolfde** [comment]
Im beta gefixt. 
Aner da die hardcodiert Form für die Fakultäten nicht gut sein wird, muss ich da ran und es optional einstellbar machen. Es betrifft dann auch andere Seiten mit fest codierten Angaben an der Stelle.

**Comment by xwolfde** [comment]
nun konfigurierbar
