### ISSUE TITLE
Stand Rich Text Editor - Welche Sonderzeichen könnten wir "einbauen/umsetzen"?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#144]
...altes Thema, aber ich kenne den absolut letzten Stand nicht.
Wir wollen gewisse Sonderzeichen einsetzen und schulen und den Leuten nicht Tastekombis à la Alt+0132 zumuten. Es gab die Idee der automatisierten Umsetzung für Anführung und Gedankenstrich.
Wo stehen wir da?
Den Gedankenstrich gibt es nur als Enhancement später: https://github.com/RRZE-Webteam/FAU-Theme/issues/66
Die Anführung steht wohl nirgends.

Es wäre natürlich schön, das vor der Schulung zu haben, aber das ist nicht realistisch, oder? Wir müssen es nur wissen, um entsprechend darauf eingehen zu können.

(Wir werden sowieso Update-Schulungen machen müssen mit neuen Funktionen oder für spezielle Zwecke.)

**Comment by xwolfde** [comment]
UTF kann ein paar Tausend Zeichen darstellen, inklusive Smileys.

Welche Sonderzeichen genau braucht ihr? Bitte aufführen.

**Comment by wrkb** [comment]
...das Issue müsste in Gitlab, korrekt? Es geht ums Backend.

Wir brauchen eine einfache Eingabemöglichkeit für

Alt + 0132 - Anführung ein: „
Alt + 147 - Anführung aus: “
Alt + 0150 - Gedankenstrich: –

(Die Darstellung im Frontend klappt natürlich schon.)

**Comment by xwolfde** [comment]
Die werden alle von Wordpress bereits im visuellen Editor angeboten :) 
Schau mal im Editor und Klick auf das Omega:

![sonderzeichen-nutzen1](https://cloud.githubusercontent.com/assets/1070669/6246947/a6217a7a-b76e-11e4-88bc-8f85c9dc258c.png)

![sonderzeichen-nutzen2](https://cloud.githubusercontent.com/assets/1070669/6246950/ac3767ee-b76e-11e4-80a0-15c446d256f0.png)
