### ISSUE TITLE
Das Grid läuft nicht mehr sauber (SASS-Umstellung?)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#145]
https://www.fau.de/universitaet/stiften-und-foerdern/deutschlandstipendium-stiften/unsere-foerderer/ - da gibt es Lücken.

@danielkestler Schaust du mal?

**Comment by danielkestler** [comment]
Ah, das liegt daran, dass die Bildunterschriften von der Länge nicht mehr beschränkt sind. Ich schau mal, wie wir das noch angleichen können.

**Comment by xwolfde** [comment]
Ist mit dem letzten Update nicht behoben.

**Comment by wrkb** [comment]
gibt es hier Neuigkeiten?

**Comment by xwolfde** [comment]
Du meinst den @danielkestler mit der Frage nach Neuigkeiten, oder?

**Comment by xwolfde** [comment]
Jetzt hat sich was getan. Danke fürs nichtmelden.
Jetzt sind die Boxen gleich hoch.
Was aber wieder zu dem alten Bug führte, den wir bei den Galeriebildern schonmal hatten.
![bug-fehlerhafte-hoehen-matrix](https://cloud.githubusercontent.com/assets/1070669/6580627/5090ab8c-c752-11e4-85e9-cb1a775c7dc9.jpg)

**Comment by wrkb** [comment]
Das hatten wir nicht gesehen, ich glaube, die Gallerie existiert in der Hummel nicht. Aber wahrscheinlich habe ich es bei der anderen Testgalerie schlicht übersehen.

(Was hätte wer wie melden sollen? Im Basecamp gab es ja ein Issue samt Kommunikation).

**Comment by xwolfde** [comment]
Das wäre dein Job gewesen.
Alles weiter nicht öffentlich.

**Comment by wrkb** [comment]
Wird ein Issue für mr? Oder bei euch?

**Comment by xwolfde** [comment]
Problem nur ungenügend behoben durch feste Erhöhung der imageHeight auf 120 via JS:
Löst nur via JS, erkennt nicht, daß Grids umbrechen bei kleinen AUflösungen und dort diese Höhen dann zu hoch sin dund White Space erzeugen
![gridproblem2](https://cloud.githubusercontent.com/assets/1070669/6784736/c73bf136-d181-11e4-92b9-c1ea8244c5e3.png)

**Comment by xwolfde** [comment]
Redakteur muss sinnvolle Captiontexte eingeben.
