### ISSUE TITLE
Untertitel-Feld

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#146]
Wozu haben wir dieses Feld? Mir ist das was entgangen. Ist quasi eine feste h2? Die soll auch vergeben werden, richtig? Läuft das Layout mit Bildern und Boxen auch ohne richtig? Sonst kann sie ein Pflichtfeld werden, oder?
Ich frage auch, weil das Feld die Schulung etwas komplizierter macht, aber wenn es Sinn hat, dann ist das schon okay.

Wie wird danach weiter strukturiert? Mit h3 und h2 wieder, wenn ein neuer Abschnitt kommt - also wie gewohnt?

Den Namen müssten wir noch ändern, je nachdem, wie die Funktion definiert ist in eurer Antwort, Wolfgang. Ist Seitenüberschrift passend?

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/5960382/3405dc86-a7d5-11e4-975b-6d59977fd6bd.JPG)

**Comment by wrkb** [comment]
@wrcg

**Comment by xwolfde** [comment]
Warum fragst du mich das alles? Das Feld war schon drin und ihr hattet es auch bereits befüllt. Ich habs nur aus ACF in eine Metabox getan. 
Der Name erscheint mir der einzig sinnvolle und richtig.

Wenn das Feld belegt ist, wird eine zusätzliche fest definierte h2 damit erstellt.
Dies ist sinnvoll bei einigen Seiten un dganz offensichtlich wurde es gezielt designed.. Mach es und du siehst es.

Die Fragen wie es aussieht und wie wenn es nicht belegt ist, kannst du doch selbst ersehen in dem du dir Testseiten erstellst. Warum soll ich dir das nachtragen an Infos?
