### ISSUE TITLE
Neue  Version von Seiten

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#149]
bei der Verwendung einer neuen Version beim Seiten bearbeiten, wird beim anschließenden Veröffentlichen das Beitragsbild erneut in der Mediendatenbank gespeichert. Wir produzieren damit also eine Menge doppelter Bilder/Medien. Das ist eigentlich nicht gewollt.
D.h. bitte das erneute Speichern der Beitragsbilder bei "Neue" Version" abschalten.

**Comment by xwolfde** [comment]
verschoben nach https://github.com/RRZE-Webteam/cms-workflow/issues/29
