### ISSUE TITLE
Suche: Breadcrumb zeigt Herkunft des Suchergebnisses an

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#151]
...Gestaltungsvorschlag liegt der Webredaktion vor. Technische Umsetzung von RRZE.

**Comment by xwolfde** [comment]
Nach Rücksprache mit Rolf: Wir müssen erstmal die Breadcrumb neu coden. Das verwendete Plugin Breadcrumb XT macht Müll und ist eingentlich völliger Humbug.
