### ISSUE TITLE
Suche: Veröffentliche Personen durchsuchen und ausgeben (separate Kategorie bei Ausgabe)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#152]

**Comment by xwolfde** [comment]
Bitte hier:
https://github.com/RRZE-Webteam/fau-person/issues
nochmal genauer beschreiben was damit gemeint war.
Ich verstehe es gerade nicht so und Updates zu der Personenverwaltung gibt es nur noch mit dem neuen Plugin.
