### ISSUE TITLE
zusätzlicher Link auf den Seiten der Studiengänge

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#154]
Die Studiengänge sind über die Suche auffindbar (und das ist auch so gewollt). Allerdings erscheint dann nur der "blanke" Studiengang ohne Navigation etc. Rolf, könntest du auf eine Studiengangsauszugsseite (z.B. https://www.fau.de/studiengang/biologie-bsc/) oben rechts noch einen Link "Alle Studiengänge" (https://www.fau.de/studium/vor-dem-studium/studiengaenge/alle-studiengaenge/) einfügen. Wir sind uns bewusst, dass dies dann auch auf den Studiengängen angezeigt wird, die man über die Suchmaske auswählt, hoffen aber, dass es nicht störend ist.

**Comment by rvdforst** [comment]
Ist schon erledigt mittels einem Sidebar (Studiengang-Sidebar). Ich habe mir erlaubt, ein Text-Widget mit wichtige Links hinzuzufügen ;-)

**Comment by wrkb** [comment]
Danke Rolf. Aber ich fürchte, das hat neue Nachteile. Die Seite "springt" nun gezwungenermaßen, wenn man runterscrollt, und einen Studiengang auswählt. Da der Kopfteil stehen bleibt, muss man auch erstmal gucken, was gerade passiert ist und ob sich etwas geändert hat. Und man muss zum gewünschten Inhalt scrollen/den bekannten im oberen Teil "wegscrollen".

Ich weiß nicht, ob es helfen würde, den Kopfteil beim Anzeigen eines Studiengangs auszublenden. Dann würde die Seite auch "springen", aber wenigstens müsste man nicht scrollen.

Ich brauche andere Meinungen. @xwolfde @wrcg ?

**Comment by wrcg** [comment]
deine Anmerkung verstehe ich nicht, Karsten. 
Es geht ja nur um Seiten, wie z.B.  https://www.fau.de/studiengang/biologie-bsc/. Da passt die Sidebar. 
@ Rolf: wo können wir die Einträge der Sidebar selbst ändern?

**Comment by rvdforst** [comment]
@xwolf: Design > Widgets > Studiengang-Sidebar

**Comment by xwolfde** [comment]
Offtopic:
Boah, was sieht denn die Seite hässlich aus. Die Tabellen machen ja dauernd zickzack in der Breite der ersten Spalte. Geht das nicht besser zu gestalten?

Mir ists egal: Wird für Fakultäten nicht benötigt :P 
Bessere Möglichkeiten der Tabellengestaltung schau ich mir aber mal an.

**Comment by wrkb** [comment]
Ich hau hier mal noch den Aspekt "Reset der Filter" mit rein. Ich weiß nicht, ob der gewünschte Link das schon mit erfüllt. Falls nicht, müsste der Reset ein eigenes Issue werden, aber nicht dringend. Aktuell müssen wir uns den Stand nochmal anschauen mit dem Link, ich seh grad nicht durch. Wir melden uns.

**Comment by wrkb** [comment]
Funktioniert für https://www.fau.de/studiengang/business-management-mba-mba/ - closed.
