### ISSUE TITLE
Tags bei Beiträgen mit geänderter Nummerierung (-6) - woher kommt's

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#156]
Ursprünglich haben wir mal das Tag "techfak" an Beiträgen vergeben, jetzt lautet es "techfak-3". Wir haben es definitv nicht zweimal geändert o.ä. Andere Tags enden teils auf -6.
Woher kann das kommen und - am wichtigsten - sind die Tags zuverlässig genug zum Rausgeben von dauerhaften Feed-Links?

Mir fällt nur der Import aus dem Blogsystem als Grund ein, auch wenn ich nicht verstehe, warum dann -6 hinten steht (Schlagwort 5mal überschrieben?).

Habt ihr Infos?

Danke und Gruß

Karsten

**Comment by xwolfde** [comment]
Importierte Tags aus dem Blogsystem führten dazu, das der Zähler hochtickt.
