### ISSUE TITLE
Datei ersetzen schlägt fehl.

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#157]
Das ist tatsächlich dringend, denn wir können keine wichtigen Dokumente fürs neue Semester hochladen. Ohne die Ersetzen-Funktion (mit einem Workaround) würden wir riskieren, veraltete Links zu haben.

Schaut ihr bitte mal? Danke!
Fehlermeldung:
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6057908/9e88a5fa-ad22-11e4-9016-33f2dd3dd016.JPG)

**Comment by wrkb** [comment]
@wrcg @xwolfde

**Comment by wrkb** [comment]
Gibt es hier Neuigkeiten?

**Comment by xwolfde** [comment]
Ist Teil des CMS-Workflow-Plugins.
Wenn es ne Kleinigkeit ist, kann Rolf es nebenher machen; Ansonsten muss es warten bis wir dazu Zeit haben. Prorität haben derzeit andere Teilprojekte.

**Comment by wrkb** [comment]
Ist leider keine Kleinigkeit. Wir wissen, dass die Funktion von einem Plugin übernommen wurde usw., aber sie ist zentral. Wir können nicht das Studienangebot der FAU veraltet online lassen - die Webseiten haben eine hohe Verbindlichkeit usw.
Wenn wir es nicht ersetzen können, müssen wir alle Plätze suche, wo es verlinkt sein könnte und die Links manuell ändern. Also wir müssten arbeiten, als hätten wir kein CMS ;) Das nur als Hinweis auf die Bedeutung der Funktion, ich setze das Label "Dringend" wirklich nur bewusst und selten...

**Comment by wrkb** [comment]
Weiter geht es hier: https://github.com/RRZE-Webteam/cms-workflow/issues/24

**Comment by rvdforst** [comment]
Nein, das ist nicht Teil des WF-Plugins. Das Enable-Media-Replace-Plugin hat diese Ersetzen-Funktion. Ich habe die Berechtigungen des Medienverzeichnis wieder festgesetzt. Somit sollte es jetzt funktionieren.

**Comment by wrcg** [comment]
nein, es funktioniert damit leider auch nicht. 
Allerdings war das Problem ja nur bei einer einzigen Datei und diese habe ich jetzt gelöscht und komplett neu hochgeladen. So stimmt zwar die URL zu der Datei jetzt nicht mehr, aber damit müssen wir jetzt halt leben. 
Alle anderen Dokumente, die seit letzter Woche getauscht wurden, hatten dieses Problem nicht
Wenn das Problem wieder auftaucht, melden wir uns wieder :-)

**Comment by xwolfde** [comment]
"nein, es funktioniert damit leider auch nicht. ....Wenn das Problem wieder auftaucht"

Äh?  Wie jetzt? Ist das Problem behoben oder nicht?

**Comment by wrkb** [comment]
Das Problem ist nicht behoben, Cathrin hat nur pragmatisch ge-workaroundet und jetzt können wir es nicht mehr nachvollziehen...

**Comment by xwolfde** [comment]
Für euch führe ich noch ein Label ein: "Mach dem W. seine Haare grau!"

**Comment by rvdforst** [comment]
...und dem R.     ;-)
