### ISSUE TITLE
Möglich? Weniger Mailbenachrichtigungen bei "Neue Version"

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#159]
Wenn man eine neue Version anlegt und veröffentlich, erhält man gleich drei E-Mails (weil wohl drei Vorgänge dranhängen). Das lässt sich nicht verschlanken, oder? Nur eine Frage, ich ahne die Antwort schon :)

![d](https://cloud.githubusercontent.com/assets/9445370/6108712/8d3afef0-b075-11e4-8734-0a44db2b2e6e.jpg)

**Comment by xwolfde** [comment]
Ja, fände ich wäre ne sinnvolle Sache. Teil des CMS-Workflow-Plugins 
https://github.com/RRZE-Webteam/cms-workflow 
(bitte ggf. dort weitere Issues eintragen)

**Comment by xwolfde** [comment]
verschoben
