### ISSUE TITLE
Personen: Wert des Felds "Abschluss" bitte in Klammern ausgeben

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#160]
Also statt

Hans Wunderlich Dipl. Sozw.

wollen wir

Hans Wunderlich (Dipl. Sozw.)

Sieht sonst doof aus...

**Comment by xwolfde** [comment]
Bitte liefere uns alle Ausschreibungen (hier: "Sozialwissenschaft) der abgekürzten Titel. Die brauchen wir für das Abbrevation.

**Comment by wrkb** [comment]
Du weißt, dass ich das nicht kann. ;)
Also ist das nicht realistisch machbar - meinst du das?

**Comment by xwolfde** [comment]
Doch, das könnt ihr. :) 
Wir brauchen die vollständige Ausschreibung aller Abkürzungen um die Barrierefreiheit zu halten. Das finden der korrekten Langform ist redaktionelle Tätigkeit.

**Comment by wrkb** [comment]
Äh, ja...
Wenn du eine umfassende Liste kennst, schick sie uns gern. Dann machen wir das Ticket nochmal auf. Ich wüsste nicht, wer so was aufgelistet haben könnte.

Ansonsten ist das ein nicht zu leistender Aufwand, wir arbeiten mit händischen Klammern, Issue closed.

**Comment by xwolfde** [comment]
Nein.

**Comment by wrkb** [comment]
Erbitte genauere Definition der letzten Antwort. Habe Schwierigkeiten beim Dekodieren.

**Comment by xwolfde** [comment]
Wird im FAU-Visitenkarten Plugin von uns richtig umgesetzt.
