### ISSUE TITLE
Probleme Umlautbehandlung deutsche und englische Site 

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#163]
Die Shortcodes/Slugs in der deutschen und englischen Site sind unnötigerweise verschieden und das bringt uns Probleme beim Übersetzen - zum Beispiel bei eingefügten Personenvisitenkarten.

Die deutsche Site macht aus einem ö im Slug oe, die englische ein o. Aus ß wird s... usw.

Lässt sich das vereinheitlichen? Sonst wird das Synchronisieren von Seiten mit eigentlich gleich lautendend angelegten Elementen noch umständlicher...

**Comment by xwolfde** [comment]
Nein. Ist so.

**Comment by wrkb** [comment]
Es ist also nicht möglich, die Sprachebehandlung nach der deutschen Variante zu erzwingen, jenseits der im Theme hinterlegten englischen Übersetzungen? Siehe hier:
http://www.perun.net/2013/04/17/wordpress-3-6-umlaute-im-titel-ohne-plugin-entschaerfen/

**Comment by xwolfde** [comment]
Dann lass Cathrin das mal machen. Ich sehe dafür aber keine Notwendigkeit, weil man Slugs eh nicht nach aussen hin nutzen soll. Bei der Einbindung von Menus in Portalseiten hab ich die manuelle Eingabe von Slugs ebenfalls schon weggeworfen, wiel die fehleranfällig ist.
Das Problem mit den Personenvisitenkarten wird durch ein von uns entwickeltens neues Plugin erledigt werden.

**Comment by wrkb** [comment]
Beträfe auch Synoyme z.B. Da könnten wir zwar auch ohne Umlaute arbeiten als Workaround, aber wenn sich eine einfache Lösung findet...
