### ISSUE TITLE
Skalierung Bild (Thumbnail) in Beitragsvorschau und Startseite

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#166]
wie besprochen:
Für die Beitragsübersicht (FAU aktuell: http://test4.wordpress.webhummel.rrze.uni-erlangen.de/category/news/) und für die News auf der Startseite (http://test4.wordpress.webhummel.rrze.uni-erlangen.de/) brauchen wir eine Lösung für Hochformate.

Das maximale Format bleibt 3:2 (300x200px).
Das Passepartout soll wieder her (es lief schon mal) für Hochformate.
Bilder werden nicht gecroppt.
Bilder werden proportional skaliert und zwar mit _relativen_ Angaben (besprochen mit Wolfgang).
Umgangssprachlich: Die längste Seite eines Bildes muss skaliert werden.

Heißt: 

Sehr hohe Hochformate (die haben wir oft) werden dann in 200px Höhe angezeigt (relativ) mit weißem Passepartout drumherum.
Aktuelles Beispiel aus der Testsite, wo das Passepartout fehlt: ![unbenannt]
(https://cloud.githubusercontent.com/assets/9445370/6166486/06f93d96-b2b1-11e4-9323-878c85d7f19f.JPG)
.
.
.

Sehr flache und breite Querformate (z.B. die Bilder aus den Themen aus Headerbild der Startseite) werden mit Breite 300px angezeigt, ohne Passepartout. Das funktioniert schon und soll so bleiben. 

Aktuelles Beispiel: 
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6166767/85571864-b2b3-11e4-9bdb-cde231583e9b.JPG)

@wrcg

**Comment by xwolfde** [comment]
fixed im nächsten update. auf test4 aktiv
