### ISSUE TITLE
Für Beiträge (nicht: Seiten) h2-Titel über Bild laufen lassen

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#167]
...hier hatten wir nicht klar getrennt in der Vergangenheit. Ist optisch eigentlich nicht nur ein enhancement, aber als Label wähle ich trotzdem selbiges.

Der ht-Text soll über das Bild laufen in Beiträgen. Das erste obere Bild rutscht also tiefer.

Auf Seiten geht das nicht, da wir teils so kurze Seitentitel haben, dass dann ein unschöner Weißraum über dem Bild wäre. Bei Beiträgen haben wir nie so kurze Titel (oder können ggf. nachbessern).

Screenshot ist schwierig - könnte ich nur montieren. Soll ich?

**Comment by xwolfde** [comment]
Bedienerirrtum: Es gibt da keine zweite Überschrift bei Beiträgen. Das könnten wir noch machen (oder wieder einbauen, wir hatten es mal glaub ich); Die eigentliche Beitragsüberschrift ist im blauen Bereich.
Das was du also Übershcrift meinst kann also nur Teil des normalen Content sein.

**Comment by wrkb** [comment]
Schtimmt!
Dann äh hätten wir gern noch/wieder ein Feld h2 für Beiträge, dass dann entsprechend im CSS definiert wird und übers Bild in Beiträgen läuft.

Dankeschön :)

:+1:

**Comment by wrkb** [comment]
(Gibt's hier noch mehr Smileys?) :)

**Comment by xwolfde** [comment]
Ich hätte gern den Baseballschläger >;)

**Comment by xwolfde** [comment]
Werde das jetzt in der 1.4 einbauen. Diese Funktion des Untertitels wird vom Admin im Backend zentral ein/ausschaltbar sein.

**Comment by xwolfde** [comment]
done
