### ISSUE TITLE
"Neue Version" für Autoren und Redakteure

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#168]
Ich kann das Problem nicht genau formulieren, bitte stellt ggf. Fragen, dann liefere ich Details nach:
Ein Kollege ist Redakteur für seine Seite, hab aber in der schwarzen Admin-Leiste oben im Backend die Option "Neue Version" nicht.
Auch mein Test-Autor namens "autor" sieht diese Option nicht.

Wir brauchen sie aber. Im Workflow kann man das nicht einstellen. Glaube ich jedenfalls... 

@wrcg

**Comment by xwolfde** [comment]
verschoben ins workflow-plugin
