### ISSUE TITLE
Weiche für RW und Wiwi

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#169]
Liegt euch  die Definition von beiden Fakultäten für die spezielle "Weiche" vor? Liegt bei mir. Muss berücksichtigt werden.

**Comment by xwolfde** [comment]
???

**Comment by xwolfde** [comment]
Nein, es wird keine Sonderlösungen für einzelne Departments geben.

**Comment by wrkb** [comment]
Es geht nicht um ein Department. Es geht um die Pseudo-Fakultät. Letztendlich musst du es nicht mir erklären, sondern den beiden Kollegen, die keine Inhalte für die Seite haben und keine News. :)

**Comment by xwolfde** [comment]
Ich verstehe nicht, was du meinst und was dies mit dem FAU-Theme zu tun hat.
Wir werden auch keine Sonderlösung für RW machen.
