### ISSUE TITLE
Mediendatenbank: Filtern mit Ausschlussprinzip

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#17]
Sehr hilfreich, spätestens zur Konsolidierung der Inhalte wäre:

a) Suchen nach Inhalten OHNE jegliche(s)
Schlagwort
Medienkategorie
Dokumentenkategorie
--> Nachverschlagwortung/kategorisierung möglich.

b) Suchen nach Inhalten mit und Ausschließen einer Kategorie/eines Schlagwortes (alle PDF mit Master im Namen die NICHT in der Studiengangsdatenbank sind mit der Kategorie Studiengangsdatenbank)
--> bislang nicht möglich

**Comment by xwolfde** [comment]
moved to https://github.com/RRZE-Webteam/cms-workflow/issues/34
