### ISSUE TITLE
Bilderpool für Themes aus M

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#170]
@xwolfde @wrcg 

machen

**Comment by wrkb** [comment]
Fragen:
Sollen die Fakultäten die gleichen Bilder wie auf unserer Seite bekommen, wenn sinnvoll? Also die Studis bei der Studienberatung z.B. Wäre dann eine einheitliche Bildersprache und vor allem von uns auch einfacher zu leisten - dann hätten wir ruckzuck einen guten Pool zusammen. Mal eben andere Bilder zum gleichen Thema herzaubern ist sonst viel schwieriger.

Hier muss ich intern aber noch einmal nachfragen, ob das in Ordnung geht. Die Lizenz sollte es aber hergeben.

Der Pool wird trotzdem Grenzen haben, wir können nicht jedes mögilche Menü der Einrichtungen mitdenken. Ich würde mich hier auf die großen Themen beschränken, die wir selbst bedienen und auf das, was uns vielleicht noch einfällt, was jede Fakultät/jedes Department/jeder Lehrstuhl als Bild-Box haben könnte (Publikationen, Personenlisten, Forschungsberichte etc.).

Wie gehen wir mit Stockphotos um? Die dürfen FAU-weit genommen werden, glaube ich. Wenn sie nur im Theme auswählbar sind, haben wir kein Problem. Als Datei rumgeben muss ich ebenfalls intern nachfragen, die Wiederverwendung ist ja an die Lizenz gebunden und da müssen wir Aufklärung betreiben.

Sagt mal was dazu :)

@wrcg @xwolfde

Grüße

Karsten

**Comment by xwolfde** [comment]
Hatte ich schonmal in einem Meeting.
Grundlage: ALLES was in den Theme enthalten ist, MUSS unter einer freien Lizenz.
Also entweder GPL, Public Domain oder eine CC-Lizenz.

Wenn das nicht geht, kann das jeweilige Bild nicht in das Theme.

**Comment by wrkb** [comment]
Okay, dann müssen wir den Pool händisch überreichen und ich kann nichts fürs Theme beisteuern. Wir habe keine Bilder mit freien Lizenzen.
