### ISSUE TITLE
OpenGraph-Funktionen für Thumbnails der Artikel

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Theme#172]
OG-Compatibilität der Thumbnails muss eingebaut werden, damit es in Social Media schöner aussieht.
Ggf. in dem Zuge auch auf <picture> umstellen.

**Comment by wrkb** [comment]
Können wir im Zuge dessen auch die Bilder beeinflussen, die Facebook auswählt? Bisher geschieht das ja willkürlich... Wäre ganz wichtig, hast du auch mal als Teil des Problems erwähnt.

**Comment by xwolfde** [comment]
Genau darum geht es hier :)

**Comment by xwolfde** [comment]
Da wir Standard-Bildgrößen verwenden, die auch von den Plattformen für OG verwendet werden, müsste ein Standardplugin doch besser sein. Eine eigene Implementation im Theme lohnt sich nur, wenn man durch eigenen Bilddimensionen extra Hacks braucht, da man das Thumbnail nicht nutzen kann.
Daher: Todo: Geeignetes Plugin suchen & finden.
Für das Theme: wontfix. (erstmal)
