### ISSUE TITLE
ACF-Rückbau: SIdebar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Theme#173]
Felder der Sidebar die derzeit via ACF und ACF-Repeater gemacht werden in das Theme übernehmen.

Problem: Kontextlinks. Wie am besten umsetzen?
a) als Menu, welches man dann aus einer Selektliste wählt?
oder
b) als eigenständige Link-Type gemacht werden, zu dessen Anzeige man jeweils eine KAtegorie auswählt?

**Comment by xwolfde** [comment]
Darin enthalten: #124

**Comment by xwolfde** [comment]
Dairn enthalten: #97

**Comment by xwolfde** [comment]
geht noch nicht in die neue Version auf dem Livebetrieb rein. Das ist aufwendiger wegen der derzeit durch ACF nicht vorhandenen Linkverwaltung.

**Comment by xwolfde** [comment]
Muss getrennt werden in Pluginteil und Themeteil.
Im Plugin-Teil kommen die Kontextlinks.
Personenverlinkung verbleibt im Theme, genauso wie Text. Titel obnen und unten sind sinnfrei, wenn normales Texteingabefeld genutzt wird.

**Comment by xwolfde** [comment]
Irgendwie ist es doch sinnfrei extra Felder für "Titel" (oben und unten) zu haben, wenn darunter ein Textfeld zur Verfügung steht indem man über die Texteingabefunktionen ebenfalls Titel setzt!
Siehe Screenshot.
![sidebar-titel-ausserhalb-wpeditor](https://cloud.githubusercontent.com/assets/1070669/6594470/e76d1c18-c7e1-11e4-8d5d-35de086e318c.jpg)

Frage an @wrkb : Reicht es nicht auch die Titel in der Editoreingabe zu setzen?

**Comment by xwolfde** [comment]
Alternativ: Minimaler Editor, der die Absatzschriften nicht anbietet:
![sidebar-titel-ausserhalb-minimal-wpeditor](https://cloud.githubusercontent.com/assets/1070669/6594629/2dc20f74-c7e3-11e4-8278-a3e0c7521857.jpg)

**Comment by xwolfde** [comment]
Meine Tendenz: Ich mach die gesonderten Überschriften aus Abwärtscompatibilität noch optional ein/ausschaltbar drin; Per Default aber nur vollständige wpeditor() EIngaben für oben und unten ohne Titel.

**Comment by wrkb** [comment]
Ich bin mir nicht sicher, ob ich alles richtig verstehe, aber es klingt ziemlich sinnvoll.

Dieses Titel "oben" und "unten" entsprang der ursprünglich festen Reihenfolgen (weil wir ja zwei Freitextfelder haben, eines über den anderen Inhalten, eines darunter). Was sich mit einer variablen Reihenfolge (anderes Issue) z.B. erledigen würde. (Mehr als 1 Freitextfeld könnte aber weiterhin hilfreich sein).

Jedenfalls ist die Sidebar so komplex, dass uns jede Vereinfachung nur recht sein kann. Wenn dafür das Titel-Feld wegfallen muss und der Rest mit H1 und H2 usw. läuft, ist das völlig okay. @wrcg

**Comment by xwolfde** [comment]
Was dazu auch noch zu sagen wäre:
Ihr wollt ja die Kontextlinks mit eigene Titeln ausstatten.
Der WPEditor hat aber bereits einige eigene Linkverwaltung in der man sowohl externe wie interne Links suchen & einfügen kann... D.h. die Kontextlinks könnte man ebenfalls darin machen.

**Comment by wrkb** [comment]
Das heißt... alles läuft per Freitext?
Wir verlieren dann ein wenig gefühlte Kontrolle über das Layout - durch den modularen Charakter bislang würden unsere Autoren das Ganze wohl eher als getrennte Einheiten sehen und behandeln. Aber das ist wohl auch eine Schulungsfrage. Den Mehraufwand für die Autoren könnte man in Kauf nehmen.

Bleiben noch die Kontakte - da sollen dann Shortcodes zum Einsatz kommen?

Und: Wird es ein riesiges Freitextfeld oder werden es trotzdem mehrere?

**Comment by xwolfde** [comment]
Nein, die Personen sind extra. Das würde ich da bei Freitexten keinen Autor nicht zumuten wollen...

**Comment by xwolfde** [comment]
Da bei der Linkauswahl nicht zwischen extern und intern (ausser an Hand der Ziel-URL) unterschieden werden kann, macht es keinen Sinn diese zu trennen, es sei denn man möchte Titel setzen. In dem Fall gibt es also folgende EIngabeboxen:

- Text oben
- Kontakt(e) Titel   + Kontaktwahl (n1 auswahlbar)
- Linkliste 1 Überschrift + Linkwahl (n2 auswählbar)
- Linkliste 2 Überschrift + Linkwahl (n2 auswählbar)
- Text unten

Ausserdem füg ich eine Sortierungsauswahl ein:
- Sortierung: 
   - Kontakte, Linkliste1, Linkliste 2
   - Linkliste1, Kontakte, Linkliste 2
   - Linkliste1, Linkliste 2, Kontakte

**Comment by wrkb** [comment]
Klingt gut, auch wenn ich es mir nicht 1:1 vorstellen kann.
Vielleicht gucken wir hier es uns einfach an, wenn es fertig ist auf der Hummel?
Dann brauchen die Fragen auch nicht jetzt beantwortet werden, die ich hier nur festhalte.

"n1/n2 auwsählbar" versteh ich nicht.
Titel bei Links weiterhin nicht editierbar oder über Freitext nur noch frei editierbar?

**Comment by xwolfde** [comment]
Mit n1, n2, n3 meine ich die Zahl der maximal auswählbaren Links. Wir wollen ja auch nicht, daß Autoren dort Linkwüsten bauen :)  D.h. im Backend geben wir an, wieviele Links maximal gesetzt werden können.
Titel müssen natürlich edierbar sein. Sonst wäre es ja leicht gewesen :P

**Comment by xwolfde** [comment]
Da die Linklisten in der Praxis zusammengeführt sind wenn die zweite keine eigene Überschrift hat, macht die Sortierungswahl über 3 Objekte keinen SInn. Daher nur Reihenfolge Kontakte-Linkblöcke änderbar.

**Comment by xwolfde** [comment]
done in 1.3
