### ISSUE TITLE
Filter-Reset-Buttons/-links für Studiengangsübersicht

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#176]
(Hat nichts mit https://github.com/RRZE-Webteam/FAU-Theme/issues/177 zu tun)

Aktuell kann man zwar schön filtern auf https://www.fau.de/studium/vor-dem-studium/studiengaenge/alle-studiengaenge/studiengang/, aber man muss die Haken händisch entfernen überall, um wieder die Gesamtübersicht zu kriegen. 

Schöner wäre es, einen oder mehrere Reset-Möglichkeit zu haben, sie in Onlineshops:

![unbenannt2](https://cloud.githubusercontent.com/assets/9445370/6246209/af93865a-b766-11e4-9aab-6a86d18522ad.JPG)

![unbenannt3](https://cloud.githubusercontent.com/assets/9445370/6246224/e5f4eefa-b766-11e4-9b94-a45bc804ec3a.JPG)

Perfekt wäre es natürlich, einen Reset-Link pro Filtermöglichkeit zu haben (weil man mehrfach auswählen kann und damit sich viele Klicks spart) UND einen für alle Filter (zurück auf Null).

**Comment by xwolfde** [comment]
In referenz verlinkt,. Hier zum Thema nicht gehört, da Plugin.
Daher dieser Fall geschlossen. Drüben beim Plugin ist er offen.
