### ISSUE TITLE
Studiengangs-Übersicht --> Alles Studiengänge anzeigen

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#177]
(hat _nichts_ mit dem geschlossenen Issue https://github.com/RRZE-Webteam/FAU-Theme/issues/154 zu tun)
(es geht auch nicht um einen Reset-Button für gesetzte Filter in der linken Leiste, das ist ein Extra-Issue: https://github.com/RRZE-Webteam/FAU-Theme/issues/176)

ZUV-Studiengangsübersicht --> Auswahl eines Studiengangs 
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6246132/df2a65d8-b765-11e4-8104-baa7ca0d19d4.JPG)

--> wie komme ich zurück zur Übersicht aller Studiengänge? Ich scheitere regelmäßig daran: Neu laden hilft nichts, Breadcrumb hilft nicht, nur Browserbuttons (unelegant, wirkt unfertig).
Es ist ein echter Usability-Blocker für die Nutzer.

Hier wäre ein Link à la "Alle anzeigen" schön - ein möglicher Platz ist rot eingekringelt im Screen. Das dürfte auch hartcodiert sein, die Seite ändert sich ja erstmal nicht.

**Comment by wrkb** [comment]
Es ist tatsächlich ein Usability-Blocker! Ein Hard-Link auf die Ausgangsseite als Workaround reicht auch erstmal, Hauptsache die Nutzer stecken nicht fest. :warning:

**Comment by wrkb** [comment]
@xwolfde

**Comment by xwolfde** [comment]
Offensichtlich gefixt. Fall war wohl nicht geschlossen. @rvdforst Bitte an das Schliessen von Fällen denken, wenn es gelöst wurde.

**Comment by wrkb** [comment]
NICHT gefixt!!
Hast du das Issue gelesen?

#154 ist gelöst, siehe Eingangspost. Das Problem ist nach wir vor dringend zu lösen. Bitte öffne eine  Studiengang und navigiere dann mit Hilfe der Seite zurück in die Übersicht!

**Comment by xwolfde** [comment]
Hab ich gemacht. Geht? Soll ich ein Video machen?

**Comment by wrkb** [comment]
Ja bitte.
Aber ohne: Browser-zurück-Button, Auswählen-Button ganz unten und via Breadcrumb eine Ebene hoch und dann zurück. Denn das zählt natürlich nicht.

**Comment by xwolfde** [comment]
Hä? Ich mach den Haken beim Button einfach wieder weg und schon ist alles auf Anfang und damit resettet...Ich verstehe das Problem nicht.

**Comment by wrkb** [comment]
Hier geht es ums Theme/Template - ob es Design/CSS (mr) oder Code (ihr) ist, kann ich aktuell nicht einschätzen. Also nochmal:

Wenn du _einen Studiengang direkt anklickst_ (rechts im Content, nicht in der linken Spalte, nichts filtern o.ä.), dann bekommst du folgende Ansicht:

![alle_studiengange_ _fau de_-_2015-03-11_09 14 04](https://cloud.githubusercontent.com/assets/9445370/6592502/a6382c86-c7cf-11e4-866e-01ed5cad41c5.png)

Wie kommt man von hier wieder zur Gesamtübersicht? Also dahin:

![alle_studiengange_ _fau de_-_2015-03-11_09 22 08](https://cloud.githubusercontent.com/assets/9445370/6592541/1f9518c8-c7d0-11e4-9fbc-72b6c46f1c9f.png)

**Comment by xwolfde** [comment]
Ah, jetzt! Ok, du hast recht. Ich hab links geklickt.

In dem Fall wäre es IMHO vielleicht am Besten oberhalb des eigentlichen Content des Studeienganges ein "Zurück zur Übersicht" einzubauen. Dieser Link würde dann aber nur dann erscheinen, wenn man auch ein Studiengang anzeigt.

**Comment by wrkb** [comment]
Ja, genau, das wäre gut. Der kann ja fürs Erste hardcodiert sein, die Zielseite wird nicht ohne Weiteres umbenannt.

Danke!

**Comment by xwolfde** [comment]
Jetzt bleibt nur die Frage wer es macht ;P Wann hat Cathrin es fertig? (*und jetzt schnell in Deckung gehen*)

@rvdforst Schaust du da bitte mal ob das nebenher machbar ist? Für dieses Plugin muss aber danach geklärtwerden, wer die Betreuung und Weiterentwicklung macht. Nur weil wir damals Cathrin darin ausgeholfen haben, kann dies nicht zu einer Daueraufgabe von uns werden.

**Comment by wrkb** [comment]
Och, wenn es nur ein php <? echo irgendwas ist, kann ich das auch machen. Ich hack das da rein und schicks euch. Ist die Frage, wie das aussieht und ob ihr das pullen wollen. ;)

Hat es ernsthaft Sinn, sich die Datei ausm Github rauszusuchen und den Link reinzusetzen? Ist mal was anderes, guck ich mit Cathrin mal rein.

**Comment by rvdforst** [comment]
Ho-ho! Ich füge einfach ein php echo ein... ;-)
Aber Scherz beiseite, ich werde mich darum kümmern.

**Comment by wrkb** [comment]
Danke Rolf :heart_eyes:

**Comment by rvdforst** [comment]
Ist erledigt + ausgewählte Parametern bei Studiengangsdetailansichten bleiben jetzt ausgewählt.

**Comment by wrkb** [comment]
Passt, dankeschön!
