### ISSUE TITLE
Lightbox-Zoom: Wie groß dürfen Bilder angezeigt werden?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#178]
Aktuell scheinen Bilder nicht größer als rund 700 Pixel zu "zoomen", auch wenn ihre maximalen Abmessungen in der Datenbank größer sind.

a) Wonach richtet sich das? Selbst können wir das scheinbar nicht einstellen.
b) Ist es möglich, dass Geräte/Browsergrößen-spezifisch zu machen, so dass die Lightbox immer den maximalen Platz ausnutzt (wenn das Bild groß genug ist)? Responsive und so?
c) falls b=nein - was wäre dann ein sinnvolles Vorgehen?
d) Spricht etwas dagegen, die Lightbox auch für Seiten und andere Post-Types zu verwenden? https://www.fau.de/universitaet/das-ist-die-fau/region-erlangen-nuernberg/
e) Wenn wir in der Lightbox Bilder anzeigen, die mit noch größeren Pixelmaßen in der Datenbank sind, kann man dann _trotzdem_ noch einen Link zum originalgroßen Bild anzeigen (dass man dann via Browser und dem Pluszeichen scrollend anschauen kann). Fällt unter "Wünschdirwas" und "Brauchenwirs"?

Danke für die Aufmerksamkeit,

Karsten

@wrcg

**Comment by xwolfde** [comment]
Das war bei Beiträgen fest definiert worden auf 	add_image_size( 'gallery-full', 940, 470); 
Ich hab jezzt mal eingestellt, dass das Bild im Original verlinkt wird und keine herunterskalierte Version.

Zur Frage ob man Lightbox auch woanders verwenden kann? Ja, eigentlich schon...

Wobei bei der gelinkten Seite wundert mich etwas, dass dort das Artikelbild nicht oben angezeigt wird? Ist das Absicht? Stattdessen habt ihr im Content dann ein eigenes Bild normal angegeben.

**Comment by xwolfde** [comment]
Bin bei den Galerien dran. Dort mach ich jetzt auch konseuqnt lightbox. bei Bildenr in Artikeln müsst ihr noch von Hand die Klasse anfügen

**Comment by xwolfde** [comment]
Zusammenhang mit #93

**Comment by xwolfde** [comment]
Größe von Lightbox bei Galerien und Thumb auf "full" gestellt.

**Comment by wrkb** [comment]
Fragen:

1) "full" heißt welche maximale Pixelgröße?
2) "In Oiginalgröße" führt auf die Lightbox, nicht auf das Original im Browser? Noch ein Fehler? (In der Lightbox kann man nur eine htm speichern und bekäme man da die Originalgröße aus der DB?)
3) Die Bildunterschrift wird nicht in der LB angezeigt.
4) Können wir "In Originalgröße" (selten zutreffend) noch umbenennen in "Vergrößern" (immer richtig)?

**Comment by xwolfde** [comment]
1. full heisst, wie es hochgelanden wurde. 
2. Ja, so ist das gewollt.
3. fixed
4. ok, so done.

**Comment by wrkb** [comment]
Wunderschön :+1:

**Comment by wrkb** [comment]
...fällt uns noch ein: Lightbox bitte auch bei Bildern auf Beiträgen und auf Seiten aktivieren.
Dann gibt es :100:%

:D

**Comment by xwolfde** [comment]
Ne, das geht nicht automatisch. Bzw. ein Automatismus, wäre in 50% der Fälle falsch. Die Entscheidung ob in Beiträgen ne Lightbox aufklappen soll oder nicht, die muss schon der Autor treffen.
Wenn er das tat und ne Lightbox will, dann muss er dann halt rel="lightbox" in dem <img> Tag einfügen.

**Comment by wrkb** [comment]
Okay, du erwähntest das schon mal. Danke, so geht es natürlich auch.
