### ISSUE TITLE
Beitragssuchergebnisse ab Seite 3 nicht blätterbar

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#182]
...getestet mit dem Suchwort "tag"
Im Chrome passiert garnüscht. Im Firefox bloß lustiges Rumgezappel, aber kein echtes Laden.

**Comment by xwolfde** [comment]
probiere es mal auf der testinstanz.

**Comment by wrkb** [comment]
da geht es.

FAU-Webredaktion
Blog: http://blogs.fau.de/webredaktion/
Tel.: 09131/85 -70203

Von: Wolfgang Wiese [mailto:notifications@github.com]
Gesendet: Freitag, 20. Februar 2015 15:36
An: RRZE-Webteam/FAU-Theme
Cc: Busch, Karsten
Betreff: Re: [FAU-Theme] Beitragssuchergebnisse ab Seite 3 nicht blätterbar (#182)


probiere es mal auf der testinstanz.

**Comment by xwolfde** [comment]
dann mach dir keine sorgen, beim nächsten update läufts besser. ursache wahrscheinlich die: Synonyme und Glossareinträge wurden da auch gefunden...
