### ISSUE TITLE
Personenvisitenkarten

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#183]
...du bist wohl noch dran, Wolfgang, aber das Ticket ist schon geschlossen?

Bei den Personenvisitenkarten ist

a) noch eine komische Einrückung drin (Fehler, kein enhancement)
b) das Platzhalterbild umzusetzen (notfalls enhancement, aber eigentlich schon lange hässlich...)

b) hattest du weiter rausgeschoben, oder? Dafür brauchts aber noch ein Platzhalter-Ticket... soll das hier dafür herhalten?

![Uploading Unbenannt.JPG . . .]()

**Comment by xwolfde** [comment]
Wir machen ein neues Plugin dafür. An das vorhandene im Theme werden wir nichts weiter entwickeln. 
(Auser das iche inbauen werde, es zu deaktivieren vom Theme, damit dann später das neue eigenständig aktiviert werden kann)
Alles neue wird in das neue Plugin reinkommen, welches hier im Git ist: https://github.com/RRZE-Webteam/fau-person

**Comment by wrkb** [comment]
Das Issue hast du zu schnell geschlossen, a) und b) warten noch auf Antworten :)

**Comment by xwolfde** [comment]
" An das vorhandene im Theme werden wir nichts weiter entwickeln."

**Comment by xwolfde** [comment]
Add: Bitte Wünsche an das Plugin beim Issue-Tracker des Plugins einstellen (siehe LInk oben)
