### ISSUE TITLE
Lizenzangabe als Link in Bildunterschrift

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#184]
...geht schon bei Bildern in der Datenbank, die als Beitragsbild angehangen werden. Allerdings noch per Hand (kein RTE am Feld):

![unbenannt3](https://cloud.githubusercontent.com/assets/9445370/6328219/66b3726c-bb65-11e4-806a-1ca4c111c259.JPG)

Sieht dann so aus (Link ist leider kaum sichtbar, farblich)

![unbenannt2](https://cloud.githubusercontent.com/assets/9445370/6328222/7a708a24-bb65-11e4-8fd7-a70a1c53da1a.JPG)

Beim Einsatz der alternativen Bildunterschrift geht das noch nicht, auch da wäre es schön - Linkmöglichkeit plus RTE am Feld:

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6328229/94c098ec-bb65-11e4-8dc7-05a8bf91f1ff.JPG)

**Comment by xwolfde** [comment]
Pfui! Lass das sein mit dem HTML! Hab ich dir letzte Woche geschrieben, warum das Böse und gefährlich ist!

**Comment by xwolfde** [comment]
Ihr wollt, wenn ich das "RTE" richtig verstehe (wofür steht das?) eine extra Verwaltung für Lizenzinfos, die hier in Form eines zusätzlichen weiteren EIngabefeldes daherkommt, oder?

**Comment by wrkb** [comment]
Ich erinnere mich. Haben aber das alte Ticket nicht gefunden hier :(
RTE steht für Rich Text Editor - bei dem würde man das händische html umgehen.

Wie war denn die Quintessenz generell? Dass wir ohne Links trotzdem korrekt Lizenzen angeben können? Eigentlich ist es doch ein Verstoß ohne Link, oder?

**Comment by xwolfde** [comment]
Verwendet ihr denn Fremdbilder die unter CC stehen und wo fest vorgegeben ist, wie der Lizenztext bei dem Bild angezeigt werden muss? 
Wenn nicht, reicht die Info auch an anderer Stelle, bspw. im Impressum unter Lizenz-Hinweise.

Nochmal zum anderen problem: Lightbox erlaubt nur einen Plaintext als Bildunterschrift. Wenn da HTML drin ist, wie bspw. ein Link, geht es kaputt, es geht dann nicht mehr. Ist so.

**Comment by xwolfde** [comment]
Wie auch immer, ihr habt jetzt einen Text als Bildunterschrift da könnt ihr ohne HTML reinschreiben was ihr wollt. Das muss erstmal reichen, sorry.

**Comment by wrkb** [comment]
CC-Bilder: Ja, und zwar gern und häufig. Aber in letzter Zeit eben nicht mehr, wegen der schwierigen Lizenzangabe... Und wenn ich das richtig verstand, ist die Verlinkung essenzieller Bestandteil (Web halt, kann man auch nachvollziehen).

**Comment by wrkb** [comment]
So, habe das ganze jetzt nochmal mit den Pressekolleginnen und Luisa durchgespielt und -gesprochen: Wir verzichten momentan oder gar rückwirkend auf CC-Lizenz-Bilder, weil der Link nicht machbar ist. Das ist ein großes (!) Problem.

Nun haben wir ja Testbilder genutzt in der Hummel und da wird der Link in der Lightbox halt nicht angezeigt. Das ist unproblematisch, bei der Standardanzeige im Browser ist ja auch kein Hinweis dran. (Das Skandalurteil dazu wurde ja längst relativiert). Ich kann das Lightboxproblem zumindest optisch grade nicht sehen...?

Die Argumente mit sauberem Code verstehe ich natürlich grundsätzlich auch, aber es wäre leider schwer vermittelbar, dass ausgerechnet das im eigentlich offen angelegten FAU-CMS nicht machbar ist - jede andere Seite hat das: https://netzpolitik.org/2015/in-eigener-sache-constanze-kurz-verstaerkt-unser-team/, http://t3n.de/news/google-panda-40-546467/
Außerdem sollen die Fakultäten doch auch CC-Bilder nehmen können...

Was tun? Ohne CC geht es mittelfristig nicht (Prophezeiung).

Andere Lighbox-Lösung wählen? Oder erstmal zugunsten der CC-Bilder deaktivieren (ja, das wäre absolut ärgerlich nachdem du uns alles so schön gebaut hast :( ) oder nen anderen Workaround?

**Comment by xwolfde** [comment]
Werdet euch erstmal klar darüber, wie ihr Bilder korrekt benutzt. DANN können wir gern weiter reden.
Momentan mixt ihr wild Titel, Beschreibung, Bildunterschriften, wie es euch gerade mal passt.
Das ihr auf CC Bilder Pauschal verzichtet, also auch auf solche die gar keinen Link fordern, zeigt auch das ihr die Lizenzvarianten noch garnicht verstanden habt. 

Wir werden hier bei Zeiten etwas machen. Aber das hat geringere Prio für mich, da es nicht den Betrieb des Themes verhindert oder einen fatalen Error wirft.  Bis dahin müsst ihr damit leben was geht. "Wir", sprich der Rest der Uni, muss auch damit leben, dass die Pressestelle keine sauber lizenzensierten Bilder herausgeben will.

**Comment by wrkb** [comment]
>Werdet euch erstmal klar darüber, wie ihr Bilder korrekt benutzt. DANN können wir gern weiter reden.

Vielleicht müssen wir uns wieder treffen, wir haben es doch schon definiert. Bzw. die oben zitierten Links zeigen das, was wir und alle brauchen. 

>Momentan mixt ihr wild Titel, Beschreibung, Bildunterschriften, wie es euch gerade mal passt.

Wieso? Wo denn?

>Das ihr auf CC Bilder Pauschal verzichtet, also auch auf solche die gar keinen Link fordern, zeigt auch das ihr die Lizenzvarianten noch garnicht verstanden habt.

Tun wir nicht. Bilder ohne Linkangabe sind die Ausnahme (die wir nutzen).

>"Wir", sprich der Rest der Uni, müssen auch damit leben, dass die Pressestelle keine sauber lizenzensierten Bilder herausgeben will.

Das musst du nochmal genau erklären. ;) Aber nicht hier.
Es kommt nochmal eine genauere Rückmeldung, aber nicht von mir allein, ich bin hier vor allem Mittler.

**Comment by xwolfde** [comment]
ich schließe denn Fall hiermit. Es wird eine allgemeine Lösung in Form eines Plugins geben, welches dann die Bilder um entsprechende Auswahllisten für verfügbare oder berabeitbare Lizenzen ergänzt.
Das ist dann nicht mehr Sache dieses Themes. Daher "wontfix" für hier.
Bis dahin muss mit den vorhandenen Mittel ausgekommen werden, die durch Bildbeschreibung etc. gegeben sind.

**Comment by wrkb** [comment]
Okay, wie besprochen, Wiedervorlage ab Mai 2015, bis dahin die besprochenen Workarounds.
