### ISSUE TITLE
Schriftart bei Beitragsdatum und Beitrags-Kategorie ändern

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#185]
...wir haben das Problem eingekreist (zu zweit):

Die Schriftart ist auf der Liveseite eine andere als im Backend. Im Backend ist es Roboto, die wollen wir:

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6328390/3df86e8e-bb67-11e4-9e9c-6f49dfb9b1b3.JPG)

Auf der Liveseite wird Times o.ä. genommen (Fallback des Browsers?) ist irgendwie Fontawesome statt der Schriftart im CSS definiert - vielleicht ist das die Ursache?

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6328423/8a3ddd74-bb67-11e4-8bc8-f8a64301ca7b.JPG)

Fazit: Roboto :+1: Times :-1:

**Comment by xwolfde** [comment]
Olle Kamelle. Schau mal auf Test!

**Comment by wrkb** [comment]
Hamwer gemacht! Guck: (Neue :eyeglasses: ? :) )

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6328863/e4de58fe-bb6b-11e4-958e-847760d6b9bb.JPG)

**Comment by xwolfde** [comment]
WTF

**Comment by xwolfde** [comment]
Ok, jetzt.
