### ISSUE TITLE
Alte Personenverwaltung deaktivierbar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Theme#186]
Entweder ist das neue Plugin so schnell und hat alles drin was wir wollen, dann löschen wir den alten Code aus FAU-Plugin und das ACF, oder wir müssen ein Schalter machen, mit dem der Personalkram deaktivierbar wird.

@endv02

**Comment by wrkb** [comment]
Moment, ich krieg Angst: Wird unser Weg dann vollständig ersetzt? Wir kenne das neue Plugin gar nicht - was ändert sich denn dann? Prophylaktische Panik, Karsten

**Comment by xwolfde** [comment]
HARHARHAR

**Comment by wrkb** [comment]
:fearful:

**Comment by xwolfde** [comment]
done. Ist an/abschaltbar.

Zur Beruhigung: Natürlich testen wir das neue Plugin ausführlich erstmal woanders.
Es kann alles was das alte kann. Und dann einiges mehr, nämlich bessere strukturierte Daten (z.B. bei Telefonnummern oder akademischen Titeln) verwalten, damit z.B. nicht wie jetzt ein Wildwuchs an Tippfehlern herrscht (insbesondere Telefonnummern werden ja noch immer abhängig von der tagesform geschrieben). 
Ausserdem soll es Datensyncs mit UnivIS, IdM, CRIS und co geben.

Deswegen muss das alte auch deaktivierbar sein, damit es keine Konflikte gibt.
Das jetzige alte wird daher auch nicht weiter entwickelt. 
Für dei Fakutäten wird nur das neue verfügbar gemacht und das alte nicht übernommen.

**Comment by wrkb** [comment]
Okay, Puls ist wieder bei 60. Die optische Stufe macht ihr aber noch raus? Ist ein Issue hier irgendwo im Hub.
Habt ihr eine Zeitangabe? Bleibt es bei Mitte März/April? Oder wird es später? (Wegen des fehlenden Platzhalters...)

**Comment by xwolfde** [comment]
Was ist die "optische Stufe"?

**Comment by wrkb** [comment]
--> https://github.com/RRZE-Webteam/FAU-Theme/issues/183

**Comment by endv02** [comment]
Ok, dann steht doch jetzt alles was noch gemacht werden muss in #183.
Können wir dann dieses Ticket geschlossen lassen (alte Personenverwaltung ist ja jetzt deaktivierbar) und es bei einem Ticket bzgl. Personenverwaltung belassen, sonst verliert man irgendwann den Überblick, was eigentlich wirklich zu tun ist...
