### ISSUE TITLE
Statistik-Übersicht

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#187]
Wir sollten uns ja hier nochmal alles wünschen, was uns auf dem Herzen liegt, nichtwahr? :) Daher halten wir hier noch mal den Wunsch fest, auch in Wordpress die Seitenzugriffe irgenwie sichtbar zu machen. Das Dashboard-Widget/-Plugin etc. im Blogsystem war wunderbar, auch wenn es für unser Netzwerk ja scheinbar nicht so einfach umzusetzen war?

Wenn es aber irgendwie geht, mindestens für die Newsbeiträge, gerne für mehr, hätten wir gern wieder so eine Übersicht der Zugriffe. Oder gern ein anderes Sammel-Tool jenseits von Wordpress, das eh auf der Wunschliste steht :)

Bitte um wohlwollende Einschätzung dieses Tickets, der Aufwand/die bisherige Einschätzung sind uns ja bekannt :-) :rose:

**Comment by xwolfde** [comment]
ich bin doch nicht der Weihnachtsmann! :P 
Könnte ein Plugin sein, welches auf die Statistik zugreift. Wieviel wäre euch das finanziell wert?

**Comment by wrkb** [comment]
Mist, ich hatte echt Hoffnung! :santa: 
Also finanzielle Details setze ich _hier_ nicht rein, aber ich kann das Budget natürlich ansprechen. Die Statistik ist definitiv ein Projekt mit hoher Wichtigkeit. Ich melde mich dazu gesondert.

**Comment by xwolfde** [comment]
Pluginsache -> wontfix hier
