### ISSUE TITLE
Seiten falsch verknüpft

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#189]
Wir wissen nicht, wie es passiert ist, aber:
Die Seite https://www.fau.de/forschung/forschungsprofil/forschungsprofil-und-wissenschaftsschwerpunkte-der-fau/
falsch (!) ist mit der englischen
https://www.fau.eu/?page_id=687715
verknüpft. (die auch keine normale URL hat sondern die ID aus der Seitenliste).

Wie kann so was passieren und wie ändern wir das?

**Comment by rvdforst** [comment]
1. Ich vermute, dass der Fehler mit der Verknüpfung von einer früheren (und fehlerhaften) Version des Workflow-Plugins kommt. Diese Verknüpfung muss ich von der DB löschen.

2. Nur veröffentlichte Dokumente enthalten keine ID im Permalink.

**Comment by wrkb** [comment]
1. danke
2. Ich hatte _extra_ nachgeschaut, ob die Seite online ist. Und trotzdem: fail. Du hast recht. (Browserchaos).

**Comment by rvdforst** [comment]
Ist erledigt!
