### ISSUE TITLE
Bilder und Lightbox

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Theme#193]
ggf. doch ein oder zwei Schalter sinnvoll:
- Bilder in Artikel-Content immer automatisch mit "lightbox" verbinden (Default: nein)
- Bilder in Seiten-Content immer automatisch mit "lightbox" verbinden (Default: nein)

**Comment by xwolfde** [comment]
Title-Attribut vom <a title=""> welches von Lightbox verwendet wird, wahlweise entweder aus Beschriftung, Beschreibung, Alttext oder Bilddateititel (so nenn ich das jetzt mal!) nehmen. Klärungn welches. Oder auch das optional?

**Comment by wrkb** [comment]
Wir brauchen im ersten Schritt nur "Beschriftung", siehe Referenzbild:
http://test4.wordpress.webhummel.rrze.uni-erlangen.de/2015/03/03/bildbeispiel/

Normalerweise ist es hilfreich, dass man immer alles auswählen kann. Hier bin ich nicht sicher, da wir uns an der Standardprozedur von Wordpress (den Standardthemes) orientiert haben. Und dort ist die Bildbeschreibung für die Anhangsseite reserviert. Letztere nutzen wir nicht im Theme, aber falls das irgendwann mal kommt, sind die Workflows verhunzt und/oder die Bilder. Ich würde hier eine Vorgabe schaffen - und wir empfehlen da natürlich unseren Weg (den Standard-Wordpress-Weg) :ghost:

**Comment by xwolfde** [comment]
Muss auf Release 3 verschoben werden.

**Comment by xwolfde** [comment]
Case in FAU-Einrichtungen übernommen
