### ISSUE TITLE
xliff -Datei bei Beiträgen übernimmt noch nicht alles

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#195]
Anleser und Bildunterschriften der Beitragsbilder  werden offensichtlich nicht mit in der xliff-Datei gespeichert. Kannst du das noch einstellen, Rolf? Danke!
(Text und H1, sowie Bilder und Bildunterschriften werden korrekt übernommen und können übersetzt werden.)

**Comment by wrkb** [comment]
gehört nach https://github.com/RRZE-Webteam/cms-workflow/issues/39, weiterhin offen!
