### ISSUE TITLE
Schützbarkeit von Seiten via IdM

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#196]
...pardon, wenn hier die Lösung schon fast fertig ist, ich kenne nur den Stand nicht. Im Crashkurs mit der Medfak kam die Frage auf und spätestens im Herbst wollen wir auch hier in der ZUV die alten Seiten mit internen Seiten umstellen auf Wordpress - dann hilft uns .htacess nicht mehr (wäre ein Blocker).

**Comment by xwolfde** [comment]
@rvdforst Sollte doch eigentlich drin sein?

**Comment by wrkb** [comment]
Oh, grade entdeckt. Gibt es hier Neugikeiten? Wird für uns relevant Ende Sommer, wenn es ums Intranet geht. Dort können wir erst Inhalte umschichten (eigene Site fürs FAU-Intranet), wenn wir Teile nicht öffentlich anlegen können (Passwortschutz ist keine Hilfe).

**Comment by xwolfde** [comment]
@rvdforst Wie ist hier der STand?

**Comment by rvdforst** [comment]
Ich bin noch dran und es kann ein bisschen noch dauern. Die Lösung ist einfach nicht trivial.

**Comment by xwolfde** [comment]
On work. Plugin ist im Test. Comments und Issues dazu bitte im zugehörigen Gitlab-Projekt ( da müsstet ihr glaub ich rankommen)
