### ISSUE TITLE
Dateiauszüge (Shortcode) - Ausgabe

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#198]
...bei der Ausgabe von Dateien anhand der Kategorien: Die Dateien aus der Oberkategorie (hier: "Wege ins Ausland") sollen über den Akkordion-Reitern der Unterkategorien angezeigt werden (hier: Informationsveranstaltungen" und die darunter) und nicht darunter wie bisher.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6441535/1e6646cc-c0e9-11e4-9d86-e5dc6af65849.PNG)

**Comment by xwolfde** [comment]
Kann ich nicht nachvollziehen, bitte URL oder Besipielseite auf der Testinstanz.

**Comment by wrkb** [comment]
https://www.fau.de/dokumentkategorien
z.B. Service für Studium und Lehre oder Dozenten- und Personalmobilität

**Comment by xwolfde** [comment]
@rvdforst Das kommt aus irgendein Plugin. Bitte prüfen (und bei Gelegenheit gleich mal dokumentieren, wer welchen Shortcode macht) und das issue dorthin übernehmen.

**Comment by xwolfde** [comment]
Doch kein Plugin; Es hat sich in shortcodes.php versteckt.

**Comment by xwolfde** [comment]
Halbrichtig. Die Anzeige erfolgt im Theme; Aber damit das passiert muss es eine Taxonomie bei den Medien geben. Dies macht wohl ein anders Plugin.

**Comment by xwolfde** [comment]
Sollte erstmal doch ins Theme übernmmen werden, da Datei/Downloadlisten durchaus weit benutzt werden. Daher kein Verschieben auf Sommer möglich.

**Comment by xwolfde** [comment]
Wird als Plugin gelöst. Nur für CMS-Instanz und andere. Bei FAU-Theme/ZUV-CMS-Instanz bleibt alles wie es ist.

**Comment by wrkb** [comment]
...heißt aber auch, wenn uns eure Lösung besser gefällt, können wir sie aktiveren und unsere deaktiveren?

**Comment by xwolfde** [comment]
Nur wenn ihr lieb seid :P

**Comment by wrkb** [comment]
Also ja. ;)
