### ISSUE TITLE
Audio-Einbettung läuft nicht/wird nicht schön eingebettet

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#20]
...Beispiel in Heledir: http://heledir.zuv.cms.rrze.uni-erlangen.de/2014/10/29/news/test-videoeinbindung/
In Megli ebenfalls getestet, gleiches Problem.

**Comment by xwolfde** [comment]
Muss komplett neu gemacht werden. Vorhandener Code kann nicht für Fakultäten verwendet werden.
