### ISSUE TITLE
Fallback-Bild für Portalmenüs - aufhübschen?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#200]
Hallo,

das nützliche Fallback-Bild (Ersatzbild) für die Portalmenüs ist schön, aber es könnte noch schöner sein. Vielleicht ein blasseres schöneres Wasserzeichen, was Zurückhaltendes. (Bei mir wirkt die Schrift immer zu pixelig, auch wenn der Rest des Bildes scharf ist)
Wir haben gesucht - man kann es nicht individuell hinterlegen, glaube ich. 

Soll wir was liefern (GPL-Lizenz oder was du brauchst) oder kann Barbara...? Und wird das evtl. noch einstellbar?

Gruß

Karsten

**Comment by xwolfde** [comment]
Ruhig Brauner :)
Da muss ich eh noch ran .

**Comment by wrkb** [comment]
Macht wat Schönes! :bouquet:

**Comment by xwolfde** [comment]
Immer diese Ansprüche :)

**Comment by xwolfde** [comment]
Zusammenhang mit #194

**Comment by xwolfde** [comment]
Habs mal ganz sanft angepasst.
