### ISSUE TITLE
Manuell gesetzt Lighbox (WYSIQYG oder html direkt): BU fehlt

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#202]
Unten zitierte Anleitung funktioniert, leider ist in der Lightbox aber die Bildunterschrift nicht zu sehen - wie bei den anderen Bildern, an die die LB per default aktiviert wird.

> Im HTML-Editor geht man zu dem <a ...> welches das Bild umrandet und
> füght
> ein:   ..  class="lightbox" ...
> 
> im WYSIWYG-Editor klickt man auf das Bild und dann auf das erscheinende
> Bearbeiten-Symbol. Dann kommt das angehängt Fenster mit den
> Bildeigenschaften.
> 
> Dort fügt man dann unter "Erweiterte Optionen" ganz unten CSS-Klasse
> verküpfen "lightbox" ein. Tut man dies, wird das Bild in einer Lightbox
> geöffnet.
> Tut man es nicht, wird das Bild direkt aufgerufen.

**Comment by xwolfde** [comment]
Die Lightbox nimmt das was im title="" steht als Bildunterschrift. (was auch der grund ist, warum da kein HTML drin sein kann.

**Comment by wrkb** [comment]
Problem 1: Im Title steht was drin. Wird aber nicht angezeigt.

Problem 2: Wieso nimmt die Lightbox title nehmen? Also das Feld "Titel" bei "Bild bearbeiten" ist gemeint, oder? Richtig wäre "Beschriftung", das Feld wird überall für Bildunterschriften verwendet und das doch systemweit unsere Systematik? Bei Beiträgen nutzen wir das Titelfeld tatsächlich auch anders, da Wordpress ja die Titel durchsucht und wir unsere Bilder nicht anders suchbar machen können (mangels IPTC, unter anderem).

**Comment by xwolfde** [comment]
Weil Lightbox ein drauf gesetztes JavaScript ist, welches nichts mit dem CMS zu tun hat. Ist so.
