### ISSUE TITLE
Zusätzliches Eingabefeld für Thementitel

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#206]
...genauer: Themen-Untertitel und evtl. auch Thementitel. Ist auch für die Fakultäten relevant.
Aktuell sehen Blog-Meldungen komisch aus, wenn sie auch in Themen benutzt werden - statt des normal langen Vorspanns (Anleser) können wir dort teils nur sehr kurze Sätze wählen, weil auf dem Themenbild nicht so viel Platz ist (viel Text sieht dort schlecht aus).
Screens:

![unbenannt2](https://cloud.githubusercontent.com/assets/9445370/6552109/2fd3791c-c642-11e4-8d53-e198be315264.PNG)

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6552143/b41f5fba-c642-11e4-9ff6-78e05a5614ed.PNG)

Optimal wären also zwei weitere Felder an der Beitrags-Eingabemaske, die Titel (anstelle der h1) und Untertitel (statt des Anlesers) eines Themenbildes definieren.

Ist kein Nice-to-have (dazu ist es zu wichtig), mit eurer aktuellen Auslastung aber "nur" ein enhancement.

Ich hoffe, ich habe das hier verständlich ausgeführt :)

**Comment by xwolfde** [comment]
Dafür gibt es den "Auszug", bei Artikeln den man befüttern muss. 
Einen anderen Titel als den Haupttitel jeweils pro Thema (ja welches denn, für jedes Thema ein andere? Witz.) ist ein Fail der Redaktion.
Weitere Felder würden die Bedienung für unbedarftere und weniger geschulte Anwender (und ihr macht ja auch schon Fehler obwohl ihr geschult seit) nur erschweren.
Von daher lehne ich diesen Vorschlag erstmal ab.

**Comment by wrkb** [comment]
Korrekt, die Komplexität erhöht sich. Aber ich würde sagen, das ist in jedem CMS so, wenn man es anpasst...? Man kann das Feld ja ausblenden.
Verstehe die ersten Einwände nicht so ganz.

Der Auszug ist aktuell nicht definiert (oder? Wo ist es dokumentiert?). Wir nutzen den Anleser für den Vorspan (gelb markiert).

Über das Themenbild in der Startseiten-Bühne wird nun der h1-Titel und der Vorspann gelegt. Heißt: Wir müssen den Vorspann zu kurz halten - er fällt aus dem Rahmen, der Mehrwert geht verloren. Und den h1-Titel anpassen zu können, würde einfach die Sache rund machen, man hat dann die völlig freie Gestaltung beim Titel auf der Startseite (und kann freier und ansprechender formulieren!). Es ist quasi eine Erweiterung zum schönen Extra-Themenbild, dass wir dank euch haben :pray: 

Der Thementitel ist ja am Beitrag gebunden - nicht für jedes Thema ein anderern. Er soll sich nur zum Beitragstitel unterscheiden.

Verständlich? Sonst gern auch telefonisch kurz, damit wir nicht aneinander vorbeireden.

**Comment by xwolfde** [comment]
Ich hab dem obigen nichts hinzuzufügen. Der Fall bleibt geschlossen.

**Comment by wrkb** [comment]
nichma als nice to have...?
