### ISSUE TITLE
Vimeo auf fau.de?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#21]
...ist das überhaupt geplant? Z.B. für Material, dass wir nicht auf video.fau.de stellen können. Iframes sind nicht mehr erwünscht, oder können wir notfalls damit arbeiten?

**Comment by xwolfde** [comment]
In den Glossaren funktionieren Shortcodes und oEmbeds, In den normalen Akkordions auch.
