### ISSUE TITLE
Eigenheit (?) bei Sonderzeichen im H1 bei Beiträgen

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#213]
Wenn man im Beitragstitel ein > oder ein < einsetzt, wird daraus HTML/ASCII-Code. Bei anderen Sonderzeichen (Umlaute) passiert das nicht. Zugegebenermaßen ein seltener Fall, aber kommt vor.

Bug? normal? Muss irgendwas getan werden?

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6595871/ddcfa236-c7ee-11e4-9810-c2b0a4d7f53d.PNG)

![2](https://cloud.githubusercontent.com/assets/9445370/6595872/e3acaf8c-c7ee-11e4-87e3-5b58db46e923.PNG)

**Comment by xwolfde** [comment]
Ja, das ist absicht und macht Sinn bei HTML-zeichen und Entities. Aber ist das Ausgabeergebnis denn jetzt falsch?

**Comment by wrkb** [comment]
Nee, die Ausgabe passt. Wir wusste nur nicht, warum das bei > auftritt und bei ä (&auml;) nicht. Danke.
