### ISSUE TITLE
h2-Titel mit in Suchausgabe

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#216]
Wenn wir auf fau.eu nach language courses suchen, kommen 4 bis 5 Seiten, die alle Sprachkurse zum Thema haben, aber sehr verschiedene Inhalte für verschiedene Zielgruppen.
Um den Nutzer hier gezielter zu informieren und zu leiten, wäre es hilfreich, die h2 mit anzuzeigen.Das kostet zwar wieder Platz, aber gibt sehr hilfreiche Zusatzinformationen.
Vorteile:
1) Wir müssen nicht die h1 ändern, was für chaotische Navigations-Menüs sorgen würde (language courses for placement students ist einfach sehr lang).
2) Wir müssten nicht Hinweise in den ersten Zeilen des Seitentextes unterbringen (den die Suche ja noch mit anzeigt) und hoffen, dass die Leute das beim Scannen der Suchergebnisse mitkriegen. Weniger unnütes Geschwafel im Text also.
3) Wir haben einen guten Grund mehr, die h2 in den Schulungen als wichtigen Teil der Seite zu vermarkten und zu insistieren, dass sie sinnvoll und aussagekräftig verwendet wird (noch nicht überall der Fall).

Was meint ihr?

@wrcg @lagerlit 

P.S. Das könnte auch bei den hunderten Kontakt-Seiten u.ä. helfen, die immer nur "Kontakt" heißen

**Comment by xwolfde** [comment]
"Seitentitel müssen eindeutig sein" :=)
Ist aus guten Gründen ein Kriterium für Usability und Barrierefreiheit.

Das was du vorschlägst ist ein Workaround um ein Fehler. Dieser Workaround würde vielleicht bei der siteinternen Suche helfen. Bei Google und anderen Suchmaschinen allerdings nicht. 
Von daher: Sorgt lieber für richtige eindetige Titel, die in den ersten 40 Zeichen unterschiedlich sind. Dann braucht man nicht vergeblich Workarounds versuchen.

**Comment by wrkb** [comment]
Ja klar, es geht um die interne Suche. Aber Google stellt doch nicht ausschließlich auf die h1 ab - dazu gibt es doch Struktur und h2 und folgende?
Eindeutigere h1 wären das Optimum, aber hast du dir mal bildlich vorgestellt, wie dann die Menüs aussehen? Wollen wir das wirklich?

**Comment by xwolfde** [comment]
Natürlich wollen wir das - aber ihr müsst das menü sinnvoll machen. Das bedeutet auch, daß es keine Inhaltsdupletten mehr geben sollte.

Mit der Breadcrum erkennt man es gut.
Also bspw. das wäre schlecht (kein echtes Beispiel!):

fau.de > Internationales > Internationales Büro > Internationale Kontakte 

Richtig wäre:
fau.de > Internationales > Büro > Kontakte

**Comment by wrkb** [comment]
Das machen wir ja schon.
Aber bei den Sprachkenntnissen hätten wir dann - um deinem Beispiel zu entsprechen - 4 Seiten die mit "Sprachkenntnissen für" anfangen - und mit der Zielgruppe dahinter extrem lange Menüeinträge ergeben...
Pressiert jetzt nicht allzu sehr, ggf. können wir uns da noch mal austauschen, ihr müsst das ja auch den Fakultäten irgendwie als Empfehlung vermitteln. Aber ich habe noch keine Patentlösung...

**Comment by xwolfde** [comment]
Nee, eben doch nicht. EINE Überseite 

 .. > Sprachkenntnisse > English
 .. > Sprachkenntnisse > Deutsch
 .. > Sprachkenntnisse > Suaheli
 .. > Sprachkenntnisse > Klingonisch
 .. > Sprachkenntnisse > Bayerisch

**Comment by wrkb** [comment]
...gib doch mal language course auf fau.eu und schau selbst, worum es geht. Eine Seite mit Sprachkursen/-kenntnissen vom Welcome Centre, eine aus Studium, eine für Praktikanten und eine für Auslandgeher. DAs kann man nicht in einen Baum packen.
Außerdem: So ein superstrukturiert Baum sorgt für die 9 Unterebenen, die wir früher hatten - contra Usability.

**Comment by xwolfde** [comment]
Naja, in diesem Fall ists halt genauso, als wenn ich auf der deutschen Seite nach "Einrichtung" oder einem anderen Allerweltsbegriffe suche.
Ändert aber nichts am obigen. 
Wenn jemand nicht genau genug suchen kann, soll er halt ein fax senden :P

**Comment by wrkb** [comment]
Ich mag Faxe! :fax: 
Nungut, wir schauen mal, wir müssen das jetzt aufbauschen, das Thema Suche kommt immer wieder.

**Comment by xwolfde** [comment]
Besorg mir das Geld für eine GSA und wir können mehr Ausnahmebedürfnisse befriedigen :) 
(Nebenbei hab ich genau das vor einem Jahr vorhergesagt.)

**Comment by xwolfde** [comment]
Nicht relevant für Fakultäten. Eher typabhängige TTeaserausgabe bei Suchergebnissen, die eh in Planung ist. So pauschal aber wontfix und daher hier closed.
