### ISSUE TITLE
Darstellung Personenvisitenkarten

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#217]
Achtung, Kleinkram :baby_chick: , aber irgendwann mal anschauen:
Bei den Kontakten sollte die Adresse auch einrücken - am einfachsten, indem sie ein Icon aus dem Pool bekommt (welches?).
Das Icon vor der Abteilung ist auch nicht ganz richtig - das Haus steht für "home", wenn, dann kenn ich da so Wolkenkratzer oder Fabrikgebäude (naja, letzteres müssen wir nicht nehmen).

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6667615/8698e4b6-cbed-11e4-8665-786a608be527.PNG)
@wrcg @lagerlit

**Comment by xwolfde** [comment]
mach du mal ein Vorschlag für ein Icon. Hier ist die Auswahl: http://fontawesome.io/icons/

**Comment by xwolfde** [comment]
(Aber nicht das i nehmen, das wird für die Website verwendet, wie die auf den testportal bei meinen Pseodoeintrag sehen kannst)

**Comment by wrkb** [comment]
Nee, kein i (nicht gefunden, aber brauchmer nicht): Ich würde das Haus bei Abteilung durch den Taschenrechner ersetzen, der ein Bürohaus sein soll: http://fontawesome.io/icon/building/ - das bisherige Haus steht ja für "zuhause"/Heimadresse in den üblichen PIM-Tools.
Und bei der Adresse sind wir uns nicht ganz einig: Straße? http://fontawesome.io/icon/road/ oder besser den Böppel? http://fontawesome.io/icon/map-marker/ Oder den Zielpunkt http://fontawesome.io/icon/dot-circle-o/ Vielleicht ist der Böppel am besten, wobei so eine Pin-Nadel auch nicht schlecht wäre.
Nun haben wir mit Franzi ja die ultimative Icon-Designerin hier - arbeiten wir schon mit ein Fork von Fontawesome, wo sie contributen kann?

**Comment by xwolfde** [comment]
Habs auf building geändert.
Bei der Adresse würde ich erstmal nichts machen. Das sind jetzt eigentlich schon viel zu viel Icons.

(Woher soll ich wissen, ob Franzi einen eigenen Fork von Awesome pflegt. Wir benutzen den jedenfalls derzeit nicht, sondern das Original. Wenn Franzi den Fork immer pflegen will... ich dachte ihr habt keine Zeit?)

**Comment by wrkb** [comment]
Nein, die Frage war, ob ihr einen Fork nehmt oder das Original.
Franzi ist genau für solche Sachen da ;)

**Comment by wrkb** [comment]
Danke fürs Building, Adresse leuchtet auch ein. Machen wir den Optik-Kleinkram später (Umbrüche etc.), mir fällt eh nicht ein, was man da anders machen könnte. Sidebars sind immer schwierig.

**Comment by xwolfde** [comment]
Ich will die aktuelle Umsetzung im Theme eigentlich nicht mehr verändern, da wir hierzu wie ja gesagt ein neues Plugin bauen, welches das jetzige ersetzt. Das bedeutet "Code-Freeze" für das jetzige.

**Comment by wrkb** [comment]
Code-Freeze geht klar.
Wegen URL und Pflege frage ich Franzi. Sie hat da bestimmt was aus dem von euch mitgebracht :)
