### ISSUE TITLE
Menülänge begrenzt - zu kurz!

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#220]
[...Trolling-Selbstzensur ;)...]

Betroffenes Menu in fau.de: Struktur-Medfak
Symptom: Es lassen sich keine weiteren Elemente hinzufügen, nach dem Speichern sind dies nicht übernommen.
Screenshots: Zuerst das Menü, dann die Ausgabe (hier: Organigramm)

![menus_ _fau de_ _wordpress_-_2015-03-18_15 26 10](https://cloud.githubusercontent.com/assets/9445370/6710778/45b25c60-cd83-11e4-80c0-189272af202d.png)

![struktur-medfak_ _fau de_-_2015-03-18_15 28 00](https://cloud.githubusercontent.com/assets/9445370/6710800/6482b72a-cd83-11e4-8ce4-467324fe2f81.png)

**Comment by xwolfde** [comment]
Fehlbedingung des Anwenders. Trolling bitte woanders.

**Comment by wrkb** [comment]
Eine brauchbare Antwort brauche ich noch. Welcher der 2 Klicks (Seite auswählen, Hinzufügen) war falsch?

**Comment by wrkb** [comment]
Organigramm scheint als Lösung unbrauchbar, wir wählen eine andere Darstellungsform.
