### ISSUE TITLE
Backend: Bezeichnung ändern

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#225]
...das Drop-Down-Menü" Jede Übergeordnete" ist nicht verständlich bezeichnet, war aber umbenennbar, wenn ich nicht irre.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6870717/1f3005a2-d49e-11e4-93c2-92596b6d0063.PNG)

Kann da einfach "Seitenbaum" stehen?
Oder "Suche im Seitenbaum"?
Oder "Platz im Seitenbaum"?
Oder "In allen Ebenen"?

@endv02

**Comment by xwolfde** [comment]
Ist nicht im Theme. CMS-Plugin? @rvdforst

**Comment by endv02** [comment]
Kommt mit einem Update nächste Woche (oder so), ist im Plugin FAU-Settings a.k.a. CMS-Settings.

**Comment by rvdforst** [comment]
Ich habe "Jede Übergeordnete" als "Alle Seitenebenen" umbenannt.
Übrigens, das FAU-Plugin wurde vom FAU-Settings-Plugin ersetzt. Siehe https://gitlab.rrze.fau.de/rrze-webteam/fau-settings
