### ISSUE TITLE
Accordion überlagert Sidebar

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Theme#227]
Wenn man ein Accordion zur Darstellung nutzt, überlagert es die Sidebar. Siehe screenshot.
![bildschirmfoto 2015-03-31 um 09 05 30](https://cloud.githubusercontent.com/assets/11296947/6913885/9453f728-d785-11e4-8fa8-5d87fe42c41a.png)

**Comment by xwolfde** [comment]
Ja. Ist derzeit nicht lösbar. 
Die Benutzer müssen gelehrt bekommen, dass ein Accordion nur auf Seiten einzustellen sind, die über eine breite von zwei Spalten verfügen.

**Comment by xwolfde** [comment]
kleiner workaround gemacht. trotzdem gilt das obige: solche Accordions sind nur für 2 spaltige Inhaltsbereiche zu empfehlen.
