### ISSUE TITLE
Textumbruch beim Editieren ab erster Zeile Textbox

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Theme#228]
Wenn man in der ersten Zeile der Textbox in WP zu editieren anfängt, wird in der Anzeige die erste Textzeile umbrochen. 
Screenshot Textbox:
![bildschirmfoto 2015-03-31 um 09 12 07](https://cloud.githubusercontent.com/assets/11296947/6913976/75fd32a2-d786-11e4-9547-bea6ebcd992f.png)
Screenshot Ergebnis:
![bildschirmfoto 2015-03-31 um 09 12 43](https://cloud.githubusercontent.com/assets/11296947/6913985/7f793ac4-d786-11e4-9108-53f817140d45.png)
Fängt man erst in der zweiten Zeile an, wird nicht umbrochen.
Screenshot Textbox:
![bildschirmfoto 2015-03-31 um 09 13 26](https://cloud.githubusercontent.com/assets/11296947/6914005/a7200e54-d786-11e4-9f04-34c2a551ea28.png)
Screenshot Ergebnis:
![bildschirmfoto 2015-03-31 um 09 13 44](https://cloud.githubusercontent.com/assets/11296947/6914006/a9175992-d786-11e4-93a9-ed443e917b3a.png)
Wie kommt das? Kann man das eliminieren?

**Comment by xwolfde** [comment]
WTF?

**Comment by xwolfde** [comment]
Im Fakultätstheme gelöst. (Sidebar inline legte leere divs an)

**Comment by xwolfde** [comment]
fixed
