### ISSUE TITLE
Umwandlung Schreibweise Titel "Top-Event" in Beiträgen

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Theme#229]
Wenn ich einen Beitrag zum Top-Event mache, wird auf der Startseite der Titel korrekt angezeigt, solange ich im Beitrag keinen Titel eingebe:

Screenshot Beitragsedition:
![bildschirmfoto 2015-03-31 um 09 28 43](https://cloud.githubusercontent.com/assets/11296947/6914274/1975f606-d789-11e4-9512-e7d92c518f03.png)

Screenshot Startseite:
![bildschirmfoto 2015-03-31 um 09 32 09](https://cloud.githubusercontent.com/assets/11296947/6914325/7a217e6c-d789-11e4-9df4-62517e05d42b.png)

Gebe ich aber einen Titel ein, wird er in Kleinschreibung mit Bindestrichen umgewandelt und auch so auf der Startseite angezeigt.
Screenshot Eingabe Titel:
![bildschirmfoto 2015-03-31 um 09 29 55](https://cloud.githubusercontent.com/assets/11296947/6914295/4133b714-d789-11e4-9cb6-642e347bebe8.png)

Screenshot nach Aktualisierung:
![bildschirmfoto 2015-03-31 um 09 30 35](https://cloud.githubusercontent.com/assets/11296947/6914304/5294d7ea-d789-11e4-8e1f-066b7fef2d3f.png)

Screenshot von der Startseite nach Aktualisierung:
![bildschirmfoto 2015-03-31 um 09 31 18](https://cloud.githubusercontent.com/assets/11296947/6914311/61f4a94a-d789-11e4-9808-5cab14ed879a.png)

**Comment by xwolfde** [comment]
fixed
