### ISSUE TITLE
Bullets bei Listen

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Theme#231]
Wenn man eine Liste definiert, wird als Standardbullet ein Kreis eingefügt:
![bildschirmfoto 2015-03-31 um 10 26 39](https://cloud.githubusercontent.com/assets/11296947/6915014/c879e50c-d790-11e4-988b-8df6e79a1469.png)

Möchte man über das Menü den Bullet aber ändern, passiert das hier:

![bildschirmfoto 2015-03-31 um 10 27 30](https://cloud.githubusercontent.com/assets/11296947/6915021/dc369220-d790-11e4-9b7d-9974a6816650.png)

Wenn nun im Design vorgesehen ist, dass ungeordnete Listen unbedingt ein Bullet haben müssen (1), so ist die Auswahlmöglichkeit an dieser Stelle unpraktisch und sollte entfernt werden. 
(1) Diese Herangehensweise halte ich übrigens für diskussionswürdig, denn es gibt durchaus einige Anwendungsfälle, in denen gar keine Bullets erwünscht sind. Falls ich hier aber für die Diskussion des Problems zu spät kommen sollte, bitte ich den Einwand zu ignorieren.

**Comment by wrkb** [comment]
Das Editor-Menü (Datei-Bearbeiten-Einfügen etc.) wollen wir eigentlich gar nicht haben. Wir haben für fau.de/fau.eu den Rich-Text-Editor um alle unsinnigen Elemente gekürzt, das Editormenü bietet sie alle dennoch noch einmal an. Und damit auch die ollen Bullet points.
Der einzige Grund, warum das Menü bei uns noch genutzt wird: Der Punkt "Werkzeugleiste", über den man bequem Shortcode-Elemente einfügen kann. Den wollten wir den Autoren nicht wegnehmen und ihnen sagen: Nutzt sonst nicht das Editor-Menü. Blöd ist das natürlich.

Wen man also den Punkt "Werkzeugleiste" irgendwie in den TinyMCE integrieren könnte (nicht update-tauglich?) oder anderswo unterbringt, dann kann das Editormenü weg. Kommt uns entgegen!

Was die Fälle ohne Bulletpoint angeht: Wir haben irgendwann mit weiteren Styles aufgehört - dem Zeitplan beim Relaunch zuliebe. Wir haben daher keine schönen Linklisten und keine schönen Einschubkästen, die das Arbeiten mit Text vereinfachen würden. Bullet points werden so häufig missbraucht, ohne dass echte Listen da sind. Konkretes Beispiel kann ich ggf. noch liefern.

Man könnte nun also noch die Einrückung nutzen, wenn keine Bullet points gewünscht sind - wir wissen aber gar nicht, ob die gutes CSS darstellen und genutzt werden sollten? Oder es gibt doch noch einmal neue Styles für abgesetzte Aufzählungen oder Textabsätze ohne bullets.

@wrcg

**Comment by wrkb** [comment]
Unsere TinyMCE-Konfiguration.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6915380/ba968e1a-d793-11e4-95a8-34a9b3d56c70.PNG)

**Comment by xwolfde** [comment]
Hm... also bei fau.de geht es tatsächlich nicht, dort kriege ich keine Auswahlliste für den Bulletpointtype.
(Anmerkung: Es geht nicht um die Werkzeugleiste von TinyMCE, sondern um die nativen WP-Funktionen ohne Spezialplugins. Welches Plugin bei fau.de jetzt die Zusatzfunktion des Defaulteditors an der Stelle einschränkt, weiss ich nicht.).

Was aber auch heisst, daß dort gar keine Liste ohne Kreis geht; Was wahrscheinlich früher oder später Probleme machen wird, mann man eine Liste braucht, die eben was anderes hat.
Für die Fakultäten möchte ich mir erwartbare Debatten darüber lieber ersparen. Daher bauen wir dann halt dort entsprechendes ein. Bei fau.de dann nicht :)

**Comment by xwolfde** [comment]
Also:
1. Wenn TinyMCE nicht installiert wurde und WP-Default verwendet wird, gibt es die Option zur Auswahl der Liststyles nicht.
2. Wenn TinyMCE installiert wurde und am Default nichts geändert wurde, ist dort der Haken gesetzt, daß die List Style Options angezeigt werden.
3. Bei fau.de wurde der Haken abgeschaltet.

Problem auf alle Fälle:
Es gibt Situationen in denen eigene List-Style Optionen sinnvoll sind. Insbesondere bei nummerischen Aufzählungen. So ist die Untergliederung auf zweiter Ebene bei nummerischer Aufzählung oft unerwünscht oder als falsch angesehen, wenn es normal wieder Zahlen sind. 
 Korrekt bspw. ist in solchen Fällen:
      1.  Erster Punkt
          a) Unterpunkt 1a)
          b)  Unterpunkt 1b)
               
Weiterhin gibt es Fälle, wo man definitiv andere Nummererungsformen verwenden muss. Bspw. bei Richtlinien und Gesetzestexten. Dort fängt die Form mit §n an.

Folge:
Wir müssen unabhängig von der Nutzung des Editors das CSS ergänzen um Typdefinitionen. Sprich: Wenn von dem Default abgewichen werden soll, dann muss dies auch möglich sein.

Weitere Meinungen hierzu?

**Comment by wrkb** [comment]
Wow, das ist mal detailliert... Gesetzestexte? Nichtmal wir haben das bei unseren Satzungen... Aber wenn der Bedarf da ist, warum nicht.

TinyMCE (oder irgendein alternativer Editor) ist also nicht als Standardlösung vorgesehen, entnehme ich deinem Post. Ich finde es immer noch wichtig, dass so ein Editor flexibel anpassbar ist, der TinyMCE tuts einigermaßen, aber z.B. die Shortcodes (Werkzeugmenü) oder CSS-Formatierungen (class attention) sind halt nicht untergebracht.

Ist es irgendwie denkbar, den Tiny wegzuschmeißen und die möglichen Formatierungen selbst zu bestimmen? FAU-Plugin? Also z.B. ausgehend von unserer Konfiguration plus erwartbare Wünsche Fakultäten plus obige Wünsche plus Sonderzeichen Anführungszeichen literarisch und Gedankenstrich?

Numerische Aufzählungen mit Unterpunkten sind so eine Sache: Ist denn die Strukturierung innerhalb der Aufzählung ohne Umschalten in den Text-Modus (Code statt WYSIWYG) problemlos möglich - gerade nach Copy/Paste? Nach meiner Erfahrung sind Unterlistenpunkte (bullet oder numerisch) für WYSIWYG-Nutzer ohne Code-Kenntnisse unbedienbar, es hakt irgendwann (Sackgasse). Sowas sollte nicht auf Webseiten, sondern in PDFs oder Wikis (persönliche Meinung).

Generell zu Abweichungen vom Default: Was ist default? Das betrifft die leidige Frage Web-CD-Manual (da müssen wir sicher auch liefern). Wieviel ZUV soll ins Web-CD? Wir haben uns ja schon Gedanken gemacht um einen gemeinsamen Nenner. Wer entscheidet, was eine Abweichung ist?
--> Jour fixe? Mai?

Soviel von mir erstmal.

**Comment by xwolfde** [comment]
Ich würde sagen: Bei FAU.de nicht relevant, da so entschieden, das es nur eine Ebene gibt. Bei Fakultäten trotzdem ggf. Sublisten nachbauen und Listdarstellung daher dort korrigieren.
Hier daher closed.
