### ISSUE TITLE
Bildergalerien (Slider): Bitte Text unterm Bild nicht zentrieren

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#232]
...sondern linksbündig.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/6939616/cba93492-d86e-11e4-92fe-3b574f59ed3e.PNG)

**Comment by xwolfde** [comment]
Bin ich dagegen, sieht doch blöd aus.

**Comment by wrkb** [comment]
Ich bin nicht sicher, ob wir uns richtig verstehen. (1. April? :) ) Zentrierter Text geht gar nicht, der ist nicht richtig lesbar und es gibt keine seriösen Bilderstrecken mit zentrierten Text im Web. Also wir wollen nicht zentriert, sondern linksbündig, links-nach-rechts-lesen wie es sich gehört etc.
Zentrierter Text kommt nur aus Word für die Überschriftengestaltung oder aus Office-Tabellen.

**Comment by endv02** [comment]
Apropos 1. April: Schon mal rechtsbündig in Betracht gezogen?

**Comment by wrkb** [comment]
Jetzt bin ich raus.

**Comment by xwolfde** [comment]
Ich stelle es auf Vorschlag. Das ist kein Fehler, sondern war so von der AGentur gemacht. Also war es wohl gewollt und quasi abgenommen.

Ansonsten: Nein, mach mal bitte etwas Photoshop, Karsten und schau dir an, wie das Beispiel aussieht, wenn der Text linksbündig ist. Die Bildergalerie darunter ist nämlich mittig angeordnet unter dem aktiven Bild und auch der Link zum vergrößern ist das. 
Es sieht wirklich blöd aus.

**Comment by wrkb** [comment]
Ja okay, der Link rutscht mit rüber, das hatte ich nicht bedacht. Wir können das ja mal probieren (Developer Tools im Browser vielleicht), dann sehen wir selbst die Problemstellen und was wir übersehen haben könnten. Ich setz das mal auf unsere Agenda auch.

Es muss wohl als abgenommen gelten (wenn sich in den Updates nichts geändert hat) aber natürlich war das so nicht gedacht und jetzt hammer den Salat. 
Es ist nicht wahnsinnig schlimm, aber optimal auch nicht. Wir finden früher oder später sicher eine Lösung.
@wrcg

**Comment by xwolfde** [comment]
Ja, schaut mal. Ggf. können wir ja auch mal die Anke Vogler fragen, die als gelernte Diplomdesignerin auch eine Empfehlung geben könnte.
Momentan haben wir aber wirklich wichtigere Todos.
