### ISSUE TITLE
Fehler im Template "Suche Nachrichten"

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Theme#235]
Im Template "Suche Nachrichten" gibt es bei der Anzeige einen fatalen Fehler. Screenshots anbei.
![bildschirmfoto 2015-04-08 um 14 55 36](https://cloud.githubusercontent.com/assets/11296947/7045554/6f1cb8ca-ddff-11e4-8512-f3456e44caa2.png)
![bildschirmfoto 2015-04-08 um 14 56 39](https://cloud.githubusercontent.com/assets/11296947/7045558/7e0f9de8-ddff-11e4-88d1-1cc29fc454d0.png)

**Comment by xwolfde** [comment]
fixed
