### ISSUE TITLE
Fehler im Template "Suche Personen"

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Theme#236]
Bei Auswahl des Templates "Suche Personen" gibt es auch einen fatalen Fehler. Screenshots anbei.
![bildschirmfoto 2015-04-08 um 14 58 29](https://cloud.githubusercontent.com/assets/11296947/7045612/fa718342-ddff-11e4-8b67-f7a3f57a2794.png)
![bildschirmfoto 2015-04-08 um 14 58 57](https://cloud.githubusercontent.com/assets/11296947/7045613/fc2d2088-ddff-11e4-96d7-d744a99ab2e0.png)

**Comment by xwolfde** [comment]
fixed
