### ISSUE TITLE
Fehler im Template "Suche Veranstaltungen"

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Theme#237]
Bei Auswahl des Templates "Suche Veranstaltungen" ebenfalls fataler Felher. Screenshots anbei.
![bildschirmfoto 2015-04-08 um 15 01 31](https://cloud.githubusercontent.com/assets/11296947/7045654/5516ed78-de00-11e4-9179-aec316199455.png)
![bildschirmfoto 2015-04-08 um 15 01 54](https://cloud.githubusercontent.com/assets/11296947/7045655/5695bc74-de00-11e4-835c-53f70e4d9cf0.png)

**Comment by xwolfde** [comment]
fixed
