### ISSUE TITLE
Personenanzeige in Sidebar

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Theme#242]
Issue von cibsell war bei fau-person falsch, kommt durch die Personenanzeige im Theme:

Hallo,

wenn ich bei Personen eine Person anlege und unter "Eigenschaften" die Postadresse angebe, dann erscheint diese Adresse in der Sidebar ohne Zeilenumbruch, siehe Screenshot. Gebe ich br ein, wird der Code in Text umgewandelt und kein Zeilenumbruch gemacht.

![fc900eac-df83-11e4-88bb-2fe0d543f767](https://cloud.githubusercontent.com/assets/5851793/7087832/c5b520a0-df8f-11e4-841d-c6bc09e8d8d3.png)

**Comment by cibsell** [comment]
Ist aber im Phil-Theme, nicht im FAU-Theme...

**Comment by endv02** [comment]
Hab’s da auch nochmal dazugetan, ist die gleiche Funktionalität, danke!

--
Karin Kimpan, Ausbildung & Information
Friedrich-Alexander-Universität Erlangen-Nürnberg
Regionales Rechenzentrum Erlangen (RRZE)
Martensstraße 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27808
karin.kimpan@fau.de<mailto:karin.kimpan@fau.de>
www.rrze.fau.de


Von: cibsell <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Theme <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 10. April 2015 14:47
An: RRZE-Webteam/FAU-Theme <FAU-Theme@noreply.github.com<mailto:FAU-Theme@noreply.github.com>>
Cc: Karin Kimpan <karin.kimpan@fau.de<mailto:karin.kimpan@fau.de>>
Betreff: Re: [FAU-Theme] Personenanzeige in Sidebar (#242)


Ist aber im Phil-Theme, nicht im FAU-Theme...

**Comment by xwolfde** [comment]
bei dem Fakultaätstheme gelöst. FAU muss warten :)

**Comment by xwolfde** [comment]
sollte durch zentrales neues plugin gelöst sein.
