### ISSUE TITLE
Abhängigkeiten, Readme anpassen

### ISSUE THREAD

**Issue by zfldev** [RRZE-Webteam/FAU-Theme#249]
Zunächst Danke für eure Tolle Arbeit und dass diese hier öffentlich auf Git ist!

Da ihr das FAU-Plugin nicht mehr weiterentwickelt und das wichtigste in FAU-Person ausgelagert habt gehe ich mal davon, dass das FAU-Plugin kein Foraussetzung für dieses Theme ist oder? Genauso wie ihr wohl auch die Abhängikeiten zum ACF entfernt habt.

**Comment by xwolfde** [comment]
So ist es.
Personenverwaltung ist in fau-person. 
Und als Vorlage für Fakultätsthemes sollte in Zukunft auch besser nicht mehr FAU-Theme verwendet werden sondern eher FAU-Philfak. Bei FAU-Theem bleiben leider noch ein paar Eigenheiten bestehen, die niemand ausser die ZUV braucht.

**Comment by zfldev** [comment]
Super! Vielen Lieben Dank!
