### ISSUE TITLE
Textfloating neben Bildern ohne Beschriftung

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#250]
Hallo,

entweder ist das der eine nötige Workaround, den Wolfgang mal erwähnte in Sachen Bilder und den ich vergass. Oder wir haben hier eine Besonderheit in der Darstellung - ich will es nicht gleich Bug nennen.

Das Problem statt von https://www.fau.de/universitaet/das-ist-die-fau/publikationen/, ist aktuell nur im Screen sichtbar, da auf der Seite erstmal umgangen.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7298972/679c59fe-e9d3-11e4-991b-5a3ab158f4d7.PNG)

- Hat ein Bild keine Beschriftung / [caption], wird der Text vertikal zentriert, hat keinen Abstand mehr zum Bild und es sieht schlecht aus. (Leerzeichen als fauler Workaround klappt nicht)
- Wir wollen hier eigentlich keine Bildunterschrift, weil sie schlicht unnötig ist (obsoleter Content, siehe Überschrift) und wir sie auch rechtlich nicht brauchen - es sind unsere eigenen Flyer.

In der Hummel unter Test --> Test CSS-Lauf habe ich eine Kopie der Seite angelegt, gleiches Verhalten.

Wir hätten das gern anders. Geht das?

@lagerlit

**Comment by xwolfde** [comment]
Es wurde offensichtlich absichtlich gemacht, da folgender Code im CSS vorhanden ist, der eine Links/Rechts-Positionierung beim Bild deaktiviert:
.page-template-page-subnav #content .span8 img.alignleft, .page-template-page-subnav #content .span8 img.alignright     {   float: none;
    height: auto;
    margin-right: 0;
    max-width: 350px;
}

Bei dem obigen Beispiel habt ihr aber kein alignleft genommen, sondern wohl "full-size".In dem Fall ist das Verhalten wohl richtig/gewollt?
Ihr hättet alignleft nehmen müssen. Aber das macht rechts dann nur weiße Fläche wegen obigen absichtlichen Code.
Ich kann das deaktivieren, da ich aber die Gründe nicht kenne, die dem Code zugrunde liegen, kann es sein,. daß es woanders dann knrischt.

**Comment by xwolfde** [comment]
Ok, weiter gebohrt: Das wurde gemacht, weil für den Fall, wenn die Sidebar vorhanden ist & die Page eine Subnav hat & die Bildposition verändert wird, die Sidebar nach verschoben wird.

Ein möglicher Workaround dafür ist das wegnehmen des clear-Befehls. Die mitte Anordnung des textes ist  aber darin begründet, daß der Text middle aligned ist. das kann man ändern.
Allerdings kommt hier ein anders "Problem" zu tragen. Ihr habt dort "size-full" für das Bild genommen und nicht alignleft. Size-full war nicht definiert - MR hat das wohl mit aligncenter verwechselt, was definiert wurde.

tl;dr: Lösung 1: verwendet korrekt align-left und nicht "keine Ausrichtung" und wartet auf das Update, das ihr auf test4 testen könnt.

**Comment by wrkb** [comment]
Danke Wolfgang für die Details! :+1:  Wir schauen nach dem Update noch mal und auf die Ausrichtung müssen wir eh noch mal achten.
