### ISSUE TITLE
Banner/Werbung unter Inhalt wird nicht angezeigt

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#251]
Was könnte ich falsch gemacht haben?

Backend:

![backend](https://cloud.githubusercontent.com/assets/9445370/7316892/570b25ae-ea7b-11e4-8052-ebbcc43b4289.PNG)

Backend 2, an Seite Studium:

![backend2](https://cloud.githubusercontent.com/assets/9445370/7316908/778b4958-ea7b-11e4-90eb-4525e74b8297.PNG)

Wunsch im Frontend (ob das gut aussieht, ist eine andere Frage, müssen wir testen):

![frontend](https://cloud.githubusercontent.com/assets/9445370/7316887/3bf441a6-ea7b-11e4-9eed-871c21f66e93.PNG)

@xwolfde

**Comment by xwolfde** [comment]
Bedienerfehler.
Guck nochmal genauer hin, was du nicht eingegeben hast.

**Comment by wrkb** [comment]
Wie jetzt - Ratespielchen? Was soll das denn??

Wenn du die ID meinst: Eingabe von 0 oder eben willkürliche Werte über 0 (1, 3) hatte ich bereits, das Feld leert sich nach dem Aktualisieren. Alle anderen Felder kommen laut Hilfetexten nicht in Frage für meinen Fall - so also fehlt etwas?

**Comment by wrkb** [comment]
Irgendwelche Updates hierzu?

**Comment by xwolfde** [comment]
Ist nicht relevant für Fakultätsthemes, daher müsst ihr halt warten.

**Comment by wrkb** [comment]
Okay, schieben wir. Ist nur ein wenig schade, da wir diverse schöne Banner-Gründe haben (Fotowettbewerb, FAU-Blog-Werbung). Ich kann mir auch gut vorstellen, dass die Fakultäten das durchaus nutzen möchten (Marketing diverser Veranstaltungen etc.). Aber das wird anderswo entschieden.

**Comment by xwolfde** [comment]
Entschuldigung, du ´hattest recht.
Problem liegt nur bei fau.de, da die Ursache in den alten ACF-Geraffel lag, welche nur bei euch vorhanden waren.
Im nächsten Update und auf test4 behoben.
