### ISSUE TITLE
Anzeige Personenvisitenkarte

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#252]
Bei der Anzeige der Personenvisitenkarten war bisher der Teil des Freitextfeldes rechts angezeigt. Heute haben wir Änderungen der Daten vorgenommen und die Anzeige des Freitextfeldes rutscht nach unten... Bitte korrigieren :-)

Beispielseite: https://www.fau.de/studium/vor-dem-studium/studienberatung/einzelberatung/

![2015-04-27 16_25_32-einzelberatung fau de](https://cloud.githubusercontent.com/assets/9526974/7349529/164148d8-ecfa-11e4-811c-e8882141e74e.png)

**Comment by xwolfde** [comment]
fixed im nächsten update, wenn es getestet wurde.
