### ISSUE TITLE
Bilder werden unscharf dargestellt wenn...

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#253]
...man sie in einer vordefinierten Größe in eine Seite einfügt im Content und dann per "Individuelle Größe" im Bearbeiten-Dialog des Bildes vergrößert, wird das Bild unscharf. Da läuft irgendwas schief.

Workaround bisher: Bild im Dialog auf Originalgröße stellen. Aktualisieren. Dann die gewünschte individuelle Größe einstellen.

Zusammenfassung: Erst klein, dann inviduell größer --> unscharf. Erst groß, dann inviduell kleiner: Scharf.

**Comment by xwolfde** [comment]
HÄ?! Das ist doch normal und logisch so? Wie soll denn ein kleines Bild, welches vergrößert wird, schärfer werden?

**Comment by wrkb** [comment]
Ich konnte gestern in der Eile keine Screenshots machen, liefere ich bei Bedarf aber noch nach. 

Das Bild ist 2048x.... Pixel groß, also groß genug. Es geht nicht um Interpolieren.
Der Fehler hängt davon ab, welche Größe (die von euch definierten Maßvorgaben) man im Dialog auswählt und welche danach.

Sprich: Wenn man sich für 300 Pixel entscheidet und später das Bild erneut ändert und mit 450 Pixel individuellem Maß einbindet (Motto: erstmal gucken in der Vorschau, wie es mit 300 Pixeln aussieht) - dann ist es unscharf. Die Originalgröße ist ein Vielfaches des Ganzes.

**Comment by wrkb** [comment]
In der Testhummel ist eine neue Seite mit dem Problem zu finden - Bild-Test-Schärfe heißt sie. Das Bild wurde aus der Datenbank ausgewählt, mit 300px eingebunden. Dann erneut auf 400px individuell geändert. Dann nochmal auf 600px.

**Comment by xwolfde** [comment]
ich vermute, ich verstehe langsam was du meinst... Aber auch dann ists ein Bedienerfehler und damit ein Schulungsproblem.

Du hast im WYSIWYG-Editor ein Bild eingebunden. Dabei hast du die Größe auf 300 Pixel oder so genommen. Im Editor hast du es danach dann mit der Maus größer gezogen.

War es so?

**Comment by wrkb** [comment]
Nein, immer über den Einstellungsdialog (Klick aufs Bild - Edit-Symbol) Wert dort geändert.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7395169/8affab34-ee98-11e4-8b0c-13c53db5b453.PNG)

**Comment by xwolfde** [comment]
Die wichtigere Frage ist, WARUM tust du das? Die Bildgrößen sind fest definiert, damit man eben keine individuellen Größen verwendet. Die Bildgrößen in Artikeln und Seiten sind vom Design festgelegt. Jegliche manuelle oder individuelle Änderung ist eigentlich etwas, was niemand machen sollte.

**Comment by wrkb** [comment]
Das leuchtet natürlich ein. Der aktuelle Fall betraf eine landing page, auf der wir die volle Gestaltungsfreiheit haben wollen (Standardtemplate), naja, soweit das eben geht.

Wir müssen uns da einfach noch mal eure Größendefinitionen verinnerlichen (geschickt habt ihr die Liste ja schon). Mit der Agentur hatten wir versucht, sinnvolle Größen für SEiten (nicht: Posts) festzulegen, waren dabei stehen geblieben, dass wir sie eigentlich nur ganz oben volle Breite (mit oder ohne Sidebar) einbinden können. Ich weiß nicht, wie eure Formate dazu noch passen und ich weiß nicht, ob wir da eingebunden waren in die Formatentwicklung für Seiten (nach all unseren Frage würde ich sagen: nein). Was nur heißt, dass wir uns bald mal damit beschäftigen müssen und gucken, was überhaupt geht. 

Bei Postings/Blogbeiträgen haben wir ja ein festes Prozedere, da spielen wir nicht an den Bildgrößen rum.

Kann also erstmal geschlossen bleiben hier, für unsere landing pages funktioniert der Workaround aktuell. Siehe https://fau.de/fotowettbewerb
