### ISSUE TITLE
Sidebar: Titel bei Kontakten über jedem Kontakt - gewollt?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#254]
...ich glaube, da hatten wir schon mal drüber gesprochen. Wenn man mehrere Kontakte auswählt, wird über jedem der Titel angezeigt (wir nehmen immer "Kontakt"). Das ist eigentlich redundant - war das so gewollt? Ist zumindest für das neue Plugin eine relevante Frage, aktuell ist die Prio nicht hoch. Es fiel aber auf. Screenshot ist von einer Schulungs-Testseite, mehr als 2 Kontakte geben wir eigentlich auch nie an (zu lang).

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7373865/46e49b0e-edcf-11e4-87fa-c8f9aeba6390.PNG)

Geben wir keinen Titel an, erscheint nirgends ein Titel. Aktuell wird er also verfielfältigt.

**Comment by xwolfde** [comment]
Stimmt

**Comment by xwolfde** [comment]
Im nächsten Update Und auf test4 behoben
