### ISSUE TITLE
FAU-Theme Shortcode-Ausgabe Downloads

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Theme#255]
https://www.fau.de/international/wege-ins-ausland/downloads-und-formulare-wia/downloads-wege-ins-ausland/
Es fehlt hier bei Downloads womöglich eine Ausgabe, falls ein Ordner leer ist. Der Nutzer denkt hier, es liegt ein Fehler vor, da die "Kategorien" keine Inhalte (=Downloads) liefern.

Man wünscht sich die Ausgabe: "Derzeit liegen keine Inhalte vor." 

Man müsste dazu wohl einmal die function fau_downloads( $atts, $content = null) prüfen.
![bildschirmfoto 2015-04-30 um 10 42 16](https://cloud.githubusercontent.com/assets/11868989/7409322/a35aaba6-ef25-11e4-9504-e419412af767.png)

**Comment by wrkb** [comment]
Danke Steffi für den Hinweis. Ich glaube, das brauchen wir tatsächlich, ich informiere auch mal Cathrin, die die Funktion hier zum ersten Mal eingesetzt hat. @wrcg

**Comment by xwolfde** [comment]
Die Download-Implementierung ist großer verwirrender Murks. Das müssen wir für die Fakultäten besser machen. So wie bei fau.de gelöst kann man das niemand zumuten....
Bei den Fakultäten werf ich den Code raus. Bei dem FAU-Theme bleibt es drin; Ob wir das gemeldete verbessern können muss sich zeigen.

**Comment by wrkb** [comment]
Verbesserungen wären natürlich schön, aber: Der Status quo ist das, was wir der wenigen verfügbaren Zeit noch umsetzen konnten (das wurde am Schluss entwickelt) und für uns hatte das gepasst bzw. wäre die Frage, was man stattdessen macht.
Leere Kategorien sollten ansonsten die Ausnahme sein und eigentlich kann man sie auch entfernen, wenn nicht gefüllt. Wir müssen hier auch mal ein paar Erfahrungen sammeln auf fau.de.

**Comment by xwolfde** [comment]
Ok, dann für FAU-Theme geschlossen. eigenes Plugin is coming ahead later.
