### ISSUE TITLE
doppeltes Sidebar-Widget auf fau.eu

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#256]
gerade gesehen: auf der Seite https://www.fau.eu/international/international-applicants/bachelors-masters-state-examinations/admission-requirements/international-qualifications/ werden zwei Sidebar-Widgets angezeigt, einmal das alte und einmal das neue...

(ist mir letzte Woche auch schon mal an einer Seite passiert, da konnte ich es mit Cache-Löschen aber entfernen...)

![2015-05-04 12_05_57-edit page fau eu wordpress](https://cloud.githubusercontent.com/assets/9526974/7451850/f82ce67a-f255-11e4-8d73-b2494ebe8746.png)

**Comment by xwolfde** [comment]
Ihr hattet da noch ACF aktiv. Was hat das mit dem Theme zu tun?
Bitte immer auch erstmal selbst prüfen,,,

**Comment by wrkb** [comment]
Seit wann dürfen wir denn Plugins deinstallieren? ACF ist doch ein Plugin? Und da das Theme ohne ACF läuft eigentlich, ist es schon Theme-relevant...
Habe nachgeschaut: ACF ist längst deaktiviert für fau.eu, mehr kann ich nicht tun. Netzwerkweit scheint das Ding aber noch im System rumzuhängen, oder?

**Comment by rvdforst** [comment]
Wenn ein Plugin deaktiviert ist, dann ist dieses Plugin nicht mehr funktionsfähig, obwohl die entsprechenden Dateien noch vorhanden sind. Bisher scheint das Theme ohne das ACF richtig zu funktionieren. Sprich ich kann jederzeit das Ding einfach vom System (WP) entfernen.

**Comment by wrkb** [comment]
Irgendwas scheint ja zu hängen. Ich ging davon aus, dass ACF schon längst komplett entfernt ist aus dem Netzwerk. Es hieß bei einem der letzten Updates mal, dass es problemlos entfernt werden kann - prüfen kann ich das hier natürlich nicht.

**Comment by xwolfde** [comment]
Ich hab es gestern deaktiviert. Deswegen hab ich den Bug geclosed.
Ihr dürft als lokale Admins Plugins deaktivieren oder aktivieren.  Installieren ist was anderes. das dürft ihr nicht. (Das solltet ihr eigentlich wissen, wenn ihr Kurse macht).


Was genau meinst du nun mit "irgendwas scheint zu hängen"? Jetzt konkret? oder ist das nur die Verwirrung hier? (ich gehe von letzterem aus)

**Comment by wrkb** [comment]
Wenn wir noch eine Sidebar haben, die offenbar noch auf ACF fußt, obwohl wir das nicht einsetzen und es heißt, das ACF wäre weg - dann stimmt ja irgendetwas nicht. Wenn du ACF gelöscht hast (nun endgültig) dann ist ja alles i.O. Ich habe nur auf Rolfs Post reagiert, ich weiß nicht, wer wann wo ACF nicht entfernt hat. Ich tippe also auf Verwirrung und vier überflüssige Posts hier :)

(Dass wir Plugins nicht installieren dürfen, weiß ich doch - schrieb oben. Geschult wird das nicht - Autoren haben damit doch gar nichts zu tun.)

Over and out,

K
