### ISSUE TITLE
Medien ersetzen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#257]
letzte Woche bei den Schulungen funktionierte es, wenn mein Name als Autor eines Dokumentes angezeigt war, dass ein anderer Autor (nur mit Autorenrechten) dieses Dokument mit dem Link "Datei ersetzen" aktualisierte. Heute war ich bei einem Kollegen und wir wollten mit seinem Account ein Dokument ersetzen. Er bekam die Fehlermeldung "nicht genügend Rechte". Könntest du das bitte wieder korrigieren.

**Comment by xwolfde** [comment]
Hä?

**Comment by wrkb** [comment]
Es geht um das Plugin zum Ersetzen von Medien in der DB.
![ersetzen](https://cloud.githubusercontent.com/assets/9445370/7469406/7f6aa63c-f313-11e4-902a-0e808fc447a1.jpg)

Das erlaubte in der Schulung vor aller Augen mit dem lokalen Schulungs-Account "autor" (Autorenrechte), dass wir als Autor jedes Dokument ersetzen, auch solche, die wir nicht selbst hochgeladen haben.  Im Screenshot ist das der Fall. Nach dem Ersetzen waren wir der neue Besitzer des Dokuments/Bildes. Das funktioniert aber scheinbar nicht für die Kollegen mit IdM-Account und Autorenrechten - warum weiß ich nicht.

Haben wir also Quatsch geschult? Rechnen konnten wir damit nicht so richtig. Das hieße, dass immer nur der Ersteller eines Dokuments dieses ändern kann, was natürlich ungünstiger ist.
Dass die Medien-DB nicht direkt ans Rollensystem gekoppelt ist, wissen wir, aber vielleicht kann man ja noch für alle ermöglichen, was der lokale "autor" ja scheinbar darf?

**Comment by wrkb** [comment]
Wann könnt ihr das prüfen? Ich mag nicht drängeln, aber da die Leute aktuell gegen die Wand laufen und nichts von dem Problem wissen, muss ich bis morgen früh eine Mail rausschicken an alle Autoren, wenn wir das nicht zeitnah bearbeiten können.

**Comment by rvdforst** [comment]
Das Problem kommt vom Plugin "Enable Media Replace" (third-party). Dieses Plugin nutzt die Funktion current_user_can('upload_files') außerhalb des "plugins_loaded"-Hook. Sprich wenn ein anderes Plugin (z.B. CMS-Workflow) sehr abhängig vom Rollensystem ist, dann hat dieses keine Möglichkeit die capabilities einer Rolle zu beeinflussen. Also das Plugin "Enable Media Replace" muss gefixt werden.

**Comment by rvdforst** [comment]
...oder ersetzt werden.

**Comment by rvdforst** [comment]
tja, wer macht das? medienreaktor oder... Ich?

**Comment by wrkb** [comment]
Zum Verständnis: Es gibt für das Plugin also möglicherweise einen Unterschied zwischen IdM-Autoren und lokalen Autoren?

**Comment by rvdforst** [comment]
Nein. Warum das Problem jetzt aufgetaucht hat, hängt von der Reihenfolge ab, wie die Plugins von WP hochgeladen wurden. Und das ändert sich ab und zu.

**Comment by xwolfde** [comment]
Und wie lösen wir das Problem jetzt?

**Comment by rvdforst** [comment]
Ich bin dran. Es kann einige Tage dauern...

**Comment by wrkb** [comment]
Danke fürs Update. Ich informiere unsere Autoren, wir springen ein als Webredaktion und kommen damit erst einmal klar.

**Comment by rvdforst** [comment]
Um das Problem zu überwinden habe ich das Workflow-Plugin erweitert. Un zwar, ab sofort die Medien werden auch die Autoren- und Benutzergruppen-Funktionen unterstützen. Das heißt, die Co-Autoren der Medien können sowohl die Metadaten als auch die entsprechenden Dateien ersetzen. Neu ist die "Autoren"-Spalte (Co-Autoren) der Medientabelle.

**Comment by wrcg** [comment]
Danke, das scheint zu funktionieren. 
Allerdings ist jetzt die Möglichkeit der Auswahl nach Kategorien (sowohl Dokument- als auch Medienkategorie) kaputt gegangen. Sobald ich mir die Einträge der Medienbibliothek nach einer Kategorie anzeigen lassen will, erscheint immer die Meldung "Keine Medienanhänge gefunden." :-(
Bitte wieder korrigieren.

**Comment by rvdforst** [comment]
Oh sorry! Ich habe es behoben.
