### ISSUE TITLE
Personenvisitenkarten - neue Maske

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#259]
weil es mir gerade wieder eingefallen ist bei dem Mailverkehr von gestern...
es gibt einen kleinen Schönheitsfehler in der Maske :-)
Der Titel beim FAX-Nummern-Feld heißt "Telefon" - bitte bei Gelegenheit korrigieren.

**Comment by xwolfde** [comment]
Ist in fau-Settings, oder @rvdforst ? Änderst du da das bitte?

**Comment by rvdforst** [comment]
Ist erledigt. Siehe https://gitlab.rrze.fau.de/rrze-webteam/fau-settings
