### ISSUE TITLE
Backend-Sidebar-Linkbox: Link-wählen-Feld löst keine Aktion aus, Seite nicht mehr scrollbar mit Maus

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#260]
...was bei einem ausstehenden Review bedeutet, dass man umfangreichere Änderungen an der Sidebar verwerfen muss (wegen F5) oder den Review erstmal veröffentlichen. Neuladen der Seite behebt das Problem.

Voraus ging dem Fehler das Hin- und Herkopieren von Linktiteln aus den einzelnen Feldern der Linkbox zum Ändern der Reihenfolge (über beide Linkboxen hinweg). Dann, beim zweiten oder dritten Klick auf "Link auswählen" öffnet sich der Link-Assistent nicht mehr (zum Auswählen vorhandener Seiten) und man kann die Seite nicht mehr mit der Maus scrollen. Trat auch schon in der Schulung auf in v1.3.

Könnt ihr das so schon nachvollziehen? Screenshots bringen hier nichts, falls noch Fragen offen sind, muss ich das nochmal provozieren zum Reproduzieren.

**Comment by wrkb** [comment]
...und es scheint, als würden die Änderungen auch nach dem Veröffentlichen des Reviews verworfen sein, auch wenn ich mit Bild auf nach oben scrolle.

**Comment by wrkb** [comment]
noch etwas: Beim Klicken auf "Wähle Link" und Auswahl einer vorhandenen Seite und Schließen des Dialogs springt man ganz nach oben in der Seite und muss wieder zur Linkbox hinunterscrollen. Das ist nicht schön.

**Comment by xwolfde** [comment]
Kapiere nicht was du meinst. Herkommen, zeigen.

**Comment by wrkb** [comment]
Ja, wir beoachten das oder screencasten oder kommen vorbei.
