### ISSUE TITLE
Einfacher Menü-Edit auf Startseite killt Verknüpfung zu Theme locations

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#261]
Ich habe das Menü FAU bearbeitet in fau.eu, das mit der theme location Quicklinks 2 verknüpft war. Ich habe lediglich zwei Einträge von den 4 oder 5 entfernt. Nach dem Bearbeiten...
...war die Verknüpfung defekt
...das Menü enthielt nur noch die zwei gelöschten (!) Einträge, die anderen waren weg
...die theme location Quicklings 2 sah im Frontend so aus, wie im langen Screen unten. Ist das die gewünschte Fallbacklösung? 

Ich habe das Menü neu mit der theme location verknüpft.

Die Menüs wurden vor längerer Zeit gebaut - also vor so einigen Updates.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7492828/1c5147c4-f3fc-11e4-9b53-41fce4e12bac.PNG)
![friedrich-alexander-universitat_erlangen-nurnberg_ _fau eu_-_2015-05-06_13 20 16](https://cloud.githubusercontent.com/assets/9445370/7492832/22155600-f3fc-11e4-976f-6c11204dc21e.png)

**Comment by xwolfde** [comment]
Ich kann das nicht nachvollziehen.
Ich vermute, du hast aus versehen die Verknpüfung zum menü bei Quicklinks-Location entfern, so daß dort dann kein definiertes menü zugeordnet war. In dem Fall und nur bei euren Theme wird dann als Fallback das automatisierte Seitenmenü als Fallback genommen. Das sind dann alle Seiten. Und dementsprecht weit geht es dann halt nach unten.

tl;dr: Bedienerfehler.

**Comment by wrkb** [comment]
Langsam nehm ich die Bedienfehlervorwürfe persönlich. Nicht nachvollziehbar - okay, das ist die Info die ich brauche, das war die Frage. Automatisch Userfehler zu schreiben, ist fehl am Platz und bar jeder Tatsache.

Die Verknüpfung wurde nicht händisch von mir gelöscht, warum sollte ich das tun?

**Comment by wrkb** [comment]
Der "Bedienfehler" ist ein fetter Fehler im System und hat bei der Bearbeitung der Beschäftigenseiten (neue Einträge eingefügt) gerade ALLE Menüs gekillt und es waren etliche!

Dass wir hier einen Blocker haben, ist sicher klar, ab sofort können keine Menüs mehr bearbeitet werden, nirgendwo, oder wir verlieren Inhalte

**Comment by xwolfde** [comment]
Ok, falsch verstanden. Sorry.

Problem liegt mgwl. nicht direkt an Wordpress, sondern an einer PHP Einstellung, die Wordpress zum Verhängnis wird:
vgl. auch
http://www.netz-gaenger.de/blog/wordpress-tutorials/tun-wenn-sich-menuepunkte-in-wordpress-nicht-speichern-lassen/
http://sevenspark.com/wordpress/menu-item-limit

Wir sind dran.

**Comment by xwolfde** [comment]
Folgende Werte wurden erhöht:

post_max_size = 100M
upload_max_filesize = 100M
max_execution_time = 30
max_input_time = 60
max_input_nesting_level = 256
max_input_vars = 32000
memory_limit = 128M

Damit sollte das Problem behoben sein...

**Comment by wrkb** [comment]
Das Problem des verschwundenen Menüs ist wieder aufgetreten - dieses Mal beim Hinzufügen von Einträgen im Portalmenü Alumni (https://www.fau.de/alumni/). Wir haben es manuell wiederhergestellt. 

Das Menü ist kürzer als das eins verschwundene Intranet-Menü, so dass das mit den mittlerweile erhöhten Werten (s.o.) eigentlich nicht passieren dürfte. Aktuell heißt das, dass alle Menüs potenziell gefährdet sind und wir sicherheitshalber Screenshots von allen Portalen/Menüs anfertigen.

Schaut ihr bitte mal nach? Danke!

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7911191/7ad06b18-085b-11e5-8a81-1f7ec866e54d.PNG)

**Comment by wrkb** [comment]
...und das nächste Menü ist hin. Diesmal hat es Internationalisierung getroffen - ein Menü mit 8 Einträgen...
Gibt es Neugikeiten hierzu?

**Comment by rvdforst** [comment]
Leider noch nicht (der Fehler ist einfach schwer zu finden... ich hoffe, dass hier kein Problem des WP selbst ist). Ich bin dran.

**Comment by wrkb** [comment]
Danke Rolf, wir wissen Bescheid!

**Comment by xwolfde** [comment]
Wie ist der Stand @rvdforst ?

**Comment by wrkb** [comment]
Nur fürs Protokoll: Heute zwischen 8.10 und 8.30 Uhr ist das Menü "Aus dem Ausland" verschwunden beim Umbenennen des Menüs.
(Wiederhergestellt unter dem Namen "International - Studium und Praktikum")

**Comment by rvdforst** [comment]
In diesem Zeitraum hat der FAU-Webserver viele redirects-Fehlern ausgegeben. Leider habe ich kein Backtrace um diesen Fehlern zu entgehen. Auf meinen Test-Webserver passiert das nicht obwohl ich hunderte von Menüs habe. Ich werde auf den FAU-Webserver ein Paar Debug-Funktionen hinzufügen (die Performance des Servers kann ein bisschen abnehmen) um die Ursache des Problems endlich zu beheben.

**Comment by wrkb** [comment]
Fürs Protokoll, diesmal mit engerem Zeitfenster: Zwischen 15.35 und 15.40h heute ist das Menü Alumni vom englischen Auftritt fau.eu verschwunden.

**Comment by xwolfde** [comment]
Möglicherweise haben wir gestern nachmittag eine Problemursache gefunden

**Comment by xwolfde** [comment]
Tritt das Problem noch auf? 
@rvdforst ?

**Comment by rvdforst** [comment]
Meine Meinung nach, das Problem wurde beseitigt. Es fehlt noch den Feedback vom Karsten.

**Comment by wrkb** [comment]
...das Feedback kam ja bisher nur bei Probleme. Wir könnten jetzt mutwillig ein paar Menüs bearbeiten (kleinere z.B.), oder wir warten einfach, ob es wieder auftritt. Was meint ihr?

**Comment by rvdforst** [comment]
Ich habe auf der FAU-Seite (Live-Seite) verschiedene Menüs mit hunderte von Submenüs neu erstellt. Ich habe mehrmals der Menüname umbenannt, etc. In all diesem Fällen hat das Problem nicht aufgetreten.

**Comment by wrkb** [comment]
...das allein reicht evtl. nicht. Das Perfide war ja, dass es 10mal nicht auftrag und dann plötzlich doch... Wollen wir es noch ein wenig beobachten? Ich kann morgen auch noch einmal mit existierenden Menüs testen, die im Zweifel schnell repariert sind.

**Comment by xwolfde** [comment]
Das Problem ist seit den Änderungen nicht mehr aufgetreten.
