### ISSUE TITLE
style="clear:both" bei Überschriften?

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#262]
Spricht eigentlich etwas dagegen, wenn im CSS bei allen Überschriften ein clear:both gesetzt wird? 
Wir haben immer wieder Schwierigkeiten bei Bildern mit Text daneben, dass dann die nächste Überschrift darum fließt und wir mit <hr/> oder längerem Text tricksen müssen, damit es optisch passt.
Aktuelles Beispiel: Seite Tagungsmaterial (im Entwurf)
Wenn wir es nicht global festlegen, darf ich es dann individuell an entsprechender Stelle einbauen?

**Comment by xwolfde** [comment]
Oh ja!
Zum Beispiel bei Artikeln würde es bedeuten, dass das Thumbnail rechts nicht mehr neben der Unterschrift erscheint, wie ihr es manchmal macht.
Ausserdem würde es überall dort, wo die Sidebar verwendet wird, diese kaputt machen.
Die Accordions und Assistenten würden ebenfalls betroffen sein...

Wenn ihr ein clear braucht, dann müsst ihr das [hr] setzen (und danach die Überschrift).

**Comment by wrkb** [comment]
Neugierfrage, vielleich deplatziert hier, aber generell für CSS möglicherweise relevant: Kann das Attribut flexbox künftig (also irgendwann mal) eine Lösung bieten? Habe jüngst von dieser CSS-Erweiterung gehört und die wird in der aktuellen c't als möglicher Problemlöser bei komplexen float-Fragen verkauft.

**Comment by xwolfde** [comment]
Äh nein, es gibt viele CSS-Frameworks. Hier wurde viel auf Basis von BS gemacht  (Bootstrap, nicht Bullshit :) ) . Man kann damit viel machen. Aber das würde hier das Problem nicht lösen.
Man könnte natürlicgh auch jetzt das problem für dich mit dem jetzigen lösen, indem man sich bei dem clear auf Überschriften aus dem definierten Contentbereich beschränkt und auf Seiten ohne Sidebar inline rechts.
Aber das würde viel kleinteilige Änderungsarbeit nach sich ziehen.
