### ISSUE TITLE
Menü-mehr-Link-Erzeugung sinnvoll?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#263]
Undringend für uns.

Um an einem Portalmenü nach 5 Einträgen den Hinweis "...mehr" zu erhalten, muss man 6 Einträge ins Menü packen, wenn ich nichts durcheinander bringe. Der 6. Einträg wird aber nicht angezeigt und hat auch keine weitere Funktion.

Das hat uns beim Relaunch wohl nicht gestört, weil wir die Menüs einfach schnell und effizient (mit allen Unterinhalten) gefüllt und quasi überfüllt haben, um später über die Reihenfolge zu entscheiden. Kritische Konsequenzen hatte das ja nicht, mal abgesehen vom Speicher vielleicht.

Bleiben wir bei diesem Prozess? Der 6te Menüeintrag funktioniert aktuell wie ein Schalter, den wir sonst anders umsetzen müssen. Denn das System weiß ja sonst nicht, wann es mehr als 5 Unterseiten gibt.

**Comment by xwolfde** [comment]
Ich verstehe die Frage nicht... Du weißt das die Anzeige konfigierbar ist?

**Comment by xwolfde** [comment]
Wiedervorlage meiner Rückfrage. @wrkb

**Comment by wrkb** [comment]
...pardon, ging unter. Ich rufe dich mal an, das lässt sich hier sehr schwer erklären.
An Konfigurationsmöglichkeiten sehe ich aktuell an einer Seite, dass man Links an oder aus machen kann an den Portalmenüs. Sonst habe ich noch nichts gefunden (Theme options, Einstellungen).
