### ISSUE TITLE
Links in Sidebar lassen sich nicht löschen

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#264]
...leere ich die Felder eines Links (Beschreibung, URL) und aktualsisiere die Seite, verschwindet der Link nicht. Auf https://www.fau.de/alumni/ etwa bekommen wir den Link zu "Grußwort des Präsidenten" nicht weg.

Kann man da was falsch machen? Sonst haben wir hier irgendeinen Fehler. Auf der Webhummel tritt das Problem auch auf.

Dringlichkeit steigt, wir müssen auf mehreren Seiten die Links ändern und können nicht

**Comment by wrkb** [comment]
Workaround: Ersetzen der Links funktioniert scheinbar, Problem besteht weiterhin.

**Comment by xwolfde** [comment]
Liegt an vorhandener Abwärtscompatibilität zu alten ACF-Felder :/

**Comment by xwolfde** [comment]
Problem identifiziert...

Workaround für fau.de:
1. Seite bearbeiten
2. Metabox "Benutzerdefinierte Felder" aufmachen (ggf. unter Optionen einschalten)
3. Dort die Spalte mit "sidebar_quicklinks" und "sidebar_quicklinks_extern" suchen
4. Diese Spalten löschen.

**Comment by wrkb** [comment]
Okay, danke.
Es ging übrigens in den letzten Tagen bei einigen Seiten doch, ohne Workaround. Ich hatte es nur noch nicht gemeldet bzw. nicht systematisch getestet.

**Comment by xwolfde** [comment]
Es betraf nur Seiten wo es vorher ACF-Felder gab. Und dort auch nur die Felder des ACF Linkblockes in dem man vorher absolute URLs einfügen konnte.

**Comment by xwolfde** [comment]
Beim nächsten Update behoben
