### ISSUE TITLE
Reihenfolge von Seiten innerhalb einer Subnavi (Inhaltsseite) - wie genau?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#265]
Ich hatte dazu neulich schon ein Telefonat mit Astrid geführt, aber so ganz klar ist die Sache in Wordpress noch nicht.

Wenn wir die Reihenfolge von Seiten in der Subnavi bestimmen wollen, vergeben wir Nummern an den Seiten - üblicherweise jeweils 5, 10, 15, 20... - um noch Platz für evtl. neue Zwischenseiten zu lassen. Das tun wir mehrmals für jede mehrere Menüs, also die Nummer 5 ist mehrfach vergeben - anders geht es ja nicht.

Aktuell klappt das aber z.B. für die Unterseiten von https://www.fau.de/studium/vor-dem-studium/bewerbung/ nicht beim - dort sind die Seiten nicht in der gewünschten Reihenfolge, obwohl ich jede Seite in die gewünschte Reihenfolge gebracht habe. Teils haben die Seiten einfach eine andere Nummer erhalten, als eingebeben.

Frage: Gibt es irgendetwas zu beachten bei der Reihung? Da wir keine andere Möglichkeit haben, um Menüs innerhalb eines Bereichs zu beeinflussen, muss das mit den Nummern klappen und sollte die einzige sinnvolle Möglichkeit sein. Die Nummer können doch mehrfach vergeben werden für mehrere Subnavis?

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7700437/fef6d004-fe1e-11e4-8107-7822b9166f3a.PNG)

**Comment by xwolfde** [comment]
Ja, da ist an der Stelle im Theme alter Murkscode, den MR selbst wieder von Dritter Seite hergenommen hat. Den hab ich damals auch nicht angepackt, weil ich den nicht kapiert hab ...
Vielleicht hab ich ihn nicht kapiert, weil es totaler Unfug ist, was da gemacht wurde. Oder mir ist der Groschen auch noch nicht gefallen...

**Comment by xwolfde** [comment]
Wie sollte das denn idealerweise funktionieren?
Diese Eingabe mit den Zahlen ist ja wohl auch nicht so dolle, oder?
Brauche Ideen.

**Comment by wrkb** [comment]
Die Zahlen sind m.E. Wordpress-Standard - auch im Blogsystem vorhanden. Von Anpassungen ist mir da nichts bekannt.
Drupal macht'ss auch mit Zahlen, aber via Dropdown. Ich finde spontan nicht genug dazu - interessant wäre ja, ob man die Position der anderen sieht gleichzeitig sieht.. Das olle Joomla hat die Auf-Ab-Pfeile in der Seitenliste, das können wir m.E. aber nicht abbilden in Wordpress.

Das Hauptproblem ist eigentlich für uns, dass wir an der Seite nicht sehen, welche Gewichtung die anderen Seiten in der gleichen Ebene haben. Ansonsten sind die Zahlen schon okay.
Ob wir aktuell sauber und wie von Wordpress vorgesehen arbeiten, ist mir nicht ganz klar (siehe 1. Post) - es gibt aber keine Probleme derzeit.

**Comment by xwolfde** [comment]
Muss auf Release 3 verschoben werden.

**Comment by wrkb** [comment]
Hinweis: Es geht hier meines Erachtens um das Verstehen einer Out-of-the-box-Funktion von Wordpress, nicht einer Anpassung oder von irgendwem angepassten Funktion.

Inwieweit das Ganze mit #62 zu tun hat, erschließt sich mir nicht, denn die Sortierung erfolgt doch unabhängig von der Menüdarstellung in #62?

**Comment by xwolfde** [comment]
Mein Problem ist, dass ich selbst auch noch nicht so richtig verstehe, wie es in der Umsetzung dann aussehen soll. Der alte Code an der Stelle ist nicht sehr hilfreich und es gibt dauernd die Kollission mit den eigentlichen WordPress-Corefunktionen bei dem Ranking der Artikel... Ich hab mir das schon mehrfach angeschaut und ich raff es einfach nicht, wie wie es funktionieren soll und wie wir das dann auch noch Otto-Normaluser vermittteln könnten...

Ich schlag vor, wir canceln die Überlegungen hier und machen im  RRZE-Webteam/FAU-Einrichtungen ein neuen Issue darüber, wie wir es eigentlich wollen - dabei völlig unbeeinflusst davon, wie es derzeit umgesetzt ist.

**Comment by wrkb** [comment]
Ich denke, wir hier sind für alles offen, was gut funktioniert. Aktuell ist es handhabbar, aber es kann eigentlich nur besser werden. Ziel sollte nur sein, dass man nicht alle Reihenfolgen neu bauen muss (hunderte von Seiten...). Alles weitere gehört ins neue Issue.

**Comment by wrkb** [comment]
Die Rückmeldungen anderer Nutzer wären übrigens interessant, denn die Reihenfolge muss ja jeder einstellen und die Funktion hängt ja nicht vom Theme ab, sondern ist Teil von Wordpress (auch in Twenty Sixteen vorhanden)

**Comment by xwolfde** [comment]
Es wird aber keine Rückmeldung von anderen geben - nur ihr setzt das ein und ab der neuen version kann es auch nur noch von euch eingesetzt werden :)) 
Aber wie gesagt: Bitte bei FAU-Einrichtungen weiter als neuen Issue darüber, was ihr  konkret wünscht.
