### ISSUE TITLE
Generell: Rote/eindeutige Warnung bei nicht/falsch ausgefüllten Feldern

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#266]
...ich wollte gerade eine Personenvisitenkarte aktualisieren, aber beim Klick auf "Aktualisieren" passierte nichts. Nur durch Scrollen und mehr durch Zufall habe ich den Hinweis gesehen, dass die Webadresse fehlerhaft ist (die noch aus der alten ACF-Lösung übernommen wurde in diesem Fall und nicht eingegeben wurde von mir). Hier braucht der Nutzer irgendeine Rückmeldung oder die Bedienmaske sollte an den fraglichen Punkt springen (wie Formulare auf Webseiten es teils tun.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7701645/73cd863e-fe29-11e4-8b04-941a25126281.PNG)

**Comment by xwolfde** [comment]
Sorry, an dem alten Teil werden wir nichts mehr weiterentwickeln. Mit den Fehler müsst ihr leben oder irgendwann auf das neue Plugin wechseln (was allerdings nicht schmerzlos sein wird, sondern aufwendig, da ihr so viele Einträge von Hand eingetragen habt).

**Comment by wrkb** [comment]
Alles klar, das überleben wir schon. Danke.
