### ISSUE TITLE
blaues Wasserzeichen im blauen Headerbalken: in z-Ebene hinter h1

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#267]
...das Problem mit Überlappungen wie im Screen wird dadurch nicht gelöst, aber entschärft, da das Wasserzeichen zumindest hinten ist. Und es gibt m.E. keinen Grund, dieses nicht nach hinten zu legen - Nachteile sollte es keine haben.

(Bei der Länge der Bezeichnungen müssen wir uns was überlegen, ist ein Inhaltsproblem...)

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7704811/edf93fc2-fe40-11e4-8df4-68bbd8aa3a33.PNG)

**Comment by xwolfde** [comment]
Anmerkung: Bei den Fakultäten schon gelöst

**Comment by xwolfde** [comment]
Auf test4 gelöst. Bitte gegenprüfen

**Comment by xwolfde** [comment]
Siehe
http://test8.wordpress.webhummel.rrze.uni-erlangen.de/tests/unterseite-des-portals-test-mit-einem-etwas-laengeren-titel-manche-wollen-das-ja-so/

**Comment by wrkb** [comment]
Das ist ziemlich cool - dankeschön :)
