### ISSUE TITLE
Zeilenumbruch in Chrome anders als in Firefox

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#268]
Es geht um den Satz mit "Weitere Informationen: ..."
Der wird unterschiedlich dargestellt.

Chrome:

![chrome](https://cloud.githubusercontent.com/assets/9445370/7835227/6ab4fa6a-0477-11e5-85a2-087adebd1c55.PNG)

Firefox (eingeloggt als Admin):

![firefox](https://cloud.githubusercontent.com/assets/9445370/7835231/6c55d1a0-0477-11e5-887f-fc3e7d9c0e6d.PNG)

Backend:

![backend](https://cloud.githubusercontent.com/assets/9445370/7835260/ad2bb5a0-0477-11e5-8fb4-236651f4a624.PNG)

**Comment by xwolfde** [comment]
Ja, der kann halt nicht so gut umbrechen, weil er nicht weiss, wo er den Link umbrechen kann.
Mglw. ist die deutsche Sprachbib von dem Chrome nicht so gut.

Da können wir nichts beständiges machen, das ist ein Browserding.
