### ISSUE TITLE
Eilt: Backend: Spalte "Zuletzt geändert" fehlt, "Datum" ist wieder aktiviert, Sortiermöglichkeit fehlt

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#269]
...mittlere Katastrophe, da wir für die Übersetzung dringend die Sortierung nach der letzten Änderung brauchen - absteigend, jüngste Dokumente zuerst! Für diese Woche sind wir da zum Glück durch, aber ab Montag bekommen wir Probleme.

Es fehlt schlicht die Option, die Spalte "Zuletzt geändert" einzublenden.

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/7882209/8a0de594-060b-11e5-8cdb-263d57dee34d.PNG)

Woher das Problem kommt, ist rätselhaft. Letztes Update?

Es soll so aussehen, wie im Screenshot unten.

![bild1](https://cloud.githubusercontent.com/assets/9445370/7882210/91f3c954-060b-11e5-9935-1ca0ae07344d.png)

**Comment by rvdforst** [comment]
Die Spalte ist wieder da. Sorry.
