### ISSUE TITLE
Suche geändert?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#270]
(...habe keine separate Ressource zur Suche gefunden, falls das hier falsch ist, bitte gern verschieben).

Habt ihr in den letzten 3 Tagen etwas an der Suchfunktion geändert? Wenn Sie Teil des Themes ist, wohl eher nicht.
Wir fragen, weil wir einige Sachen nicht wie erwartet finden und zwar auch dann nicht, wenn wir die passenden Seitenschlagworte eingeben. Oder es kommen zum Suchwort schlossgartenfest zwar seiten, aber keine Newsbeiträge.

Wir können das aber an nichts festmachen und das Problem kaum umschreiben - daher erst einmal die Frage :)

Ansonsten müssen wir mit den Einstellungen experimentieren, wir haben kürzlich die Seitenschlagworte höher gerankt als alles anderen Kriterien.

Danke und Gruß

Karsten

**Comment by rvdforst** [comment]
Die Suche ist Teil des "cm-search"-Plugins (ist auf Gitlab: https://gitlab.rrze.fau.de/rrze-webteam/cms-search). Ich vermute, dass das Problem liegt an der Indizierung der Suchbegriffe (die DB-Suchetabelle ist einfach zu groß geworden). Lösung: Die Indizierung vollständig auslöschen und das ganzes Ding wieder indizieren. ich kümmere mich drum... (wo war ich auch dran?... ;-)

**Comment by wrkb** [comment]
Danke Rolf!

**Comment by rvdforst** [comment]
Die neue Indizierung ist fertig. Jetzt ist die Suche wesentlich schneller geworden aber das Problem besteht nach wie vor... Ich bin noch dran.

**Comment by wrkb** [comment]
:+1:
