### ISSUE TITLE
Glossar-Sortierung A/Ä

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#272]
Glossar-Inhalte werden komisch sortiert, wenn Umlaute im Spiel sind:

![1](https://cloud.githubusercontent.com/assets/9445370/8281032/218ef350-18e4-11e5-9f7f-9d7819319404.png)

Quelle: https://www.fau.de/international/aus-dem-ausland/alles-zum-aufenthalt-an-der-fau/erste-schritte/

Korrekt wäre doch, dass Ä unter A sortiert wird wie alle Begriffe mit A, so wie im Duden/Lexikon, oder? Das hätten wir auch gern bitte :) Das Ganze ist schon online und wird auch in Kürze in die App gespielt.
@lagerlit

**Comment by xwolfde** [comment]
Also ich habs sogar so gelernt: A B C ... Z Ä Ü Ö ;)

**Comment by wrkb** [comment]
Also am Ende ist es definitiv nicht hilfreich. In technischen Katalogen/Sortierungen kenn ich das auch, aber der Nutzer wird keine Einträge mit Ä am Ende suchen - da wette ich. Spricht was gegen das Gleichbehandeln mit A? Und analog dann mit I, O, U und E?

**Comment by xwolfde** [comment]
Wir sind dran. Das Problem ist wegen der Notwendigkeit der Mehrsprachigkeit komplexer.
Ausserdem müssen wir die Sortierbarkeit bei Nutzung von Emojis diskutieren

**Comment by wrkb** [comment]
Uns würde eine erste Vorablösung für die deutschen Umlaute sehr helfen. Ich vermute, dass Worte, die mit Akzenten beginnen (wie in deinem Postings zu Rolfs Änderung) eher selten bis fast nie vorkommen.

Das mit dem Emojis hab ich nicht verstanden. Wer sollte so verrückt sein, in einem Glossar Emojis zu verwenden? Sachlichkeit usw....

**Comment by xwolfde** [comment]
Wenn du wüsstest ;)

**Comment by wrkb** [comment]
Ja, ich kann mir Vieles vorstellen. Aber sollte man das unterstützen? Es ist ein Glossar, ein Werkzeug für sachliche Darstellung von XYZ...

**Comment by xwolfde** [comment]
im nächsten update drin
