### ISSUE TITLE
Darstellungsfehler Chrome Silbentrennung/Umbruch

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#273]
...keine Ahnung, obs am Browser oder am CSS liegt, aber mindestens dieser Beitrag https://www.fau.de/2015/06/news/panorama/millionenfoerderung-fuer-globales-innovationsprogramm/ wird in Chrome mit komischen Umbrüchen dargestellt (die definitiv keinen Sinn ergeben) und die Silbentrennung ist zumindest anders als im Firefox.

Mögt ihr mal schauen, was davon wir beeinflussen können? Sieht leider nicht so dolle aus :(

Chrome:
![unbenann](https://cloud.githubusercontent.com/assets/9445370/8281221/cd44ec1c-18e5-11e5-8b22-76f2eab07c69.PNG)

Firefox:
![ff](https://cloud.githubusercontent.com/assets/9445370/8281231/e33dadec-18e5-11e5-9fa3-3a9c43ee907e.PNG)

**Comment by xwolfde** [comment]
Liegt an dem "Wortschatz" von Chrome, da können wir nichts machen. 
hatten wir doch schonmal die Frage?

**Comment by wrkb** [comment]
Möglich, aber so krass ist es uns noch nicht aufgefallen. Bei den vielen Browserupdates kann das auch neu sein, daher die Frage. Nungut, wir müssen damit leben.

**Comment by xwolfde** [comment]
Ja- Der IE11, der in der Sicherheitsstufe "Hoch" bei Nutzung von Domains "uni-erlangen.de" auf Intranet-Modus umschaltet und damit dann plötzlich die alte fehlerbehaftete IE7 (!!) Darstellungsweise einschaltet ist viel schlimmer.
