### ISSUE TITLE
Fehler bei Bild-Sizes (Gallerien)

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Theme#281]
In Z 119 bis 126 functions.php ist die Dimension der Bilder falsch definiert (immer dieselbe Auflösung statt unterschiedliche) 
Dadurch kommt es zu Problemen bei der Darstellung der Bildergallerien Grid, 2cols, 4cols).

Testfall
[gallery type="grid" caption="1" ids="16679,1136977,1136979"]
 Permalink: https://www.fau.de/universitaet/auszeichnungen-und-ehrungen/akademie-mitglieder/academia-europaea/ ‎Bearbeiten

Gemeldet von @wrkb

**Comment by xwolfde** [comment]
Ist ne kleine Sache, daher noch vor mein Urlaub. Aber nicht mehr heute.

**Comment by xwolfde** [comment]
Fixed im nächsten Update. 
 Unter Design Options->Erweitert das Bildmaß bei Grid auf 145x120,false setzen. Danach Regenerate Images anwerfen.

**Comment by xwolfde** [comment]
online

**Comment by wrkb** [comment]
Läuft. Danke!!
