### ISSUE TITLE
Defekte Dokumenten-Größen-Anzeige - Stand?

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#283]
Ich finde leider das alte Issue zum Thema nicht, daher ein neues:
Eingefügte Dokumente (Mime-Types PDF und Office z.B.) zeigen ja aktuell nur eine Größenangabe, wenn der Link noch auf megli.zuv.cms... lautet, nicht auf fau.de. Ist das noch bekannt als Bug oder schon geschlossen?
Die Dringlichkeit war nicht hoch, aber es sollte nicht untergehen :)

Beispiel: https://www.fau.de/universitaet/das-ist-die-fau/medien-und-publikationen-der-fau/friedrich/

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/8591553/630082a2-2629-11e5-95cc-206b35cd2aa3.PNG)

**Comment by xwolfde** [comment]
Warten bis nach Techfak.

**Comment by xwolfde** [comment]
Offensichtlich (jedenfalls bei obiger URL) inzwischen behoben
