### ISSUE TITLE
Kalenderanzeige auf fau.eu zur Zeit fehlerhaft

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#284]
auf der Startseite von fau.eu sind zur Zeit (im Firefox sichtbar) die blauen Kalenderblätter ineinander geschoben (s. Screenhot). Ich denke, hier müsste noch eine entsprechende min-height im css eingebaut werden...
![kalendereintrage fau eu-startseite](https://cloud.githubusercontent.com/assets/9526974/8795710/746d7648-2f8f-11e5-8ea2-9e7f7362b0a6.jpg)
events-list ul li {
    list-style: outside none none;
    margin: 0px;
    padding: 0px;
    background: transparent none repeat scroll 0% 0%;
    min-height: 50px;
}

**Comment by xwolfde** [comment]
Nein.
Das Problem hatten wir schon mal. Es kommt aus dem Fehler bei der Eingabe des Kalendereintrags, bei dem die Zeitangabe nicht ausgefüllt wurde und daher fehlt.

**Comment by wrkb** [comment]
Ist der Haken bei "ganztägig" eine valide Zeitangabe?

**Comment by rvdforst** [comment]
Tja für ganztägige Termine gibts keine Zeitausgabe (Fau-Theme/functions/pluggin-support.php - Zeile 100). Ich bin dran.

**Comment by rvdforst** [comment]
Btw. soll der Text der Zeitausgabe "ganztägig" sein?

**Comment by wrkb** [comment]
Nein, das wäre dann nur ein Termin, der keine bestimmte Uhrzeit hat gewöhnlich (Semesterbeginn z.B.)

**Comment by xwolfde** [comment]
Das Design gibt vor, daß dort eine Zeile angegeben werden soll. 
@rvdforst Bitte schreibe da "Ganztägig" hin.

**Comment by rvdforst** [comment]
Vielleicht hilft ein geschützte Leerzeichen (nbsp;) als Zeitausgabe für Termine die ganztägig bzw. keine Uhrzeit haben.

**Comment by xwolfde** [comment]
Nein. Ganztägig ist gängig und wird auch so in der Quelle (Exchance) angezeigt.

**Comment by xwolfde** [comment]
Im nächsten Update drin
