### ISSUE TITLE
Glossary-Einträge und Personenvisitenkarteneinträge für google unsichtbar machen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#285]
Hallo,
aus gegebenem Anlass bitten wir die Einträge im Glossar (und dann auch gleich bei den Personenvisitenkarten) möglichst schnell für google nicht indizierbar zu machen. Danke!

**Comment by rvdforst** [comment]
Erledigt! Die robots.txt-Dateien der Webseiten www.fau.de u. www.fau.eu wurden aktualisiert.

Allerdings darauf muss man hinweissen, dass es liegt an den Suchmaschinen (a.k.a. googlebot u. co.), ob diese Verzeichnisse (/person/ u. /glossary/) indexiert werden können.

Hinweis: Man kann die Einstellungen der robost.txt-Datei jederzeit unter Einstellungen > Lesen bearbeiten.
