### ISSUE TITLE
Metaleiste Startseite (Menülocation: Metaleiste oben) fehlt auf dem Smartphone

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#286]
...ich dachte, das war mal da, stimmt aber nicht, fehlt wohl schon immer. Ich weiß nicht, ob das eine bewusste Entscheidung war (Optik, Bedienbarkeit), aber zumindest der Link zu UnivIS fehlt doch irgendwie (die häufigst nachgefragte Funktion in der Metaleiste in der Desktop-Variante). den Rest könnten wir unten in den Footer setzen, wobei wir hier nicht zwischen Mobilnavigationen und Standard verschieden definieren können (das Weaver-Theme für Wordpress hat das z.B.).

Ist eine Lösung schon angedacht? Oder kurzfristig möglich? Oder eher langfristig?

**Comment by xwolfde** [comment]
Gehört in den Kontext zum fehlerhaften responsive Design. Dort bereits Thema.

**Comment by xwolfde** [comment]
fixed im Test
