### ISSUE TITLE
Formatierung WYSIWYG - Benutzung Einzug

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#287]
![unbenannt0](https://cloud.githubusercontent.com/assets/9445370/9110857/843251f2-3c41-11e5-86b4-5bce61f29bd4.PNG)

In der Schulung sagen wir derzeit, dass diese Wordpress-Funktion nur in Tabellen benutzt werden darf, besser gar nicht. Selbst habe ich das Einrücken von Elementen via padding-left gerade mal testweise benutzt, da wir mangels Template/Klasse immer noch keine keine Möglichkeit haben, Listen mit mehreren Details schön zu gestalten.

Frage: Wie gut/sauber ist das überhaupt? Da es eine einzelne Auszeichnung ist pro Zeile, ist es eigentlich eher unsauber, eine CSS-Klasse wäre wohl konsequenter. Was meint ihr?

Als Übergangslösung bis zu einer Designlösung hilft es uns aber. Spricht etwas gegen den Einsatz?

Auf dieser Seite hat es gut funktioniert:

![unbenannt1](https://cloud.githubusercontent.com/assets/9445370/9110852/75ab2ee2-3c41-11e5-8353-98f7ebfb7614.PNG)

Hier scheint es mit irgendwas zu kollidieren:

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/9110856/813772f2-3c41-11e5-8612-7e1d33062e85.PNG)

**Comment by wrkb** [comment]
@wrcg @lagerlit

**Comment by xwolfde** [comment]
Es ist in allen Fällen Unfug. Sowohl in der Tabelle als auch drum herum. Das Design hat vorgegeben, dass es bei Absätzen keine Einrückungen gibt. Daher deaktiviert ihr diese Option im Editor am Besten ganz bzw. nutzt sie nicht.
