### ISSUE TITLE
Einfügen von Kontextlinks (Sidebar) erzeugt wild Link im Text

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#288]
Ich füge den Link über das Linktool von Wordpress unter "Sidebar" ein:

![unbenannt2](https://cloud.githubusercontent.com/assets/9445370/9466783/8b768604-4b37-11e5-8432-d9cf6b83dd1b.PNG)

Gleichzeitig wird der Link auch oben ins Textfeld kopiert. Merkt man natürlich erst nach dem Aktualisieren, so dass man im Zweifel korrigieren muss:

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/9466839/eda304f6-4b37-11e5-9243-bb25071ffca6.PNG)

**Comment by xwolfde** [comment]
Setzt den Fokus vorher auf das Eingabefeld (Linkurl oder Linktitel)

Die Funktion habt ihr im Frühjahr getestet und kein Problem gemeldet. Jetzt ists zu spät. Daher warten bis nach der Techfak.

**Comment by wrkb** [comment]
Ja, damals hat es auch funktioniert.
Fokus setzen hilft _nicht_

**Comment by xwolfde** [comment]
Im nächsten Update behoben

**Comment by xwolfde** [comment]
Zu früh gefreut. $InsertFluchhier

**Comment by xwolfde** [comment]
Egal was ich tu, der Link den ich im wpLink Editor auswähl wird zusätzlich zum Eingabefeld unten auch oben in das Eingabefenster vom Editor reingepostet. Und zwar an die Stelle wo man vorher war.
Dies passiert auch dann, wenn ich mit der Maus vorher in ein anders Eingabefeld klicke.

**Comment by rvdforst** [comment]
Wir müssen die Variable wpActiveEditor überschreiben mit TRUE weil sonst wird der Dialog-Box die aktuelle WP-Editor-Instanz nutzen.

**Comment by xwolfde** [comment]
Das wurde schon in _init() gemacht, ohne das es eine Auswirkung hat.

**Comment by xwolfde** [comment]
Danke Rolf gefixt! \o/
