### ISSUE TITLE
Dringend: "Mehr"-Button zu den Meldungen auf der Startseite fehlt

### ISSUE THREAD

**Issue by lagerlit** [RRZE-Webteam/FAU-Theme#289]
Hallo, uns ist da ein Button abhanden gekommen, auf fau.de (Nicht auf fau.eu): Der "Mehr Meldungen"-Button unter den drei Meldungen auf der Startseite, der zum Blog https://www.fau.de/category/news/ liegt. Das bedeutet, niemand kann von der Startseite unsere Meldungen erreichen. Bei der nächsten Meldung kann dann niemand mehr unseren aktuellen Content sehen - bitte schnell fixen! Danke :)

![mehr button fehlt](https://cloud.githubusercontent.com/assets/9449835/9471917/d4b7af26-4b52-11e5-9e15-65c2616a4480.JPG)

**Comment by xwolfde** [comment]
Bedienerfehler.
Bitte drauf achten, was ihr in den Optionen ändert.

**Comment by lagerlit** [comment]
Ist der Button neu? Gabs ein Update? Von uns hat in den Theme Options keiner etwas verändert! Aber jetzt wissen wir, wies geht ;)

**Comment by wrkb** [comment]
Kenne die Option auch nicht. Die wurde sicher wegen der Fakultätsthemes eingeführt? Und ist sie per default gesetzt? Ich vermute: nein. Und damit wurde uns der Button bestimmt gemopst, wenn es ein Update gab. Gab es eins?

**Comment by xwolfde** [comment]
Diese Option gab es seit ...letztem Jahr?  Prüft es selbst, ihr könnt das mit dem GitHub. 
Oder checkt die Mails, ich hab es euch mal erklärt.

**Comment by wrkb** [comment]
Okay, danke. Es bleibt aber der Fakt, dass wir die Option nicht angerührt haben, es gab auch keinen Grund dazu.
