### ISSUE TITLE
Medien bearbeiten - Fehler beim Feld "Beschreibung"

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Theme#293]
seit kurzem (seit Dokumentenzugriffsschutz-Änderung?!) kann man keinen Text mehr in die Bildbeschreibung einfügen. Er wird mit jedem Aktualisieren mit Buchstabensalat überschrieben.

![datei-beschreibung](https://cloud.githubusercontent.com/assets/9526974/9745840/758efab8-5674-11e5-9918-cf9b2f51d8b9.jpg)

**Comment by xwolfde** [comment]
Kann ich bestätigen.

Hier ein Testbild:
https://www.fau.de/wp-admin/post.php?post=1219875&action=edit

**Comment by rvdforst** [comment]
Da habe ich ein bisschen mit der Verschlüsselung übertrieben ;-)

**Comment by rvdforst** [comment]
Bug fixed @cms-intranet 1.2.3
