### ISSUE TITLE
Sidebar - Titel erster Linkblock kann nicht geändert werden

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Theme#298]
Bei alten Seiten ist der Titel im Feld sidebar_title_quicklinks gespeichert, die Änderungen werden im Feld fauval_sidebar_title_linkblock1 gespeichert, aber dann immer wieder mit dem Wert in sidebar_title_quicklinks überschrieben (vermutlich aufgrund der Auflösung von ACF?) Erst nach Löschen von sidebar_title_quicklinks kann der Titel auch erfolgreich geändert werden.

**Comment by xwolfde** [comment]
Bitte in der aktuellen Version auf test4 bzw den anderen Themes nochmal testen. Sollte gelöst sein.
