### ISSUE TITLE
Verschönerung Darstellung Mobile Devices

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Theme#301]
Issues zur Verbesserung der Darstellung des repsonsive Designs für kleine Bildschirmdarstellungen auf Basis vom aktuellen Testbranch Dev2-0 hier eintragen.

**Comment by wrcg** [comment]
Folgendes ist mir aufgefallen:
- FAUSocial-Bereich ->Link: Alle Videos entfernen, das verwirrt, wenn man gar keines sieht…
- Umschaltbutton de/en ist nicht vorhanden – Absicht?
- Menü funktioniert bei mir im Firefox, Chrome und Opera erst nach „neu laden“ – vorher sieht es so aus:  
![menue](https://cloud.githubusercontent.com/assets/9526974/11297727/ad651708-8f7a-11e5-8cf8-f80be1127038.png)

**Comment by wrcg** [comment]
kleine Verbesserungswünsche bei der Inhaltsdarstellung (nicht Menü)
- Assistentenseite: nicht nur den Seitentext anzeigen – Kontext wichtig, erkennt man sonst nur an der Breadcrump
- Bilder zentriert anzeigen
- Bildergalerie Raster: Zentriert darstellen
- Bildergalerie/Bilderslider: Evtl. noch Pfeile zum Blättern hinzufügen
- Personenvisitenkarten: Anzeige des Freitextfeldes optimieren
- Tabellen: passen, wenn auch nicht schön – aber das liegt wohl eher an uns
- Sidebar: Evtl. mit Überschrift „Sidebar“ o.ä. versehen

**Comment by AstridSemm** [comment]
Wenn Bilder größer sind als der Bildschirm, sieht man (wohl) nur den rechten Rand. Kann man die Bilder automatisch anpassen lassen? Screenshot:
![screenshot_2015-12-08-13-26-26](https://cloud.githubusercontent.com/assets/11296947/11655962/1f5964be-9db2-11e5-9283-2f84ce594f34.png)

**Comment by AstridSemm** [comment]
Wenn eines der Bilder im Galerie-Raster mit shortcode gallery und id's und type="grid" eine recht umfangreiche Bildunterschrift hat, will mir scheinen, dass die übrigen Bilder in der Galerie ebenso viel leeren Platz in der Unterschrift haben wie die lange Unterschrift eingenommen hat. Das irritiert, weil man denkt, da müßte noch was geladen werden. Screenshots:
![screenshot_2015-12-08-13-34-16](https://cloud.githubusercontent.com/assets/11296947/11656050/df70384a-9db2-11e5-8775-90d07a8299a7.png)
![screenshot_2015-12-08-13-30-14](https://cloud.githubusercontent.com/assets/11296947/11656051/e292b688-9db2-11e5-904a-e55931db4bd3.png)

**Comment by xwolfde** [comment]
header fixed hat noch probleme

**Comment by xwolfde** [comment]
Letzte Version zum testen auf
test4.tindu.rrze.uni-erlangen.de

Nur aus dem Uninetz erreichbar

**Comment by wrkb** [comment]
Hallo Wolfgang,

wir haben jetzt intensiver getestet, soweit es hier bei uns möglich ist. Bei Punkten mit Rückfragen/Unklarheiten meldet euch bitte kurz, dann können wir ggf. gezielter informieren und auch mal Screenshots machen (beim iPhone weiß ich nicht mal, wie/ob das geht). Firefox würden wir auch nachtesten – Chrome ist Platzhirsch.
Einige Punkte nennen wir zum ersten Mal (Ladezeiten), da wir ja mobil jetzt richtig überarbeiten und auch weiter fortgeschritten sind damit.

Geräte:

Oneplus One (1080px x 1920) - Chrome
Note 4: (12xx x 2560 px) - Chrome
Galaxy A3 (540 x 960px) Stockbrowser
iPhone 5s (640 x 1136px) - Safari

Startseite:


·         Ladezeit – wie hoch ist die? Wie groß ist die Seite eigentlich? Ggf. Bilder reduzieren? Text hat mehr Priorität)

·         Bühne nicht anhaltbar (Barrierefreiheit?)

·         Logoslider fehlt (soll so bleiben? – siehe Ladezeiten)

·         die FAU-Logos in Header und Footer sind unscharf. Wer kann das beheben?

·         Kopfzeile sollte wie auf Desktop schrumpfen. Beim Scrollen insbesondere im Querformat blockiert die Leiste ein Viertel des Bildschirms und macht Bühnenbilder kaum erfassbar.

Inhaltsseite:


·         Rechtszentrierte Bilder sehen nicht schön aus (inkl. der nervigen rechtszentrierten BU wie in Desktop-Auflösung). Vorschlag: Alle Bilder nur mittig anzeigen für Hochformat, BU immer linkszentriert.

·         Linke Navileiste erschließt sich nicht intuitiv als solche (u.a. weil genauso breit wie andere Inhalte). Man muss sie erst lesen und deuten. Bitte: können wir da für alle mobilen Darstellungen, in denen die Navileiste nicht links neben dem Content hängt, was drüberschreiben? Navigation oder Menü etwa?

·         Linke Navileiste taucht zweimal auf (Seite http://test4.tindu.rrze.uni-erlangen.de/test-portal/updatecheck/)

·         Linke Navileiste muss vor Sidebar auf der Seite auftauchen – also ganz am Ende.

·         Bild in Vollgröße/großer Größe (1600px) skaliert nicht richtig. (Empfehlung: zentriert, BU linksbündig)

·         Einige Akkordeons und Glossare auf http://test4.tindu.rrze.uni-erlangen.de/test-portal/shortcode-tests/ sind aufgeklappt per default. Andere nicht (so sollte es sein)

·         Organigramme ohne Unterpunkte irritieren als Liste ohne Design. Aber: Wird so nie verwendet, oder? Irgendwo ist immer ein Pluszeichen, sonst wäre Organigramm das falsche Tool?

·         Eingebunde Karten: Sind insbesondere im Querformat kaum zu überscrollen. Bitte zentriert und mit genügend Weißraum seitlich, dann kann man dort anfassen und scrollen. Auf Android ist das inbesondere wegen der Telefon-Navi-Elemente am Bildschirmrand nötig

·         Auf http://test4.tindu.rrze.uni-erlangen.de/test-portal/shortcode-tests/ ist eine Visitenkarte von Wolfgang mit einem riesigen (!) Bild versehen, egal ob hoch oder quer. So gewollt?

·         Auf http://test4.tindu.rrze.uni-erlangen.de/test-portal/shortcode-tests/ ist an der Visitenkarte (Riesenbild) im Content der Freitext nicht eingerückt (linksbündig), auf anderen Seiten dagegen eingerückt. Fällt vor allem mobil auf. Wie soll es eigentlich sein?

Portalmenüs:


·         Werden nicht immer angezeigt (Startseite, Portalseite) – unterschiedlich je nach Gerät. Vermutung: Bildschirmauflösung ist Kriterium. Bei den beiden kleineren Auflösungen (5s, A3) geht es, bei den größeren Screens (Oneplus, Note4) nicht. Bug!

Videos:

·         In Safari gar nicht sichtbar (stattdessen nur Shortcodes)

·         Volle Größe (1. Video) wird nicht skaliert, sondern ragt aus dem Bildschirm (nach rechts) (http://test4.tindu.rrze.uni-erlangen.de/test-portal/videotest/)

Tabellen:


·         Beim horizontalen Scrollen gibt es auf Android einen horizontalen Scrollbalken. Auf iPhone nicht. Natürlich, Tabellen sind eh böse… es fiel aber auf.

·         Breitere Tabellen können sich perfekt als schmal tarnen je nach Auflösung – man sieht keine weiteren Spalten. Gibt es dafür eine simple Lösung (Pfeil, Texthinweis)? Sonst müssten wir breite Tabellen tatsächlich verbieten, aber das wäre paradox, weil Tabellen ja eigentlich nur noch für komplexere Inhalte in Tabellenform herhalten sollen, wo man nicht anders lösen kann. Sprich: Wenn Tabellen, dann eigentlich nur die breiten, die schmalen, zweispaltigen kann man locker auflösen in Listen o.ä. Was tun? Wir mögen keine Tabellen, aber noch sind sie nicht ganz verboten…
Galerien:


·         2cols: Auf Safari rechts am Contentrand, unschön, auf Android normal

·         4cols: bei kleinen Bildschirmen (<1000px Breite?) unschön, sehr klein und links an den Rand gedrückt in Safari

·         Auf http://test4.tindu.rrze.uni-erlangen.de/test-portal/shortcode-tests/ zeigt Safari beim Organigramm überall externe Linkpfeile an – fälschlicherweise. Android und Desktop tun es nicht.

Anmerkung Karsten zu den neuen Symbolklassen auf http://test4.tindu.rrze.uni-erlangen.de/test-portal/textbereiche/:


·         Was bedeuten die neuen Symbole?

·         Sind Baustellen-Hinweise sinnvoll? Das Symbol assoziieren nur Technik-Affine mit Baustelle oder Systemeinstellungen, der Rest versteht es nicht.

·         Das blaue Ausrufezeichen (class hinweis) finde ich nicht gut – aus dem Bauch heraus. Ein anderes Symbol sollte da rein. Entweder eine Glühlampe oder sowas, oder es sollte dann der attention-Hinweis so ein dreieckiges Schild bekommen (Achtung-Schild wie StvO) und das Ausrufezeichen für hinweis.

Nachtests mit genügend Frist, denn leider geht für so einen Test locker eine Stunde drauf mit Testen und Formulieren – machen wir nicht spontan oder nebenbei. Aber gern ;)

Grüße

Karsten


Webredaktion fau.de/fau.eu
09131/85-70203

Wichtig: Bitte senden Sie Anliegen zu Webseiten immer an die gesamte Webredaktion via webredaktion@fau.de<mailto:webredaktion@fau.de>. Sonst kann es zu Verzögerungen kommen.

Von: Wolfgang Wiese [mailto:notifications@github.com]
Gesendet: Montag, 15. Februar 2016 16:38
An: RRZE-Webteam/FAU-Theme
Betreff: Re: [FAU-Theme] Verschönerung Darstellung Mobile Devices (#301)


Letzte Version zum testen auf
test4.tindu.rrze.uni-erlangen.de

Nur aus dem Uninetz erreichbar

**Comment by xwolfde** [comment]
Mit der Hälfte dieses Test kann ich ehrlich gesagt garnichts anfangen, da das überhaupt nichts mit der Frage des responsiven Verhaltens zu tun hatm sondern damit das ich auf dfer testsite nicht alle Plugins an hab.. Wenn da ein Shortcode sichtbar ist, ist das doch klar, das das gar nichts mit dem responsiven Verhalten zu tun hat...
Ladezeiten ist auch völlig Wumpe, da meine Kiste nicht vergleichbar ist, da dort kein cache an ist und so.. Beistellen Hinweise, Symbole, Dito...
Seufz...

**Comment by xwolfde** [comment]
Auf FAU-Einrichtungen umgesetzt.
Bitte auf test4 testen. Feedback/Probleme bitte melden unter https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues als neue einzelne Fälle.
