### ISSUE TITLE
RSS-Feed-Einbindung defekt

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#302]
Auf http://go.fau.de/x0y504 habe ich testweise RSS-Feeds eingebunden (einen aus einem geschützten Blog, FAU aktuell von uns), aber es wird nichts angezeigt.
Ich habe die URL jeweils mit Hochkommata (auf fau.de verwendet) und mit Zollzeichen angegeben (laut eurem Handbuch). Beides geht nicht.
Wichtig: Welche Syntax nehmen wir denn - die Hochkommata sind veraltet, funktionieren aber auch?

**Comment by wrkb** [comment]
P.S.: bestehende Feeds funktionieren bzw. haben bis vor einigen Wochen funktioniert: https://www.fau.de/universitaet/kennzahlen-und-rankings/rankings/
Auf dieser Seite habe ich auch gerade noch einen Beitrag nachträglich mit dem Feed-Schlagwort versehen, er müsste noch ganz oben eintrudeln (11. November)

**Comment by xwolfde** [comment]
Bitte hierzu mal ein Update geben. Obige Testurl funktioniert nicht

**Comment by wrkb** [comment]
Da hatte Rolf längst repariert, danke :)
