### ISSUE TITLE
Navigation Whitespace

### ISSUE THREAD

**Issue by SebastianHonert** [RRZE-Webteam/FAU-Theme#305]
Wenn das Theme mit einer Auflösung > 767px geladen und das Fenster anschließend verkleinert wird, gibt es bei Mouseover einen sehr störenden Whitespace-Bug in der Navigation (betrifft auch FAU.de).
 
![nav-bug](https://cloud.githubusercontent.com/assets/7110206/12810862/20a4e1a0-cb29-11e5-975e-6a5e4f4e377c.jpg)

Das Problem liegt in der /js/scripts.js . Die Variable isMobile wird nur einmal nach $(document).ready initialisiert. Dadurch ist isMobile statisch:

`var isMobile = windowWidth < 767;`

Lösungsvorschlag:

`var isMobile = function() {
    return windowWidth < 767;
}`

**Comment by SebastianHonert** [comment]
```javascript
var isMobile = function() {
  var windowWidth = window.screen.width < window.outerWidth ? window.screen.width : window.outerWidth;
  return windowWidth < 767;
};
```
Im Quelltext Variable `isMobile` ersetzen durch Funktionsaufruf:

```javascript
isMobile()
```

**Comment by xwolfde** [comment]
Danke wird übernommen. WIr bauen da gerade das ganze resp. Menü um

**Comment by SebastianHonert** [comment]
Das Problem ist leider komplizierter. Habe eine Lösung umgesetzt, schicke ich Dir.

**Comment by xwolfde** [comment]
Ähm... Ja. Wie gesagt, bin ich dran und am Feinschliff. 
vgl. test8.tindu.rrzi-erlangen.de

**Comment by SebastianHonert** [comment]
Testen und Fluchen gehören zum Tagewerk
<http://test8.tindu.rrze.uni-erlangen.de/tests/>

So sieht's aus!

Für das IZ Digital Child Theme habe ich mich an fau.de orientiert:

http://heinze.fim.uni-erlangen.de/wp/wp_iz/

Sobald Deine Lösung verfügbar ist, stellen wir um, gefällt mir gut.

VG


Am 11. Februar 2016 um 15:54 schrieb Wolfgang Wiese <
notifications@github.com>:

> Ähm... Ja. Wie gesagt, bin ich dran und am Feinschliff.
> vgl. test8.tindu.rrzi-erlangen.de
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RRZE-Webteam/FAU-Theme/issues/305#issuecomment-182896519>
> .
>



-- 
Sebastian Honert
Weiselstraße 1
91054 Buckenhof

Telefon: +49 (0)179 9739851
E-Mail: sebastian.honert@googlemail.com
Web: www.sebastianhonert.com
