### ISSUE TITLE
Hauptnavigation im Footer noch einmal (ungewollt)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#311]
...zwar ist das Theme nicht mehr wirklich in Arbeit grad, aber wir teilen trotzdem mal mit, was @csw gefunden hat.  Im Footer der Startseite ist die Hauptnavigation noch einmal verankert, ohne dass es dort speziell platziert wurde. Nur sichtbar, wenn man den Text im Footer markiert. Spezielle Auswirkungen haben wir noch nicht feststellen können.

![2016-09-13 09_51_49-](https://cloud.githubusercontent.com/assets/9445370/18465587/c1bd8bc4-7997-11e6-9d84-8f266a133e90.png)

**Comment by xwolfde** [comment]
Das interessiert mich nicht, was in euren kaputten Theme ist. Dieses Theme wird nicht weiter entwickelt und nicht mehr repariert. Die Reparatur hat den Namen "FAU-Einrichtungen".
