### ISSUE TITLE
Studiengangsdatenbankauszüge: Klick auf Studiengang zeigt ihn dreimal an (je Auszug)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#32]
https://www.fau.de/studium/vor-dem-studium/studiengaenge/internationale-studiengaenge/ --> beliebigen Studiengang auswählen --> scrollen.

Ist dieses Verhalten änderbar? Wenn ja: wenig oder viel Aufwand?

Fiel im IBZ und im RIA auf, scheint durch die Mehrfach-Auszüge im Shortcode zu entstehen.

Danke fürs Gucken, Gruß, Karsten

**Comment by wrkb** [comment]
kann man schließen?

@wrcg

**Comment by wrcg** [comment]
Das Problem der Mehrfachanzeige ist noch nicht behoben. Allerdings habe ich jetzt die Seiten so angelegt, dass nicht mehrere Auszüge auf einer Seite sind. -> von daher können wir es aus meiner Sicht streichen und dann wieder hochholen, wenn wir es benötigen.

Der Wunsch nach dem Link "Alle Studiengänge" bleibt!

**Comment by wrkb** [comment]
Link Alle Studiengänge bitte in ein Neues Issue!
