### ISSUE TITLE
Revisionen für Autoren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Theme#5]
Die Anzeige (und Nutzung?) der Revisionen soll auch für kleinere Userrollen, wie Autoren nutzbar sein.
(besprochen am 23.10.)

**Comment by xwolfde** [comment]
Teil des CMS-Plugins?

**Comment by wrkb** [comment]
@wrcg das ging noch nicht oder?

**Comment by xwolfde** [comment]
Verschoben nach https://github.com/RRZE-Webteam/cms-workflow/issues/30
