### ISSUE TITLE
Suche: Herkunft des Ergebnisses kennzeichnen

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#57]
...vor allem bei Seiten: Da sollte die erste Ebene der Hierarchi ausgewertet werden (1. Portalebene) und am besten auch die zweite dazu (2. Portalebene) - also z.B. 

International - Wege ins Ausland
Studium - Vor dem Studium

Liegt das Suchergebnis selbst höher, dann reduziert sich die Anzeige. Liegt das Ergebnis tiefer (Inhaltsseiten 4. Ebene oder so), dann wird die Herkunft nicht genauer angezeigt - sonst wird es zu unübersichtlicht.

**Comment by xwolfde** [comment]
Teil von #142
