### ISSUE TITLE
Workflow: Rechte von wiederverwendeten Benutzernamen

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#79]
Ich habe einen neuen Nutzer angelegt namens autor. Er ist in keiner Benutzergruppe und hat nirgends Seitenrechte erhalten, darf aber z.B. auf https://www.fau.de/anfahrt-und-lageplan schreiben.

Das wird daran liegen, dass wir schon mal einen Nutzer namens "autor" hatten, der die Seite schreiben durfte, dessen Nutzerkonto war aber mit einer anderen E-Mail-Adresse angelegt. Und wir haben den ersten Nutzer namens autor kurz danach wieder entfernt.

Fazit: Es werden scheinbar Nutzerrechte anhand des Autorennamens vergeben und nie gelöscht, wenn der Nutzer entfernt wird. Ist das gewollt? Durch IdM wird das Problem wohl nicht häufig auftreten, aber so ganz sauber scheint das nicht zu sein...

**Comment by wrkb** [comment]
wir sind nun kein superadmin mehr und können nicht testen. ihr müsstet das nun tun. prio gering.

**Comment by xwolfde** [comment]
Keine Zeit für Digging nach alten Konfigurationen und warum die damals von wem wie gemacht wurde mit welchen Effekten dann; hat auch nichts mit Theme zu tun. Daher closed.
