### ISSUE TITLE
Deutsche Bezeichnung im englischen Kalender, überflüssige Angabe, Detailansicht windschief

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#94]
Ich nerve ungern, aber...

...im englischen Kalender (Detailansicht) taucht noch das deutsche "Uhr" bei der Zeitangabe auf.
...bei gänztägigen Terminen für 12 am bis 12 pm angezeigt - das kann/muss weg, richtig?
...der Text sitzt schief
Schafft ihr das evtl. noch vor dem Livegang? Sonst kurz danach?

![unbenannt](https://cloud.githubusercontent.com/assets/9445370/5244826/b0536f5c-7953-11e4-84db-cf10101f8635.JPG)

**Comment by xwolfde** [comment]
behoben
