### ISSUE TITLE
Kontextspalte: Andere Sortierung der Einträge erlauben (derzeit noch ACF)

### ISSUE THREAD

**Issue by wrkb** [RRZE-Webteam/FAU-Theme#97]
Bsp: https://www.fau.de/studium/im-studium/analyse-der-studiensituation/

Wir können hier nicht den Kontakt über Weitere Informationen stellen, da wir sonst das Freitextfeld nicht nutzen könnten (extended-Parameter geht nur im Textfeld).

Aktuell kann man nicht frei sortieren.

RRZE oder medienreaktor?

**Comment by xwolfde** [comment]
Zusammenhang auch mit #123

**Comment by xwolfde** [comment]
Größerer Aufwand notwendig. Muss zwingend gemacht werdem für die Fakultäten, da das ACF-Repeater-Plugin nutzbar ist für andere installationen.

**Comment by xwolfde** [comment]
Reihenfolge der Felder wäre machbar... Aber würde die gefahr in sich bergen, daß unbedarfte User das zu sehr ausnutzen und Websites somit wieder uneinheitlich werden. Man möchte sich eigentlich gewöhnen, dass an der Stelle und nicht weiter unten dieses oder jenes steht. Das würde hiermit verhindert...
Bei vorhandener Redaktion ist das kontrolllierbar. Aber bei anderen, wo es keine Redaktion gibt und der <s>Wahnsinn</s>..sorry der tägliche Stress und wechselnde Leute subjektiv beeinflusst Inhalte einstellen...?

**Comment by wrkb** [comment]
Die Einheitlichkeit war uns auch wichtig. Aber es hat sich gezeigt, dass je nach Themenbereich (Uni, Forschung, Studium) die Anforderungen verschieden sind - es ist mal wieder die Komplexität der FAU, die sich hier zeigt. In einem Bereich sind etwa die Kontakte oben wichtiger als alles andere, dann ist aber ein wichtiger Freitext-Hinweis darüber auf der einen oder anderen Seite nicht mehr möglich.

Hier gilt für die ZUV (unsere Erfahrungen eben), dass die Leute nicht rumspielen, sondern mit Augenmaß vorgehen bzw. sich mit uns abstimmen. Anderswo weiß ich es nicht.

**Comment by xwolfde** [comment]
Lieber eine zentrale Linkverwaltung, wo ihr alle LInks drin pflegt, oder jeweils pro Seite dann?

**Comment by xwolfde** [comment]
Beispiel zum Vergleich wie ich eine zentrale Linkverwaltung machen würde sind die Werbebanner: Die werden zentral durch eine eigene Lasche gepflegt und dann bei den Seiten zur Auswahl gestellt.

**Comment by wrkb** [comment]
Pro Seite. Denn die Autoren (die dürfen das dann auch bzw. kann man das einstellen im Workflow?) dürfen nur an der Seite bearbeiten und sollen auch die Links selbst wählen. Wir schaffen das nicht für alle 100 Nutzer...

**Comment by wrkb** [comment]
P.S. Bei den Werbebannern ist zentral sinnvoll. Das machen wir.
Brauchst du mal eine Übersicht, was bei uns wie läuft (und was ZUV-only ist)? Brauchen wir selbst auch in Kürze.
@wrcg

**Comment by wrkb** [comment]
Sorry, noch ein Nachtrag: Interne Links heißt ja, dass die Link-Bereiche im Kontext völlig individuell aus allen 1300 Webseiten zusammengestellt werden können. Ich wüsste gar nicht, was ich da zentral pflegen soll :) Die Seitenliste? :)

**Comment by xwolfde** [comment]
Es geht um die externen Links, die internen sind wie bisher genauso.

**Comment by xwolfde** [comment]
also quicklinks external

**Comment by wrkb** [comment]
Achso. Okay, aber auch die können wir nicht pflegen. Es sind Dutzende die wir nicht kennen (nur einmal bei der Übernahme angefasst). Es werden noch mehr.

**Comment by xwolfde** [comment]
Wenn es so viele sind, verschärft sich auf Dauer aber das Problem der Veraltung der Links.

**Comment by wrkb** [comment]
Das ist zum einen korrekt. Zum anderen werden die Seiten anders betreut, sprich, wir haben für jede Seite eine(n) Verantwortliche(n), es gibt keine Waisen mehr. Das durchzuhalten, ist unser Job :) Wir prüfen zudem die Link-Checker-Meldungen (dafür haben wir ja das schöne Tool von euch). Und die Leute melden auch jetzt schon defekte Links.
Ich halte das für machbar (ZUV!)

**Comment by xwolfde** [comment]
Statusupdate. Siehe Notiz in verknüpften Case.

**Comment by xwolfde** [comment]
done in 1.3
